// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;
    
    import com.boundaryml.baml.BamlRuntime;
    import com.boundaryml.baml.BamlEncoder;
    import com.boundaryml.baml.BamlDecoder;
    import com.boundaryml.baml.BamlStream;
    import java.util.LinkedHashMap;
    import java.util.Map;
    import java.util.function.Function;
    
    /**
     * Generated BAML function wrappers. Use Globals.getRuntime() and call these methods.
     * Requires baml-runtime-java for BamlRuntime, encode/decode helpers.
     */
    public final class Functions {
        private final BamlRuntime runtime;
    
        public Functions(BamlRuntime runtime) {
            this.runtime = runtime;
        }
    
    
        public Types.BooleanLiterals TestBooleanLiterals(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestBooleanLiterals", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.BooleanLiterals typed = (Types.BooleanLiterals) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialBooleanLiterals, Types.BooleanLiterals> TestBooleanLiteralsStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialBooleanLiterals> partialDecoder = bytes -> (Types.PartialBooleanLiterals) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.BooleanLiterals> finalDecoder = bytes -> (Types.BooleanLiterals) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestBooleanLiterals", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.ComplexLiterals TestComplexLiterals(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestComplexLiterals", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.ComplexLiterals typed = (Types.ComplexLiterals) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialComplexLiterals, Types.ComplexLiterals> TestComplexLiteralsStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialComplexLiterals> partialDecoder = bytes -> (Types.PartialComplexLiterals) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.ComplexLiterals> finalDecoder = bytes -> (Types.ComplexLiterals) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestComplexLiterals", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.IntegerLiterals TestIntegerLiterals(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestIntegerLiterals", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.IntegerLiterals typed = (Types.IntegerLiterals) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialIntegerLiterals, Types.IntegerLiterals> TestIntegerLiteralsStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialIntegerLiterals> partialDecoder = bytes -> (Types.PartialIntegerLiterals) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.IntegerLiterals> finalDecoder = bytes -> (Types.IntegerLiterals) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestIntegerLiterals", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.MixedLiterals TestMixedLiterals(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestMixedLiterals", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.MixedLiterals typed = (Types.MixedLiterals) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialMixedLiterals, Types.MixedLiterals> TestMixedLiteralsStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialMixedLiterals> partialDecoder = bytes -> (Types.PartialMixedLiterals) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.MixedLiterals> finalDecoder = bytes -> (Types.MixedLiterals) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestMixedLiterals", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.StringLiterals TestStringLiterals(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestStringLiterals", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.StringLiterals typed = (Types.StringLiterals) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialStringLiterals, Types.StringLiterals> TestStringLiteralsStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialStringLiterals> partialDecoder = bytes -> (Types.PartialStringLiterals) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.StringLiterals> finalDecoder = bytes -> (Types.StringLiterals) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestStringLiterals", encoded, partialDecoder, finalDecoder);
        }
    
    
    }
    