// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML class types.
 */
public class Types {
    public static class BooleanLiterals {
        private boolean alwaysTrue;
        private boolean alwaysFalse;
        private Union2BoolOrBool eitherBool;

        public boolean getAlwaysTrue() {
            return this.alwaysTrue;
        }

        public void setAlwaysTrue(boolean alwaysTrue) {
            this.alwaysTrue = alwaysTrue;
        }
        public boolean getAlwaysFalse() {
            return this.alwaysFalse;
        }

        public void setAlwaysFalse(boolean alwaysFalse) {
            this.alwaysFalse = alwaysFalse;
        }
        public Union2BoolOrBool getEitherBool() {
            return this.eitherBool;
        }

        public void setEitherBool(Union2BoolOrBool eitherBool) {
            this.eitherBool = eitherBool;
        }
    }

    public static class PartialBooleanLiterals {
        private boolean alwaysTrue;
        private boolean alwaysFalse;
        private java.util.Optional<Unions.Union2BoolOrBool> eitherBool;

        public boolean getAlwaysTrue() {
            return this.alwaysTrue;
        }

        public void setAlwaysTrue(boolean alwaysTrue) {
            this.alwaysTrue = alwaysTrue;
        }
        public boolean getAlwaysFalse() {
            return this.alwaysFalse;
        }

        public void setAlwaysFalse(boolean alwaysFalse) {
            this.alwaysFalse = alwaysFalse;
        }
        public java.util.Optional<Unions.Union2BoolOrBool> getEitherBool() {
            return this.eitherBool;
        }

        public void setEitherBool(java.util.Optional<Unions.Union2BoolOrBool> eitherBool) {
            this.eitherBool = eitherBool;
        }
    }
    public static class ComplexLiterals {
        private Union4StringOrStringOrStringOrString state;
        private Union7IntOrIntOrIntOrIntOrIntOrIntOrInt retryCount;
        private Union3StringOrStringOrString response;
        private java.util.List<Union2BoolOrBool> flags;
        private java.util.List<Union3IntOrIntOrInt> codes;

        public Union4StringOrStringOrStringOrString getState() {
            return this.state;
        }

        public void setState(Union4StringOrStringOrStringOrString state) {
            this.state = state;
        }
        public Union7IntOrIntOrIntOrIntOrIntOrIntOrInt getRetryCount() {
            return this.retryCount;
        }

        public void setRetryCount(Union7IntOrIntOrIntOrIntOrIntOrIntOrInt retryCount) {
            this.retryCount = retryCount;
        }
        public Union3StringOrStringOrString getResponse() {
            return this.response;
        }

        public void setResponse(Union3StringOrStringOrString response) {
            this.response = response;
        }
        public java.util.List<Union2BoolOrBool> getFlags() {
            return this.flags;
        }

        public void setFlags(java.util.List<Union2BoolOrBool> flags) {
            this.flags = flags;
        }
        public java.util.List<Union3IntOrIntOrInt> getCodes() {
            return this.codes;
        }

        public void setCodes(java.util.List<Union3IntOrIntOrInt> codes) {
            this.codes = codes;
        }
    }

    public static class PartialComplexLiterals {
        private java.util.Optional<Unions.Union4StringOrStringOrStringOrString> state;
        private java.util.Optional<Unions.Union7IntOrIntOrIntOrIntOrIntOrIntOrInt> retryCount;
        private java.util.Optional<Unions.Union3StringOrStringOrString> response;
        private java.util.Optional<java.util.List<Union2BoolOrBool>> flags;
        private java.util.Optional<java.util.List<Union3IntOrIntOrInt>> codes;

        public java.util.Optional<Unions.Union4StringOrStringOrStringOrString> getState() {
            return this.state;
        }

        public void setState(java.util.Optional<Unions.Union4StringOrStringOrStringOrString> state) {
            this.state = state;
        }
        public java.util.Optional<Unions.Union7IntOrIntOrIntOrIntOrIntOrIntOrInt> getRetryCount() {
            return this.retryCount;
        }

        public void setRetryCount(java.util.Optional<Unions.Union7IntOrIntOrIntOrIntOrIntOrIntOrInt> retryCount) {
            this.retryCount = retryCount;
        }
        public java.util.Optional<Unions.Union3StringOrStringOrString> getResponse() {
            return this.response;
        }

        public void setResponse(java.util.Optional<Unions.Union3StringOrStringOrString> response) {
            this.response = response;
        }
        public java.util.Optional<java.util.List<Union2BoolOrBool>> getFlags() {
            return this.flags;
        }

        public void setFlags(java.util.Optional<java.util.List<Union2BoolOrBool>> flags) {
            this.flags = flags;
        }
        public java.util.Optional<java.util.List<Union3IntOrIntOrInt>> getCodes() {
            return this.codes;
        }

        public void setCodes(java.util.Optional<java.util.List<Union3IntOrIntOrInt>> codes) {
            this.codes = codes;
        }
    }
    public static class IntegerLiterals {
        private Union5IntOrIntOrIntOrIntOrInt priority;
        private Union5IntOrIntOrIntOrIntOrInt httpStatus;
        private Union4IntOrIntOrIntOrInt maxRetries;

        public Union5IntOrIntOrIntOrIntOrInt getPriority() {
            return this.priority;
        }

        public void setPriority(Union5IntOrIntOrIntOrIntOrInt priority) {
            this.priority = priority;
        }
        public Union5IntOrIntOrIntOrIntOrInt getHttpStatus() {
            return this.httpStatus;
        }

        public void setHttpStatus(Union5IntOrIntOrIntOrIntOrInt httpStatus) {
            this.httpStatus = httpStatus;
        }
        public Union4IntOrIntOrIntOrInt getMaxRetries() {
            return this.maxRetries;
        }

        public void setMaxRetries(Union4IntOrIntOrIntOrInt maxRetries) {
            this.maxRetries = maxRetries;
        }
    }

    public static class PartialIntegerLiterals {
        private java.util.Optional<Unions.Union5IntOrIntOrIntOrIntOrInt> priority;
        private java.util.Optional<Unions.Union5IntOrIntOrIntOrIntOrInt> httpStatus;
        private java.util.Optional<Unions.Union4IntOrIntOrIntOrInt> maxRetries;

        public java.util.Optional<Unions.Union5IntOrIntOrIntOrIntOrInt> getPriority() {
            return this.priority;
        }

        public void setPriority(java.util.Optional<Unions.Union5IntOrIntOrIntOrIntOrInt> priority) {
            this.priority = priority;
        }
        public java.util.Optional<Unions.Union5IntOrIntOrIntOrIntOrInt> getHttpStatus() {
            return this.httpStatus;
        }

        public void setHttpStatus(java.util.Optional<Unions.Union5IntOrIntOrIntOrIntOrInt> httpStatus) {
            this.httpStatus = httpStatus;
        }
        public java.util.Optional<Unions.Union4IntOrIntOrIntOrInt> getMaxRetries() {
            return this.maxRetries;
        }

        public void setMaxRetries(java.util.Optional<Unions.Union4IntOrIntOrIntOrInt> maxRetries) {
            this.maxRetries = maxRetries;
        }
    }
    public static class MixedLiterals {
        private long id;
        private Union3StringOrStringOrString type;
        private Union3IntOrIntOrInt level;
        private Union2BoolOrBool isActive;
        private Union3StringOrStringOrString apiVersion;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public Union3StringOrStringOrString getType() {
            return this.type;
        }

        public void setType(Union3StringOrStringOrString type) {
            this.type = type;
        }
        public Union3IntOrIntOrInt getLevel() {
            return this.level;
        }

        public void setLevel(Union3IntOrIntOrInt level) {
            this.level = level;
        }
        public Union2BoolOrBool getIsActive() {
            return this.isActive;
        }

        public void setIsActive(Union2BoolOrBool isActive) {
            this.isActive = isActive;
        }
        public Union3StringOrStringOrString getApiVersion() {
            return this.apiVersion;
        }

        public void setApiVersion(Union3StringOrStringOrString apiVersion) {
            this.apiVersion = apiVersion;
        }
    }

    public static class PartialMixedLiterals {
        private long id;
        private java.util.Optional<Unions.Union3StringOrStringOrString> type;
        private java.util.Optional<Unions.Union3IntOrIntOrInt> level;
        private java.util.Optional<Unions.Union2BoolOrBool> isActive;
        private java.util.Optional<Unions.Union3StringOrStringOrString> apiVersion;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public java.util.Optional<Unions.Union3StringOrStringOrString> getType() {
            return this.type;
        }

        public void setType(java.util.Optional<Unions.Union3StringOrStringOrString> type) {
            this.type = type;
        }
        public java.util.Optional<Unions.Union3IntOrIntOrInt> getLevel() {
            return this.level;
        }

        public void setLevel(java.util.Optional<Unions.Union3IntOrIntOrInt> level) {
            this.level = level;
        }
        public java.util.Optional<Unions.Union2BoolOrBool> getIsActive() {
            return this.isActive;
        }

        public void setIsActive(java.util.Optional<Unions.Union2BoolOrBool> isActive) {
            this.isActive = isActive;
        }
        public java.util.Optional<Unions.Union3StringOrStringOrString> getApiVersion() {
            return this.apiVersion;
        }

        public void setApiVersion(java.util.Optional<Unions.Union3StringOrStringOrString> apiVersion) {
            this.apiVersion = apiVersion;
        }
    }
    public static class StringLiterals {
        private Union3StringOrStringOrString status;
        private Union3StringOrStringOrString environment;
        private Union4StringOrStringOrStringOrString method;

        public Union3StringOrStringOrString getStatus() {
            return this.status;
        }

        public void setStatus(Union3StringOrStringOrString status) {
            this.status = status;
        }
        public Union3StringOrStringOrString getEnvironment() {
            return this.environment;
        }

        public void setEnvironment(Union3StringOrStringOrString environment) {
            this.environment = environment;
        }
        public Union4StringOrStringOrStringOrString getMethod() {
            return this.method;
        }

        public void setMethod(Union4StringOrStringOrStringOrString method) {
            this.method = method;
        }
    }

    public static class PartialStringLiterals {
        private java.util.Optional<Unions.Union3StringOrStringOrString> status;
        private java.util.Optional<Unions.Union3StringOrStringOrString> environment;
        private java.util.Optional<Unions.Union4StringOrStringOrStringOrString> method;

        public java.util.Optional<Unions.Union3StringOrStringOrString> getStatus() {
            return this.status;
        }

        public void setStatus(java.util.Optional<Unions.Union3StringOrStringOrString> status) {
            this.status = status;
        }
        public java.util.Optional<Unions.Union3StringOrStringOrString> getEnvironment() {
            return this.environment;
        }

        public void setEnvironment(java.util.Optional<Unions.Union3StringOrStringOrString> environment) {
            this.environment = environment;
        }
        public java.util.Optional<Unions.Union4StringOrStringOrStringOrString> getMethod() {
            return this.method;
        }

        public void setMethod(java.util.Optional<Unions.Union4StringOrStringOrStringOrString> method) {
            this.method = method;
        }
    }
}
