// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML union types.
 */
public class Unions {

    public static final class Union2BoolOrBool {

        private final Boolean value0;

        private final Boolean value1;


        private Union2BoolOrBool(Boolean value0, Boolean value1) {

            this.value0 = value0;

            this.value1 = value1;

        }


        public static Union2BoolOrBool ofVariant0(Boolean value) {
            return new Union2BoolOrBool(value, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public Boolean getVariant0() {
            return this.value0;
        }

        public static Union2BoolOrBool ofVariant1(Boolean value) {
            return new Union2BoolOrBool(null, value);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Boolean getVariant1() {
            return this.value1;
        }

    }

    public static final class Union3IntOrIntOrInt {

        private final Long value0;

        private final Long value1;

        private final Long value2;


        private Union3IntOrIntOrInt(Long value0, Long value1, Long value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3IntOrIntOrInt ofVariant0(Long value) {
            return new Union3IntOrIntOrInt(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public Long getVariant0() {
            return this.value0;
        }

        public static Union3IntOrIntOrInt ofVariant1(Long value) {
            return new Union3IntOrIntOrInt(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union3IntOrIntOrInt ofVariant2(Long value) {
            return new Union3IntOrIntOrInt(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Long getVariant2() {
            return this.value2;
        }

    }

    public static final class Union3StringOrStringOrString {

        private final String value0;

        private final String value1;

        private final String value2;


        private Union3StringOrStringOrString(String value0, String value1, String value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3StringOrStringOrString ofVariant0(String value) {
            return new Union3StringOrStringOrString(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union3StringOrStringOrString ofVariant1(String value) {
            return new Union3StringOrStringOrString(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public String getVariant1() {
            return this.value1;
        }

        public static Union3StringOrStringOrString ofVariant2(String value) {
            return new Union3StringOrStringOrString(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public String getVariant2() {
            return this.value2;
        }

    }

    public static final class Union4IntOrIntOrIntOrInt {

        private final Long value0;

        private final Long value1;

        private final Long value2;

        private final Long value3;


        private Union4IntOrIntOrIntOrInt(Long value0, Long value1, Long value2, Long value3) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

        }


        public static Union4IntOrIntOrIntOrInt ofVariant0(Long value) {
            return new Union4IntOrIntOrIntOrInt(value, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public Long getVariant0() {
            return this.value0;
        }

        public static Union4IntOrIntOrIntOrInt ofVariant1(Long value) {
            return new Union4IntOrIntOrIntOrInt(null, value, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union4IntOrIntOrIntOrInt ofVariant2(Long value) {
            return new Union4IntOrIntOrIntOrInt(null, null, value, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Long getVariant2() {
            return this.value2;
        }

        public static Union4IntOrIntOrIntOrInt ofVariant3(Long value) {
            return new Union4IntOrIntOrIntOrInt(null, null, null, value);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public Long getVariant3() {
            return this.value3;
        }

    }

    public static final class Union4StringOrStringOrStringOrString {

        private final String value0;

        private final String value1;

        private final String value2;

        private final String value3;


        private Union4StringOrStringOrStringOrString(String value0, String value1, String value2, String value3) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

        }


        public static Union4StringOrStringOrStringOrString ofVariant0(String value) {
            return new Union4StringOrStringOrStringOrString(value, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union4StringOrStringOrStringOrString ofVariant1(String value) {
            return new Union4StringOrStringOrStringOrString(null, value, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public String getVariant1() {
            return this.value1;
        }

        public static Union4StringOrStringOrStringOrString ofVariant2(String value) {
            return new Union4StringOrStringOrStringOrString(null, null, value, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public String getVariant2() {
            return this.value2;
        }

        public static Union4StringOrStringOrStringOrString ofVariant3(String value) {
            return new Union4StringOrStringOrStringOrString(null, null, null, value);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public String getVariant3() {
            return this.value3;
        }

    }

    public static final class Union5IntOrIntOrIntOrIntOrInt {

        private final Long value0;

        private final Long value1;

        private final Long value2;

        private final Long value3;

        private final Long value4;


        private Union5IntOrIntOrIntOrIntOrInt(Long value0, Long value1, Long value2, Long value3, Long value4) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

            this.value4 = value4;

        }


        public static Union5IntOrIntOrIntOrIntOrInt ofVariant0(Long value) {
            return new Union5IntOrIntOrIntOrIntOrInt(value, null, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public Long getVariant0() {
            return this.value0;
        }

        public static Union5IntOrIntOrIntOrIntOrInt ofVariant1(Long value) {
            return new Union5IntOrIntOrIntOrIntOrInt(null, value, null, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union5IntOrIntOrIntOrIntOrInt ofVariant2(Long value) {
            return new Union5IntOrIntOrIntOrIntOrInt(null, null, value, null, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Long getVariant2() {
            return this.value2;
        }

        public static Union5IntOrIntOrIntOrIntOrInt ofVariant3(Long value) {
            return new Union5IntOrIntOrIntOrIntOrInt(null, null, null, value, null);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public Long getVariant3() {
            return this.value3;
        }

        public static Union5IntOrIntOrIntOrIntOrInt ofVariant4(Long value) {
            return new Union5IntOrIntOrIntOrIntOrInt(null, null, null, null, value);
        }

        public boolean isVariant4() {
            return this.value4 != null;
        }

        public Long getVariant4() {
            return this.value4;
        }

    }

    public static final class Union7IntOrIntOrIntOrIntOrIntOrIntOrInt {

        private final Long value0;

        private final Long value1;

        private final Long value2;

        private final Long value3;

        private final Long value4;

        private final Long value5;

        private final Long value6;


        private Union7IntOrIntOrIntOrIntOrIntOrIntOrInt(Long value0, Long value1, Long value2, Long value3, Long value4, Long value5, Long value6) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

            this.value4 = value4;

            this.value5 = value5;

            this.value6 = value6;

        }


        public static Union7IntOrIntOrIntOrIntOrIntOrIntOrInt ofVariant0(Long value) {
            return new Union7IntOrIntOrIntOrIntOrIntOrIntOrInt(value, null, null, null, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public Long getVariant0() {
            return this.value0;
        }

        public static Union7IntOrIntOrIntOrIntOrIntOrIntOrInt ofVariant1(Long value) {
            return new Union7IntOrIntOrIntOrIntOrIntOrIntOrInt(null, value, null, null, null, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union7IntOrIntOrIntOrIntOrIntOrIntOrInt ofVariant2(Long value) {
            return new Union7IntOrIntOrIntOrIntOrIntOrIntOrInt(null, null, value, null, null, null, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Long getVariant2() {
            return this.value2;
        }

        public static Union7IntOrIntOrIntOrIntOrIntOrIntOrInt ofVariant3(Long value) {
            return new Union7IntOrIntOrIntOrIntOrIntOrIntOrInt(null, null, null, value, null, null, null);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public Long getVariant3() {
            return this.value3;
        }

        public static Union7IntOrIntOrIntOrIntOrIntOrIntOrInt ofVariant4(Long value) {
            return new Union7IntOrIntOrIntOrIntOrIntOrIntOrInt(null, null, null, null, value, null, null);
        }

        public boolean isVariant4() {
            return this.value4 != null;
        }

        public Long getVariant4() {
            return this.value4;
        }

        public static Union7IntOrIntOrIntOrIntOrIntOrIntOrInt ofVariant5(Long value) {
            return new Union7IntOrIntOrIntOrIntOrIntOrIntOrInt(null, null, null, null, null, value, null);
        }

        public boolean isVariant5() {
            return this.value5 != null;
        }

        public Long getVariant5() {
            return this.value5;
        }

        public static Union7IntOrIntOrIntOrIntOrIntOrIntOrInt ofVariant6(Long value) {
            return new Union7IntOrIntOrIntOrIntOrIntOrIntOrInt(null, null, null, null, null, null, value);
        }

        public boolean isVariant6() {
            return this.value6 != null;
        }

        public Long getVariant6() {
            return this.value6;
        }

    }

}
