// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;
    
    import com.boundaryml.baml.BamlRuntime;
    import com.boundaryml.baml.BamlEncoder;
    import com.boundaryml.baml.BamlDecoder;
    import com.boundaryml.baml.BamlStream;
    import java.util.LinkedHashMap;
    import java.util.Map;
    import java.util.function.Function;
    
    /**
     * Generated BAML function wrappers. Use Globals.getRuntime() and call these methods.
     * Requires baml-runtime-java for BamlRuntime, encode/decode helpers.
     */
    public final class Functions {
        private final BamlRuntime runtime;
    
        public Functions(BamlRuntime runtime) {
            this.runtime = runtime;
        }
    
    
        public Types.MediaArrayAnalysisResult TestMediaArrayInputs(java.util.List<Object> imageArray, String textInput) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("imageArray", imageArray);
            kwargs.put("textInput", textInput);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestMediaArrayInputs", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.MediaArrayAnalysisResult typed = (Types.MediaArrayAnalysisResult) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialMediaArrayAnalysisResult, Types.MediaArrayAnalysisResult> TestMediaArrayInputsStream(java.util.List<Object> imageArray, String textInput) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("imageArray", imageArray);
            kwargs.put("textInput", textInput);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialMediaArrayAnalysisResult> partialDecoder = bytes -> (Types.PartialMediaArrayAnalysisResult) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.MediaArrayAnalysisResult> finalDecoder = bytes -> (Types.MediaArrayAnalysisResult) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestMediaArrayInputs", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.MediaAnalysisResult TestMediaInput(Unions.Union4AnyOrAnyOrAnyOrAny media, String textInput) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("media", media);
            kwargs.put("textInput", textInput);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestMediaInput", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.MediaAnalysisResult typed = (Types.MediaAnalysisResult) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialMediaAnalysisResult, Types.MediaAnalysisResult> TestMediaInputStream(Unions.Union4AnyOrAnyOrAnyOrAny media, String textInput) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("media", media);
            kwargs.put("textInput", textInput);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialMediaAnalysisResult> partialDecoder = bytes -> (Types.PartialMediaAnalysisResult) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.MediaAnalysisResult> finalDecoder = bytes -> (Types.MediaAnalysisResult) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestMediaInput", encoded, partialDecoder, finalDecoder);
        }
    
    
    }
    