// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML class types.
 */
public class Types {
    public static class MediaAnalysisResult {
        private java.util.List<String> topics;
        private String analysisText;

        public java.util.List<String> getTopics() {
            return this.topics;
        }

        public void setTopics(java.util.List<String> topics) {
            this.topics = topics;
        }
        public String getAnalysisText() {
            return this.analysisText;
        }

        public void setAnalysisText(String analysisText) {
            this.analysisText = analysisText;
        }
    }

    public static class PartialMediaAnalysisResult {
        private java.util.Optional<java.util.List<String>> topics;
        private String analysisText;

        public java.util.Optional<java.util.List<String>> getTopics() {
            return this.topics;
        }

        public void setTopics(java.util.Optional<java.util.List<String>> topics) {
            this.topics = topics;
        }
        public String getAnalysisText() {
            return this.analysisText;
        }

        public void setAnalysisText(String analysisText) {
            this.analysisText = analysisText;
        }
    }
    public static class MediaArrayAnalysisResult {
        private String analysisText;
        private long mediaCount;

        public String getAnalysisText() {
            return this.analysisText;
        }

        public void setAnalysisText(String analysisText) {
            this.analysisText = analysisText;
        }
        public long getMediaCount() {
            return this.mediaCount;
        }

        public void setMediaCount(long mediaCount) {
            this.mediaCount = mediaCount;
        }
    }

    public static class PartialMediaArrayAnalysisResult {
        private String analysisText;
        private long mediaCount;

        public String getAnalysisText() {
            return this.analysisText;
        }

        public void setAnalysisText(String analysisText) {
            this.analysisText = analysisText;
        }
        public long getMediaCount() {
            return this.mediaCount;
        }

        public void setMediaCount(long mediaCount) {
            this.mediaCount = mediaCount;
        }
    }
    public static class MediaMapAnalysisResult {
        private String analysisText;
        private long keyCount;
        private java.util.List<String> keys;

        public String getAnalysisText() {
            return this.analysisText;
        }

        public void setAnalysisText(String analysisText) {
            this.analysisText = analysisText;
        }
        public long getKeyCount() {
            return this.keyCount;
        }

        public void setKeyCount(long keyCount) {
            this.keyCount = keyCount;
        }
        public java.util.List<String> getKeys() {
            return this.keys;
        }

        public void setKeys(java.util.List<String> keys) {
            this.keys = keys;
        }
    }

    public static class PartialMediaMapAnalysisResult {
        private String analysisText;
        private long keyCount;
        private java.util.Optional<java.util.List<String>> keys;

        public String getAnalysisText() {
            return this.analysisText;
        }

        public void setAnalysisText(String analysisText) {
            this.analysisText = analysisText;
        }
        public long getKeyCount() {
            return this.keyCount;
        }

        public void setKeyCount(long keyCount) {
            this.keyCount = keyCount;
        }
        public java.util.Optional<java.util.List<String>> getKeys() {
            return this.keys;
        }

        public void setKeys(java.util.Optional<java.util.List<String>> keys) {
            this.keys = keys;
        }
    }
    public static class MixedMediaAnalysisResult {
        private String title;
        private String description;
        private boolean hasImage;
        private boolean hasVideo;
        private boolean hasAudio;
        private boolean hasPdf;
        private long additionalImageCount;
        private java.util.List<String> metadataKeys;

        public String getTitle() {
            return this.title;
        }

        public void setTitle(String title) {
            this.title = title;
        }
        public String getDescription() {
            return this.description;
        }

        public void setDescription(String description) {
            this.description = description;
        }
        public boolean getHasImage() {
            return this.hasImage;
        }

        public void setHasImage(boolean hasImage) {
            this.hasImage = hasImage;
        }
        public boolean getHasVideo() {
            return this.hasVideo;
        }

        public void setHasVideo(boolean hasVideo) {
            this.hasVideo = hasVideo;
        }
        public boolean getHasAudio() {
            return this.hasAudio;
        }

        public void setHasAudio(boolean hasAudio) {
            this.hasAudio = hasAudio;
        }
        public boolean getHasPdf() {
            return this.hasPdf;
        }

        public void setHasPdf(boolean hasPdf) {
            this.hasPdf = hasPdf;
        }
        public long getAdditionalImageCount() {
            return this.additionalImageCount;
        }

        public void setAdditionalImageCount(long additionalImageCount) {
            this.additionalImageCount = additionalImageCount;
        }
        public java.util.List<String> getMetadataKeys() {
            return this.metadataKeys;
        }

        public void setMetadataKeys(java.util.List<String> metadataKeys) {
            this.metadataKeys = metadataKeys;
        }
    }

    public static class PartialMixedMediaAnalysisResult {
        private String title;
        private String description;
        private boolean hasImage;
        private boolean hasVideo;
        private boolean hasAudio;
        private boolean hasPdf;
        private long additionalImageCount;
        private java.util.Optional<java.util.List<String>> metadataKeys;

        public String getTitle() {
            return this.title;
        }

        public void setTitle(String title) {
            this.title = title;
        }
        public String getDescription() {
            return this.description;
        }

        public void setDescription(String description) {
            this.description = description;
        }
        public boolean getHasImage() {
            return this.hasImage;
        }

        public void setHasImage(boolean hasImage) {
            this.hasImage = hasImage;
        }
        public boolean getHasVideo() {
            return this.hasVideo;
        }

        public void setHasVideo(boolean hasVideo) {
            this.hasVideo = hasVideo;
        }
        public boolean getHasAudio() {
            return this.hasAudio;
        }

        public void setHasAudio(boolean hasAudio) {
            this.hasAudio = hasAudio;
        }
        public boolean getHasPdf() {
            return this.hasPdf;
        }

        public void setHasPdf(boolean hasPdf) {
            this.hasPdf = hasPdf;
        }
        public long getAdditionalImageCount() {
            return this.additionalImageCount;
        }

        public void setAdditionalImageCount(long additionalImageCount) {
            this.additionalImageCount = additionalImageCount;
        }
        public java.util.Optional<java.util.List<String>> getMetadataKeys() {
            return this.metadataKeys;
        }

        public void setMetadataKeys(java.util.Optional<java.util.List<String>> metadataKeys) {
            this.metadataKeys = metadataKeys;
        }
    }
    public static class OptionalMediaAnalysisResult {
        private String analysisText;
        private java.util.List<String> providedMediaTypes;
        private java.util.List<String> missingMediaTypes;

        public String getAnalysisText() {
            return this.analysisText;
        }

        public void setAnalysisText(String analysisText) {
            this.analysisText = analysisText;
        }
        public java.util.List<String> getProvidedMediaTypes() {
            return this.providedMediaTypes;
        }

        public void setProvidedMediaTypes(java.util.List<String> providedMediaTypes) {
            this.providedMediaTypes = providedMediaTypes;
        }
        public java.util.List<String> getMissingMediaTypes() {
            return this.missingMediaTypes;
        }

        public void setMissingMediaTypes(java.util.List<String> missingMediaTypes) {
            this.missingMediaTypes = missingMediaTypes;
        }
    }

    public static class PartialOptionalMediaAnalysisResult {
        private String analysisText;
        private java.util.Optional<java.util.List<String>> providedMediaTypes;
        private java.util.Optional<java.util.List<String>> missingMediaTypes;

        public String getAnalysisText() {
            return this.analysisText;
        }

        public void setAnalysisText(String analysisText) {
            this.analysisText = analysisText;
        }
        public java.util.Optional<java.util.List<String>> getProvidedMediaTypes() {
            return this.providedMediaTypes;
        }

        public void setProvidedMediaTypes(java.util.Optional<java.util.List<String>> providedMediaTypes) {
            this.providedMediaTypes = providedMediaTypes;
        }
        public java.util.Optional<java.util.List<String>> getMissingMediaTypes() {
            return this.missingMediaTypes;
        }

        public void setMissingMediaTypes(java.util.Optional<java.util.List<String>> missingMediaTypes) {
            this.missingMediaTypes = missingMediaTypes;
        }
    }
}
