// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML union types.
 */
public class Unions {

    public static final class Union4AnyOrAnyOrAnyOrAny {

        private final Object value0;

        private final Object value1;

        private final Object value2;

        private final Object value3;


        private Union4AnyOrAnyOrAnyOrAny(Object value0, Object value1, Object value2, Object value3) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

        }


        public static Union4AnyOrAnyOrAnyOrAny ofVariant0(Object value) {
            return new Union4AnyOrAnyOrAnyOrAny(value, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public Object getVariant0() {
            return this.value0;
        }

        public static Union4AnyOrAnyOrAnyOrAny ofVariant1(Object value) {
            return new Union4AnyOrAnyOrAnyOrAny(null, value, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Object getVariant1() {
            return this.value1;
        }

        public static Union4AnyOrAnyOrAnyOrAny ofVariant2(Object value) {
            return new Union4AnyOrAnyOrAnyOrAny(null, null, value, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Object getVariant2() {
            return this.value2;
        }

        public static Union4AnyOrAnyOrAnyOrAny ofVariant3(Object value) {
            return new Union4AnyOrAnyOrAnyOrAny(null, null, null, value);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public Object getVariant3() {
            return this.value3;
        }

    }

}
