// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;
    
    import com.boundaryml.baml.BamlRuntime;
    import com.boundaryml.baml.BamlEncoder;
    import com.boundaryml.baml.BamlDecoder;
    import com.boundaryml.baml.BamlStream;
    import java.util.LinkedHashMap;
    import java.util.Map;
    import java.util.function.Function;
    
    /**
     * Generated BAML function wrappers. Use Globals.getRuntime() and call these methods.
     * Requires baml-runtime-java for BamlRuntime, encode/decode helpers.
     */
    public final class Functions {
        private final BamlRuntime runtime;
    
        public Functions(BamlRuntime runtime) {
            this.runtime = runtime;
        }
    
    
        public Types.ComplexNested TestComplexNested(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestComplexNested", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.ComplexNested typed = (Types.ComplexNested) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialComplexNested, Types.ComplexNested> TestComplexNestedStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialComplexNested> partialDecoder = bytes -> (Types.PartialComplexNested) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.ComplexNested> finalDecoder = bytes -> (Types.ComplexNested) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestComplexNested", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.DeeplyNested TestDeeplyNested(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestDeeplyNested", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.DeeplyNested typed = (Types.DeeplyNested) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialDeeplyNested, Types.DeeplyNested> TestDeeplyNestedStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialDeeplyNested> partialDecoder = bytes -> (Types.PartialDeeplyNested) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.DeeplyNested> finalDecoder = bytes -> (Types.DeeplyNested) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestDeeplyNested", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.RecursiveStructure TestRecursiveStructure(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestRecursiveStructure", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.RecursiveStructure typed = (Types.RecursiveStructure) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialRecursiveStructure, Types.RecursiveStructure> TestRecursiveStructureStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialRecursiveStructure> partialDecoder = bytes -> (Types.PartialRecursiveStructure) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.RecursiveStructure> finalDecoder = bytes -> (Types.RecursiveStructure) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestRecursiveStructure", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.SimpleNested TestSimpleNested(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestSimpleNested", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.SimpleNested typed = (Types.SimpleNested) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialSimpleNested, Types.SimpleNested> TestSimpleNestedStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialSimpleNested> partialDecoder = bytes -> (Types.PartialSimpleNested) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.SimpleNested> finalDecoder = bytes -> (Types.SimpleNested) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestSimpleNested", encoded, partialDecoder, finalDecoder);
        }
    
    
    }
    