// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML class types.
 */
public class Types {
    public static class Address {
        private String street;
        private String city;
        private String state;
        private String country;
        private String postalCode;
        private java.util.Optional<Coordinates> coordinates;

        public String getStreet() {
            return this.street;
        }

        public void setStreet(String street) {
            this.street = street;
        }
        public String getCity() {
            return this.city;
        }

        public void setCity(String city) {
            this.city = city;
        }
        public String getState() {
            return this.state;
        }

        public void setState(String state) {
            this.state = state;
        }
        public String getCountry() {
            return this.country;
        }

        public void setCountry(String country) {
            this.country = country;
        }
        public String getPostalCode() {
            return this.postalCode;
        }

        public void setPostalCode(String postalCode) {
            this.postalCode = postalCode;
        }
        public java.util.Optional<Coordinates> getCoordinates() {
            return this.coordinates;
        }

        public void setCoordinates(java.util.Optional<Coordinates> coordinates) {
            this.coordinates = coordinates;
        }
    }

    public static class PartialAddress {
        private String street;
        private String city;
        private String state;
        private String country;
        private String postalCode;
        private java.util.Optional<Coordinates> coordinates;

        public String getStreet() {
            return this.street;
        }

        public void setStreet(String street) {
            this.street = street;
        }
        public String getCity() {
            return this.city;
        }

        public void setCity(String city) {
            this.city = city;
        }
        public String getState() {
            return this.state;
        }

        public void setState(String state) {
            this.state = state;
        }
        public String getCountry() {
            return this.country;
        }

        public void setCountry(String country) {
            this.country = country;
        }
        public String getPostalCode() {
            return this.postalCode;
        }

        public void setPostalCode(String postalCode) {
            this.postalCode = postalCode;
        }
        public java.util.Optional<Coordinates> getCoordinates() {
            return this.coordinates;
        }

        public void setCoordinates(java.util.Optional<Coordinates> coordinates) {
            this.coordinates = coordinates;
        }
    }
    public static class Approval {
        private String approver;
        private String date;
        private double amount;
        private java.util.Optional<String> notes;

        public String getApprover() {
            return this.approver;
        }

        public void setApprover(String approver) {
            this.approver = approver;
        }
        public String getDate() {
            return this.date;
        }

        public void setDate(String date) {
            this.date = date;
        }
        public double getAmount() {
            return this.amount;
        }

        public void setAmount(double amount) {
            this.amount = amount;
        }
        public java.util.Optional<String> getNotes() {
            return this.notes;
        }

        public void setNotes(java.util.Optional<String> notes) {
            this.notes = notes;
        }
    }

    public static class PartialApproval {
        private String approver;
        private String date;
        private double amount;
        private java.util.Optional<String> notes;

        public String getApprover() {
            return this.approver;
        }

        public void setApprover(String approver) {
            this.approver = approver;
        }
        public String getDate() {
            return this.date;
        }

        public void setDate(String date) {
            this.date = date;
        }
        public double getAmount() {
            return this.amount;
        }

        public void setAmount(double amount) {
            this.amount = amount;
        }
        public java.util.Optional<String> getNotes() {
            return this.notes;
        }

        public void setNotes(java.util.Optional<String> notes) {
            this.notes = notes;
        }
    }
    public static class Budget {
        private double total;
        private double spent;
        private java.util.Map<String, double> categories;
        private java.util.List<Approval> approvals;

        public double getTotal() {
            return this.total;
        }

        public void setTotal(double total) {
            this.total = total;
        }
        public double getSpent() {
            return this.spent;
        }

        public void setSpent(double spent) {
            this.spent = spent;
        }
        public java.util.Map<String, double> getCategories() {
            return this.categories;
        }

        public void setCategories(java.util.Map<String, double> categories) {
            this.categories = categories;
        }
        public java.util.List<Approval> getApprovals() {
            return this.approvals;
        }

        public void setApprovals(java.util.List<Approval> approvals) {
            this.approvals = approvals;
        }
    }

    public static class PartialBudget {
        private double total;
        private double spent;
        private java.util.Optional<java.util.Map<String, double>> categories;
        private java.util.Optional<java.util.List<Approval>> approvals;

        public double getTotal() {
            return this.total;
        }

        public void setTotal(double total) {
            this.total = total;
        }
        public double getSpent() {
            return this.spent;
        }

        public void setSpent(double spent) {
            this.spent = spent;
        }
        public java.util.Optional<java.util.Map<String, double>> getCategories() {
            return this.categories;
        }

        public void setCategories(java.util.Optional<java.util.Map<String, double>> categories) {
            this.categories = categories;
        }
        public java.util.Optional<java.util.List<Approval>> getApprovals() {
            return this.approvals;
        }

        public void setApprovals(java.util.Optional<java.util.List<Approval>> approvals) {
            this.approvals = approvals;
        }
    }
    public static class Company {
        private long id;
        private String name;
        private Address address;
        private java.util.List<Department> departments;
        private CompanyMetadata metadata;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public Address getAddress() {
            return this.address;
        }

        public void setAddress(Address address) {
            this.address = address;
        }
        public java.util.List<Department> getDepartments() {
            return this.departments;
        }

        public void setDepartments(java.util.List<Department> departments) {
            this.departments = departments;
        }
        public CompanyMetadata getMetadata() {
            return this.metadata;
        }

        public void setMetadata(CompanyMetadata metadata) {
            this.metadata = metadata;
        }
    }

    public static class PartialCompany {
        private long id;
        private String name;
        private java.util.Optional<Types.PartialAddress> address;
        private java.util.Optional<java.util.List<Department>> departments;
        private java.util.Optional<Types.PartialCompanyMetadata> metadata;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public java.util.Optional<Types.PartialAddress> getAddress() {
            return this.address;
        }

        public void setAddress(java.util.Optional<Types.PartialAddress> address) {
            this.address = address;
        }
        public java.util.Optional<java.util.List<Department>> getDepartments() {
            return this.departments;
        }

        public void setDepartments(java.util.Optional<java.util.List<Department>> departments) {
            this.departments = departments;
        }
        public java.util.Optional<Types.PartialCompanyMetadata> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Optional<Types.PartialCompanyMetadata> metadata) {
            this.metadata = metadata;
        }
    }
    public static class CompanyMetadata {
        private String founded;
        private String industry;
        private Union4StringOrStringOrStringOrString size;
        private java.util.List<String> certifications;
        private java.util.Optional<java.util.List<Company>> partnerships;

        public String getFounded() {
            return this.founded;
        }

        public void setFounded(String founded) {
            this.founded = founded;
        }
        public String getIndustry() {
            return this.industry;
        }

        public void setIndustry(String industry) {
            this.industry = industry;
        }
        public Union4StringOrStringOrStringOrString getSize() {
            return this.size;
        }

        public void setSize(Union4StringOrStringOrStringOrString size) {
            this.size = size;
        }
        public java.util.List<String> getCertifications() {
            return this.certifications;
        }

        public void setCertifications(java.util.List<String> certifications) {
            this.certifications = certifications;
        }
        public java.util.Optional<java.util.List<Company>> getPartnerships() {
            return this.partnerships;
        }

        public void setPartnerships(java.util.Optional<java.util.List<Company>> partnerships) {
            this.partnerships = partnerships;
        }
    }

    public static class PartialCompanyMetadata {
        private String founded;
        private String industry;
        private java.util.Optional<Unions.Union4StringOrStringOrStringOrString> size;
        private java.util.Optional<java.util.List<String>> certifications;
        private java.util.Optional<java.util.List<Company>> partnerships;

        public String getFounded() {
            return this.founded;
        }

        public void setFounded(String founded) {
            this.founded = founded;
        }
        public String getIndustry() {
            return this.industry;
        }

        public void setIndustry(String industry) {
            this.industry = industry;
        }
        public java.util.Optional<Unions.Union4StringOrStringOrStringOrString> getSize() {
            return this.size;
        }

        public void setSize(java.util.Optional<Unions.Union4StringOrStringOrStringOrString> size) {
            this.size = size;
        }
        public java.util.Optional<java.util.List<String>> getCertifications() {
            return this.certifications;
        }

        public void setCertifications(java.util.Optional<java.util.List<String>> certifications) {
            this.certifications = certifications;
        }
        public java.util.Optional<java.util.List<Company>> getPartnerships() {
            return this.partnerships;
        }

        public void setPartnerships(java.util.Optional<java.util.List<Company>> partnerships) {
            this.partnerships = partnerships;
        }
    }
    public static class ComplexNested {
        private Company company;
        private java.util.List<Employee> employees;
        private java.util.List<Project> projects;

        public Company getCompany() {
            return this.company;
        }

        public void setCompany(Company company) {
            this.company = company;
        }
        public java.util.List<Employee> getEmployees() {
            return this.employees;
        }

        public void setEmployees(java.util.List<Employee> employees) {
            this.employees = employees;
        }
        public java.util.List<Project> getProjects() {
            return this.projects;
        }

        public void setProjects(java.util.List<Project> projects) {
            this.projects = projects;
        }
    }

    public static class PartialComplexNested {
        private java.util.Optional<Types.PartialCompany> company;
        private java.util.Optional<java.util.List<Employee>> employees;
        private java.util.Optional<java.util.List<Project>> projects;

        public java.util.Optional<Types.PartialCompany> getCompany() {
            return this.company;
        }

        public void setCompany(java.util.Optional<Types.PartialCompany> company) {
            this.company = company;
        }
        public java.util.Optional<java.util.List<Employee>> getEmployees() {
            return this.employees;
        }

        public void setEmployees(java.util.Optional<java.util.List<Employee>> employees) {
            this.employees = employees;
        }
        public java.util.Optional<java.util.List<Project>> getProjects() {
            return this.projects;
        }

        public void setProjects(java.util.Optional<java.util.List<Project>> projects) {
            this.projects = projects;
        }
    }
    public static class Contact {
        private String name;
        private String relationship;
        private String phone;
        private java.util.Optional<String> email;

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getRelationship() {
            return this.relationship;
        }

        public void setRelationship(String relationship) {
            this.relationship = relationship;
        }
        public String getPhone() {
            return this.phone;
        }

        public void setPhone(String phone) {
            this.phone = phone;
        }
        public java.util.Optional<String> getEmail() {
            return this.email;
        }

        public void setEmail(java.util.Optional<String> email) {
            this.email = email;
        }
    }

    public static class PartialContact {
        private String name;
        private String relationship;
        private String phone;
        private java.util.Optional<String> email;

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getRelationship() {
            return this.relationship;
        }

        public void setRelationship(String relationship) {
            this.relationship = relationship;
        }
        public String getPhone() {
            return this.phone;
        }

        public void setPhone(String phone) {
            this.phone = phone;
        }
        public java.util.Optional<String> getEmail() {
            return this.email;
        }

        public void setEmail(java.util.Optional<String> email) {
            this.email = email;
        }
    }
    public static class Coordinates {
        private double latitude;
        private double longitude;

        public double getLatitude() {
            return this.latitude;
        }

        public void setLatitude(double latitude) {
            this.latitude = latitude;
        }
        public double getLongitude() {
            return this.longitude;
        }

        public void setLongitude(double longitude) {
            this.longitude = longitude;
        }
    }

    public static class PartialCoordinates {
        private double latitude;
        private double longitude;

        public double getLatitude() {
            return this.latitude;
        }

        public void setLatitude(double latitude) {
            this.latitude = latitude;
        }
        public double getLongitude() {
            return this.longitude;
        }

        public void setLongitude(double longitude) {
            this.longitude = longitude;
        }
    }
    public static class DeeplyNested {
        private Level1 level1;

        public Level1 getLevel1() {
            return this.level1;
        }

        public void setLevel1(Level1 level1) {
            this.level1 = level1;
        }
    }

    public static class PartialDeeplyNested {
        private java.util.Optional<Types.PartialLevel1> level1;

        public java.util.Optional<Types.PartialLevel1> getLevel1() {
            return this.level1;
        }

        public void setLevel1(java.util.Optional<Types.PartialLevel1> level1) {
            this.level1 = level1;
        }
    }
    public static class Department {
        private long id;
        private String name;
        private java.util.Optional<Employee> manager;
        private java.util.List<Employee> members;
        private double budget;
        private java.util.List<Project> projects;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public java.util.Optional<Employee> getManager() {
            return this.manager;
        }

        public void setManager(java.util.Optional<Employee> manager) {
            this.manager = manager;
        }
        public java.util.List<Employee> getMembers() {
            return this.members;
        }

        public void setMembers(java.util.List<Employee> members) {
            this.members = members;
        }
        public double getBudget() {
            return this.budget;
        }

        public void setBudget(double budget) {
            this.budget = budget;
        }
        public java.util.List<Project> getProjects() {
            return this.projects;
        }

        public void setProjects(java.util.List<Project> projects) {
            this.projects = projects;
        }
    }

    public static class PartialDepartment {
        private long id;
        private String name;
        private java.util.Optional<Employee> manager;
        private java.util.Optional<java.util.List<Employee>> members;
        private double budget;
        private java.util.Optional<java.util.List<Project>> projects;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public java.util.Optional<Employee> getManager() {
            return this.manager;
        }

        public void setManager(java.util.Optional<Employee> manager) {
            this.manager = manager;
        }
        public java.util.Optional<java.util.List<Employee>> getMembers() {
            return this.members;
        }

        public void setMembers(java.util.Optional<java.util.List<Employee>> members) {
            this.members = members;
        }
        public double getBudget() {
            return this.budget;
        }

        public void setBudget(double budget) {
            this.budget = budget;
        }
        public java.util.Optional<java.util.List<Project>> getProjects() {
            return this.projects;
        }

        public void setProjects(java.util.Optional<java.util.List<Project>> projects) {
            this.projects = projects;
        }
    }
    public static class DisplaySettings {
        private long fontSize;
        private String colorScheme;
        private Union2StringOrString layout;

        public long getFontSize() {
            return this.fontSize;
        }

        public void setFontSize(long fontSize) {
            this.fontSize = fontSize;
        }
        public String getColorScheme() {
            return this.colorScheme;
        }

        public void setColorScheme(String colorScheme) {
            this.colorScheme = colorScheme;
        }
        public Union2StringOrString getLayout() {
            return this.layout;
        }

        public void setLayout(Union2StringOrString layout) {
            this.layout = layout;
        }
    }

    public static class PartialDisplaySettings {
        private long fontSize;
        private String colorScheme;
        private java.util.Optional<Unions.Union2StringOrString> layout;

        public long getFontSize() {
            return this.fontSize;
        }

        public void setFontSize(long fontSize) {
            this.fontSize = fontSize;
        }
        public String getColorScheme() {
            return this.colorScheme;
        }

        public void setColorScheme(String colorScheme) {
            this.colorScheme = colorScheme;
        }
        public java.util.Optional<Unions.Union2StringOrString> getLayout() {
            return this.layout;
        }

        public void setLayout(java.util.Optional<Unions.Union2StringOrString> layout) {
            this.layout = layout;
        }
    }
    public static class Employee {
        private long id;
        private String name;
        private String email;
        private String role;
        private String department;
        private java.util.List<String> skills;
        private java.util.Optional<Address> address;
        private java.util.Optional<Contact> emergencyContact;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getEmail() {
            return this.email;
        }

        public void setEmail(String email) {
            this.email = email;
        }
        public String getRole() {
            return this.role;
        }

        public void setRole(String role) {
            this.role = role;
        }
        public String getDepartment() {
            return this.department;
        }

        public void setDepartment(String department) {
            this.department = department;
        }
        public java.util.List<String> getSkills() {
            return this.skills;
        }

        public void setSkills(java.util.List<String> skills) {
            this.skills = skills;
        }
        public java.util.Optional<Address> getAddress() {
            return this.address;
        }

        public void setAddress(java.util.Optional<Address> address) {
            this.address = address;
        }
        public java.util.Optional<Contact> getEmergencyContact() {
            return this.emergencyContact;
        }

        public void setEmergencyContact(java.util.Optional<Contact> emergencyContact) {
            this.emergencyContact = emergencyContact;
        }
    }

    public static class PartialEmployee {
        private long id;
        private String name;
        private String email;
        private String role;
        private String department;
        private java.util.Optional<java.util.List<String>> skills;
        private java.util.Optional<Address> address;
        private java.util.Optional<Contact> emergencyContact;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getEmail() {
            return this.email;
        }

        public void setEmail(String email) {
            this.email = email;
        }
        public String getRole() {
            return this.role;
        }

        public void setRole(String role) {
            this.role = role;
        }
        public String getDepartment() {
            return this.department;
        }

        public void setDepartment(String department) {
            this.department = department;
        }
        public java.util.Optional<java.util.List<String>> getSkills() {
            return this.skills;
        }

        public void setSkills(java.util.Optional<java.util.List<String>> skills) {
            this.skills = skills;
        }
        public java.util.Optional<Address> getAddress() {
            return this.address;
        }

        public void setAddress(java.util.Optional<Address> address) {
            this.address = address;
        }
        public java.util.Optional<Contact> getEmergencyContact() {
            return this.emergencyContact;
        }

        public void setEmergencyContact(java.util.Optional<Contact> emergencyContact) {
            this.emergencyContact = emergencyContact;
        }
    }
    public static class Level1 {
        private String data;
        private Level2 level2;

        public String getData() {
            return this.data;
        }

        public void setData(String data) {
            this.data = data;
        }
        public Level2 getLevel2() {
            return this.level2;
        }

        public void setLevel2(Level2 level2) {
            this.level2 = level2;
        }
    }

    public static class PartialLevel1 {
        private String data;
        private java.util.Optional<Types.PartialLevel2> level2;

        public String getData() {
            return this.data;
        }

        public void setData(String data) {
            this.data = data;
        }
        public java.util.Optional<Types.PartialLevel2> getLevel2() {
            return this.level2;
        }

        public void setLevel2(java.util.Optional<Types.PartialLevel2> level2) {
            this.level2 = level2;
        }
    }
    public static class Level2 {
        private String data;
        private Level3 level3;

        public String getData() {
            return this.data;
        }

        public void setData(String data) {
            this.data = data;
        }
        public Level3 getLevel3() {
            return this.level3;
        }

        public void setLevel3(Level3 level3) {
            this.level3 = level3;
        }
    }

    public static class PartialLevel2 {
        private String data;
        private java.util.Optional<Types.PartialLevel3> level3;

        public String getData() {
            return this.data;
        }

        public void setData(String data) {
            this.data = data;
        }
        public java.util.Optional<Types.PartialLevel3> getLevel3() {
            return this.level3;
        }

        public void setLevel3(java.util.Optional<Types.PartialLevel3> level3) {
            this.level3 = level3;
        }
    }
    public static class Level3 {
        private String data;
        private Level4 level4;

        public String getData() {
            return this.data;
        }

        public void setData(String data) {
            this.data = data;
        }
        public Level4 getLevel4() {
            return this.level4;
        }

        public void setLevel4(Level4 level4) {
            this.level4 = level4;
        }
    }

    public static class PartialLevel3 {
        private String data;
        private java.util.Optional<Types.PartialLevel4> level4;

        public String getData() {
            return this.data;
        }

        public void setData(String data) {
            this.data = data;
        }
        public java.util.Optional<Types.PartialLevel4> getLevel4() {
            return this.level4;
        }

        public void setLevel4(java.util.Optional<Types.PartialLevel4> level4) {
            this.level4 = level4;
        }
    }
    public static class Level4 {
        private String data;
        private Level5 level5;

        public String getData() {
            return this.data;
        }

        public void setData(String data) {
            this.data = data;
        }
        public Level5 getLevel5() {
            return this.level5;
        }

        public void setLevel5(Level5 level5) {
            this.level5 = level5;
        }
    }

    public static class PartialLevel4 {
        private String data;
        private java.util.Optional<Types.PartialLevel5> level5;

        public String getData() {
            return this.data;
        }

        public void setData(String data) {
            this.data = data;
        }
        public java.util.Optional<Types.PartialLevel5> getLevel5() {
            return this.level5;
        }

        public void setLevel5(java.util.Optional<Types.PartialLevel5> level5) {
            this.level5 = level5;
        }
    }
    public static class Level5 {
        private String data;
        private java.util.List<String> items;
        private java.util.Map<String, long> mapping;

        public String getData() {
            return this.data;
        }

        public void setData(String data) {
            this.data = data;
        }
        public java.util.List<String> getItems() {
            return this.items;
        }

        public void setItems(java.util.List<String> items) {
            this.items = items;
        }
        public java.util.Map<String, long> getMapping() {
            return this.mapping;
        }

        public void setMapping(java.util.Map<String, long> mapping) {
            this.mapping = mapping;
        }
    }

    public static class PartialLevel5 {
        private String data;
        private java.util.Optional<java.util.List<String>> items;
        private java.util.Optional<java.util.Map<String, long>> mapping;

        public String getData() {
            return this.data;
        }

        public void setData(String data) {
            this.data = data;
        }
        public java.util.Optional<java.util.List<String>> getItems() {
            return this.items;
        }

        public void setItems(java.util.Optional<java.util.List<String>> items) {
            this.items = items;
        }
        public java.util.Optional<java.util.Map<String, long>> getMapping() {
            return this.mapping;
        }

        public void setMapping(java.util.Optional<java.util.Map<String, long>> mapping) {
            this.mapping = mapping;
        }
    }
    public static class Metadata {
        private String createdAt;
        private String updatedAt;
        private long version;
        private java.util.List<String> tags;
        private java.util.Map<String, String> attributes;

        public String getCreatedAt() {
            return this.createdAt;
        }

        public void setCreatedAt(String createdAt) {
            this.createdAt = createdAt;
        }
        public String getUpdatedAt() {
            return this.updatedAt;
        }

        public void setUpdatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
        }
        public long getVersion() {
            return this.version;
        }

        public void setVersion(long version) {
            this.version = version;
        }
        public java.util.List<String> getTags() {
            return this.tags;
        }

        public void setTags(java.util.List<String> tags) {
            this.tags = tags;
        }
        public java.util.Map<String, String> getAttributes() {
            return this.attributes;
        }

        public void setAttributes(java.util.Map<String, String> attributes) {
            this.attributes = attributes;
        }
    }

    public static class PartialMetadata {
        private String createdAt;
        private String updatedAt;
        private long version;
        private java.util.Optional<java.util.List<String>> tags;
        private java.util.Optional<java.util.Map<String, String>> attributes;

        public String getCreatedAt() {
            return this.createdAt;
        }

        public void setCreatedAt(String createdAt) {
            this.createdAt = createdAt;
        }
        public String getUpdatedAt() {
            return this.updatedAt;
        }

        public void setUpdatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
        }
        public long getVersion() {
            return this.version;
        }

        public void setVersion(long version) {
            this.version = version;
        }
        public java.util.Optional<java.util.List<String>> getTags() {
            return this.tags;
        }

        public void setTags(java.util.Optional<java.util.List<String>> tags) {
            this.tags = tags;
        }
        public java.util.Optional<java.util.Map<String, String>> getAttributes() {
            return this.attributes;
        }

        public void setAttributes(java.util.Optional<java.util.Map<String, String>> attributes) {
            this.attributes = attributes;
        }
    }
    public static class Milestone {
        private long id;
        private String name;
        private String dueDate;
        private boolean completed;
        private java.util.List<Task> tasks;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getDueDate() {
            return this.dueDate;
        }

        public void setDueDate(String dueDate) {
            this.dueDate = dueDate;
        }
        public boolean getCompleted() {
            return this.completed;
        }

        public void setCompleted(boolean completed) {
            this.completed = completed;
        }
        public java.util.List<Task> getTasks() {
            return this.tasks;
        }

        public void setTasks(java.util.List<Task> tasks) {
            this.tasks = tasks;
        }
    }

    public static class PartialMilestone {
        private long id;
        private String name;
        private String dueDate;
        private boolean completed;
        private java.util.Optional<java.util.List<Task>> tasks;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getDueDate() {
            return this.dueDate;
        }

        public void setDueDate(String dueDate) {
            this.dueDate = dueDate;
        }
        public boolean getCompleted() {
            return this.completed;
        }

        public void setCompleted(boolean completed) {
            this.completed = completed;
        }
        public java.util.Optional<java.util.List<Task>> getTasks() {
            return this.tasks;
        }

        public void setTasks(java.util.Optional<java.util.List<Task>> tasks) {
            this.tasks = tasks;
        }
    }
    public static class NotificationSettings {
        private boolean email;
        private boolean push;
        private boolean sms;
        private Union3StringOrStringOrString frequency;

        public boolean getEmail() {
            return this.email;
        }

        public void setEmail(boolean email) {
            this.email = email;
        }
        public boolean getPush() {
            return this.push;
        }

        public void setPush(boolean push) {
            this.push = push;
        }
        public boolean getSms() {
            return this.sms;
        }

        public void setSms(boolean sms) {
            this.sms = sms;
        }
        public Union3StringOrStringOrString getFrequency() {
            return this.frequency;
        }

        public void setFrequency(Union3StringOrStringOrString frequency) {
            this.frequency = frequency;
        }
    }

    public static class PartialNotificationSettings {
        private boolean email;
        private boolean push;
        private boolean sms;
        private java.util.Optional<Unions.Union3StringOrStringOrString> frequency;

        public boolean getEmail() {
            return this.email;
        }

        public void setEmail(boolean email) {
            this.email = email;
        }
        public boolean getPush() {
            return this.push;
        }

        public void setPush(boolean push) {
            this.push = push;
        }
        public boolean getSms() {
            return this.sms;
        }

        public void setSms(boolean sms) {
            this.sms = sms;
        }
        public java.util.Optional<Unions.Union3StringOrStringOrString> getFrequency() {
            return this.frequency;
        }

        public void setFrequency(java.util.Optional<Unions.Union3StringOrStringOrString> frequency) {
            this.frequency = frequency;
        }
    }
    public static class Preferences {
        private Union2StringOrString theme;
        private String language;
        private NotificationSettings notifications;

        public Union2StringOrString getTheme() {
            return this.theme;
        }

        public void setTheme(Union2StringOrString theme) {
            this.theme = theme;
        }
        public String getLanguage() {
            return this.language;
        }

        public void setLanguage(String language) {
            this.language = language;
        }
        public NotificationSettings getNotifications() {
            return this.notifications;
        }

        public void setNotifications(NotificationSettings notifications) {
            this.notifications = notifications;
        }
    }

    public static class PartialPreferences {
        private java.util.Optional<Unions.Union2StringOrString> theme;
        private String language;
        private java.util.Optional<Types.PartialNotificationSettings> notifications;

        public java.util.Optional<Unions.Union2StringOrString> getTheme() {
            return this.theme;
        }

        public void setTheme(java.util.Optional<Unions.Union2StringOrString> theme) {
            this.theme = theme;
        }
        public String getLanguage() {
            return this.language;
        }

        public void setLanguage(String language) {
            this.language = language;
        }
        public java.util.Optional<Types.PartialNotificationSettings> getNotifications() {
            return this.notifications;
        }

        public void setNotifications(java.util.Optional<Types.PartialNotificationSettings> notifications) {
            this.notifications = notifications;
        }
    }
    public static class PrivacySettings {
        private Union3StringOrStringOrString profileVisibility;
        private boolean showEmail;
        private boolean showPhone;

        public Union3StringOrStringOrString getProfileVisibility() {
            return this.profileVisibility;
        }

        public void setProfileVisibility(Union3StringOrStringOrString profileVisibility) {
            this.profileVisibility = profileVisibility;
        }
        public boolean getShowEmail() {
            return this.showEmail;
        }

        public void setShowEmail(boolean showEmail) {
            this.showEmail = showEmail;
        }
        public boolean getShowPhone() {
            return this.showPhone;
        }

        public void setShowPhone(boolean showPhone) {
            this.showPhone = showPhone;
        }
    }

    public static class PartialPrivacySettings {
        private java.util.Optional<Unions.Union3StringOrStringOrString> profileVisibility;
        private boolean showEmail;
        private boolean showPhone;

        public java.util.Optional<Unions.Union3StringOrStringOrString> getProfileVisibility() {
            return this.profileVisibility;
        }

        public void setProfileVisibility(java.util.Optional<Unions.Union3StringOrStringOrString> profileVisibility) {
            this.profileVisibility = profileVisibility;
        }
        public boolean getShowEmail() {
            return this.showEmail;
        }

        public void setShowEmail(boolean showEmail) {
            this.showEmail = showEmail;
        }
        public boolean getShowPhone() {
            return this.showPhone;
        }

        public void setShowPhone(boolean showPhone) {
            this.showPhone = showPhone;
        }
    }
    public static class Profile {
        private String bio;
        private String avatar;
        private SocialLinks social;
        private Preferences preferences;

        public String getBio() {
            return this.bio;
        }

        public void setBio(String bio) {
            this.bio = bio;
        }
        public String getAvatar() {
            return this.avatar;
        }

        public void setAvatar(String avatar) {
            this.avatar = avatar;
        }
        public SocialLinks getSocial() {
            return this.social;
        }

        public void setSocial(SocialLinks social) {
            this.social = social;
        }
        public Preferences getPreferences() {
            return this.preferences;
        }

        public void setPreferences(Preferences preferences) {
            this.preferences = preferences;
        }
    }

    public static class PartialProfile {
        private String bio;
        private String avatar;
        private java.util.Optional<Types.PartialSocialLinks> social;
        private java.util.Optional<Types.PartialPreferences> preferences;

        public String getBio() {
            return this.bio;
        }

        public void setBio(String bio) {
            this.bio = bio;
        }
        public String getAvatar() {
            return this.avatar;
        }

        public void setAvatar(String avatar) {
            this.avatar = avatar;
        }
        public java.util.Optional<Types.PartialSocialLinks> getSocial() {
            return this.social;
        }

        public void setSocial(java.util.Optional<Types.PartialSocialLinks> social) {
            this.social = social;
        }
        public java.util.Optional<Types.PartialPreferences> getPreferences() {
            return this.preferences;
        }

        public void setPreferences(java.util.Optional<Types.PartialPreferences> preferences) {
            this.preferences = preferences;
        }
    }
    public static class Project {
        private long id;
        private String name;
        private String description;
        private Union4StringOrStringOrStringOrString status;
        private java.util.List<Employee> team;
        private java.util.List<Milestone> milestones;
        private Budget budget;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getDescription() {
            return this.description;
        }

        public void setDescription(String description) {
            this.description = description;
        }
        public Union4StringOrStringOrStringOrString getStatus() {
            return this.status;
        }

        public void setStatus(Union4StringOrStringOrStringOrString status) {
            this.status = status;
        }
        public java.util.List<Employee> getTeam() {
            return this.team;
        }

        public void setTeam(java.util.List<Employee> team) {
            this.team = team;
        }
        public java.util.List<Milestone> getMilestones() {
            return this.milestones;
        }

        public void setMilestones(java.util.List<Milestone> milestones) {
            this.milestones = milestones;
        }
        public Budget getBudget() {
            return this.budget;
        }

        public void setBudget(Budget budget) {
            this.budget = budget;
        }
    }

    public static class PartialProject {
        private long id;
        private String name;
        private String description;
        private java.util.Optional<Unions.Union4StringOrStringOrStringOrString> status;
        private java.util.Optional<java.util.List<Employee>> team;
        private java.util.Optional<java.util.List<Milestone>> milestones;
        private java.util.Optional<Types.PartialBudget> budget;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getDescription() {
            return this.description;
        }

        public void setDescription(String description) {
            this.description = description;
        }
        public java.util.Optional<Unions.Union4StringOrStringOrStringOrString> getStatus() {
            return this.status;
        }

        public void setStatus(java.util.Optional<Unions.Union4StringOrStringOrStringOrString> status) {
            this.status = status;
        }
        public java.util.Optional<java.util.List<Employee>> getTeam() {
            return this.team;
        }

        public void setTeam(java.util.Optional<java.util.List<Employee>> team) {
            this.team = team;
        }
        public java.util.Optional<java.util.List<Milestone>> getMilestones() {
            return this.milestones;
        }

        public void setMilestones(java.util.Optional<java.util.List<Milestone>> milestones) {
            this.milestones = milestones;
        }
        public java.util.Optional<Types.PartialBudget> getBudget() {
            return this.budget;
        }

        public void setBudget(java.util.Optional<Types.PartialBudget> budget) {
            this.budget = budget;
        }
    }
    public static class RecursiveStructure {
        private long id;
        private String name;
        private java.util.List<RecursiveStructure> children;
        private java.util.Optional<RecursiveStructure> parent;
        private java.util.Map<String, Union3BoolOrIntOrString> metadata;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public java.util.List<RecursiveStructure> getChildren() {
            return this.children;
        }

        public void setChildren(java.util.List<RecursiveStructure> children) {
            this.children = children;
        }
        public java.util.Optional<RecursiveStructure> getParent() {
            return this.parent;
        }

        public void setParent(java.util.Optional<RecursiveStructure> parent) {
            this.parent = parent;
        }
        public java.util.Map<String, Union3BoolOrIntOrString> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Map<String, Union3BoolOrIntOrString> metadata) {
            this.metadata = metadata;
        }
    }

    public static class PartialRecursiveStructure {
        private long id;
        private String name;
        private java.util.Optional<java.util.List<RecursiveStructure>> children;
        private java.util.Optional<RecursiveStructure> parent;
        private java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> metadata;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public java.util.Optional<java.util.List<RecursiveStructure>> getChildren() {
            return this.children;
        }

        public void setChildren(java.util.Optional<java.util.List<RecursiveStructure>> children) {
            this.children = children;
        }
        public java.util.Optional<RecursiveStructure> getParent() {
            return this.parent;
        }

        public void setParent(java.util.Optional<RecursiveStructure> parent) {
            this.parent = parent;
        }
        public java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> metadata) {
            this.metadata = metadata;
        }
    }
    public static class SimpleNested {
        private User user;
        private Address address;
        private Metadata metadata;

        public User getUser() {
            return this.user;
        }

        public void setUser(User user) {
            this.user = user;
        }
        public Address getAddress() {
            return this.address;
        }

        public void setAddress(Address address) {
            this.address = address;
        }
        public Metadata getMetadata() {
            return this.metadata;
        }

        public void setMetadata(Metadata metadata) {
            this.metadata = metadata;
        }
    }

    public static class PartialSimpleNested {
        private java.util.Optional<Types.PartialUser> user;
        private java.util.Optional<Types.PartialAddress> address;
        private java.util.Optional<Types.PartialMetadata> metadata;

        public java.util.Optional<Types.PartialUser> getUser() {
            return this.user;
        }

        public void setUser(java.util.Optional<Types.PartialUser> user) {
            this.user = user;
        }
        public java.util.Optional<Types.PartialAddress> getAddress() {
            return this.address;
        }

        public void setAddress(java.util.Optional<Types.PartialAddress> address) {
            this.address = address;
        }
        public java.util.Optional<Types.PartialMetadata> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Optional<Types.PartialMetadata> metadata) {
            this.metadata = metadata;
        }
    }
    public static class SocialLinks {
        private java.util.Optional<String> twitter;
        private java.util.Optional<String> github;
        private java.util.Optional<String> linkedin;
        private java.util.Optional<String> website;

        public java.util.Optional<String> getTwitter() {
            return this.twitter;
        }

        public void setTwitter(java.util.Optional<String> twitter) {
            this.twitter = twitter;
        }
        public java.util.Optional<String> getGithub() {
            return this.github;
        }

        public void setGithub(java.util.Optional<String> github) {
            this.github = github;
        }
        public java.util.Optional<String> getLinkedin() {
            return this.linkedin;
        }

        public void setLinkedin(java.util.Optional<String> linkedin) {
            this.linkedin = linkedin;
        }
        public java.util.Optional<String> getWebsite() {
            return this.website;
        }

        public void setWebsite(java.util.Optional<String> website) {
            this.website = website;
        }
    }

    public static class PartialSocialLinks {
        private java.util.Optional<String> twitter;
        private java.util.Optional<String> github;
        private java.util.Optional<String> linkedin;
        private java.util.Optional<String> website;

        public java.util.Optional<String> getTwitter() {
            return this.twitter;
        }

        public void setTwitter(java.util.Optional<String> twitter) {
            this.twitter = twitter;
        }
        public java.util.Optional<String> getGithub() {
            return this.github;
        }

        public void setGithub(java.util.Optional<String> github) {
            this.github = github;
        }
        public java.util.Optional<String> getLinkedin() {
            return this.linkedin;
        }

        public void setLinkedin(java.util.Optional<String> linkedin) {
            this.linkedin = linkedin;
        }
        public java.util.Optional<String> getWebsite() {
            return this.website;
        }

        public void setWebsite(java.util.Optional<String> website) {
            this.website = website;
        }
    }
    public static class Task {
        private long id;
        private String title;
        private String description;
        private String assignee;
        private Union3StringOrStringOrString priority;
        private Union3StringOrStringOrString status;
        private java.util.Optional<java.util.List<Task>> subtasks;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getTitle() {
            return this.title;
        }

        public void setTitle(String title) {
            this.title = title;
        }
        public String getDescription() {
            return this.description;
        }

        public void setDescription(String description) {
            this.description = description;
        }
        public String getAssignee() {
            return this.assignee;
        }

        public void setAssignee(String assignee) {
            this.assignee = assignee;
        }
        public Union3StringOrStringOrString getPriority() {
            return this.priority;
        }

        public void setPriority(Union3StringOrStringOrString priority) {
            this.priority = priority;
        }
        public Union3StringOrStringOrString getStatus() {
            return this.status;
        }

        public void setStatus(Union3StringOrStringOrString status) {
            this.status = status;
        }
        public java.util.Optional<java.util.List<Task>> getSubtasks() {
            return this.subtasks;
        }

        public void setSubtasks(java.util.Optional<java.util.List<Task>> subtasks) {
            this.subtasks = subtasks;
        }
    }

    public static class PartialTask {
        private long id;
        private String title;
        private String description;
        private String assignee;
        private java.util.Optional<Unions.Union3StringOrStringOrString> priority;
        private java.util.Optional<Unions.Union3StringOrStringOrString> status;
        private java.util.Optional<java.util.List<Task>> subtasks;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getTitle() {
            return this.title;
        }

        public void setTitle(String title) {
            this.title = title;
        }
        public String getDescription() {
            return this.description;
        }

        public void setDescription(String description) {
            this.description = description;
        }
        public String getAssignee() {
            return this.assignee;
        }

        public void setAssignee(String assignee) {
            this.assignee = assignee;
        }
        public java.util.Optional<Unions.Union3StringOrStringOrString> getPriority() {
            return this.priority;
        }

        public void setPriority(java.util.Optional<Unions.Union3StringOrStringOrString> priority) {
            this.priority = priority;
        }
        public java.util.Optional<Unions.Union3StringOrStringOrString> getStatus() {
            return this.status;
        }

        public void setStatus(java.util.Optional<Unions.Union3StringOrStringOrString> status) {
            this.status = status;
        }
        public java.util.Optional<java.util.List<Task>> getSubtasks() {
            return this.subtasks;
        }

        public void setSubtasks(java.util.Optional<java.util.List<Task>> subtasks) {
            this.subtasks = subtasks;
        }
    }
    public static class User {
        private long id;
        private String name;
        private Profile profile;
        private UserSettings settings;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public Profile getProfile() {
            return this.profile;
        }

        public void setProfile(Profile profile) {
            this.profile = profile;
        }
        public UserSettings getSettings() {
            return this.settings;
        }

        public void setSettings(UserSettings settings) {
            this.settings = settings;
        }
    }

    public static class PartialUser {
        private long id;
        private String name;
        private java.util.Optional<Types.PartialProfile> profile;
        private java.util.Optional<Types.PartialUserSettings> settings;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public java.util.Optional<Types.PartialProfile> getProfile() {
            return this.profile;
        }

        public void setProfile(java.util.Optional<Types.PartialProfile> profile) {
            this.profile = profile;
        }
        public java.util.Optional<Types.PartialUserSettings> getSettings() {
            return this.settings;
        }

        public void setSettings(java.util.Optional<Types.PartialUserSettings> settings) {
            this.settings = settings;
        }
    }
    public static class UserSettings {
        private PrivacySettings privacy;
        private DisplaySettings display;
        private java.util.Map<String, String> advanced;

        public PrivacySettings getPrivacy() {
            return this.privacy;
        }

        public void setPrivacy(PrivacySettings privacy) {
            this.privacy = privacy;
        }
        public DisplaySettings getDisplay() {
            return this.display;
        }

        public void setDisplay(DisplaySettings display) {
            this.display = display;
        }
        public java.util.Map<String, String> getAdvanced() {
            return this.advanced;
        }

        public void setAdvanced(java.util.Map<String, String> advanced) {
            this.advanced = advanced;
        }
    }

    public static class PartialUserSettings {
        private java.util.Optional<Types.PartialPrivacySettings> privacy;
        private java.util.Optional<Types.PartialDisplaySettings> display;
        private java.util.Optional<java.util.Map<String, String>> advanced;

        public java.util.Optional<Types.PartialPrivacySettings> getPrivacy() {
            return this.privacy;
        }

        public void setPrivacy(java.util.Optional<Types.PartialPrivacySettings> privacy) {
            this.privacy = privacy;
        }
        public java.util.Optional<Types.PartialDisplaySettings> getDisplay() {
            return this.display;
        }

        public void setDisplay(java.util.Optional<Types.PartialDisplaySettings> display) {
            this.display = display;
        }
        public java.util.Optional<java.util.Map<String, String>> getAdvanced() {
            return this.advanced;
        }

        public void setAdvanced(java.util.Optional<java.util.Map<String, String>> advanced) {
            this.advanced = advanced;
        }
    }
}
