// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML union types.
 */
public class Unions {

    public static final class Union2StringOrString {

        private final String value0;

        private final String value1;


        private Union2StringOrString(String value0, String value1) {

            this.value0 = value0;

            this.value1 = value1;

        }


        public static Union2StringOrString ofVariant0(String value) {
            return new Union2StringOrString(value, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union2StringOrString ofVariant1(String value) {
            return new Union2StringOrString(null, value);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public String getVariant1() {
            return this.value1;
        }

    }

    public static final class Union3BoolOrIntOrString {

        private final String value0;

        private final Long value1;

        private final Boolean value2;


        private Union3BoolOrIntOrString(String value0, Long value1, Boolean value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3BoolOrIntOrString ofVariant0(String value) {
            return new Union3BoolOrIntOrString(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union3BoolOrIntOrString ofVariant1(Long value) {
            return new Union3BoolOrIntOrString(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union3BoolOrIntOrString ofVariant2(Boolean value) {
            return new Union3BoolOrIntOrString(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Boolean getVariant2() {
            return this.value2;
        }

    }

    public static final class Union3StringOrStringOrString {

        private final String value0;

        private final String value1;

        private final String value2;


        private Union3StringOrStringOrString(String value0, String value1, String value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3StringOrStringOrString ofVariant0(String value) {
            return new Union3StringOrStringOrString(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union3StringOrStringOrString ofVariant1(String value) {
            return new Union3StringOrStringOrString(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public String getVariant1() {
            return this.value1;
        }

        public static Union3StringOrStringOrString ofVariant2(String value) {
            return new Union3StringOrStringOrString(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public String getVariant2() {
            return this.value2;
        }

    }

    public static final class Union4StringOrStringOrStringOrString {

        private final String value0;

        private final String value1;

        private final String value2;

        private final String value3;


        private Union4StringOrStringOrStringOrString(String value0, String value1, String value2, String value3) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

        }


        public static Union4StringOrStringOrStringOrString ofVariant0(String value) {
            return new Union4StringOrStringOrStringOrString(value, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union4StringOrStringOrStringOrString ofVariant1(String value) {
            return new Union4StringOrStringOrStringOrString(null, value, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public String getVariant1() {
            return this.value1;
        }

        public static Union4StringOrStringOrStringOrString ofVariant2(String value) {
            return new Union4StringOrStringOrStringOrString(null, null, value, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public String getVariant2() {
            return this.value2;
        }

        public static Union4StringOrStringOrStringOrString ofVariant3(String value) {
            return new Union4StringOrStringOrStringOrString(null, null, null, value);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public String getVariant3() {
            return this.value3;
        }

    }

}
