// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * BAML source file map. Do not edit.
 */
public final class BamlSourceMap {
    public static String getSourceMap() {
        return "{\"baml_src/main.baml\":\"class Person {\\r\\n    name string @assert(valid_name, {{ this|length >= 2 }})\\r\\n    age int @assert(valid_age, {{ this >= 0 }})\\r\\n\\r\\n    @@assert(not_minor, {{\\r\\n        this.age >= 18\\r\\n    }})\\r\\n}\\r\\n\\r\\nfunction PersonTest() -> Person {\\r\\n    client \\\"openai/gpt-4o\\\"\\r\\n    prompt #\\\"\\r\\n        Fake random information about an adult person.\\r\\n\\r\\n        {{ ctx.output_format }}\\r\\n    \\\"#\\r\\n}\\r\\n\\r\\ntest PersonTest {\\r\\n    functions [PersonTest]\\r\\n    args {\\r\\n        output_format: \\\"json\\\"\\r\\n    }\\r\\n}\\r\\n\"}";
    }
}
