// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;
    
    import com.boundaryml.baml.BamlRuntime;
    import com.boundaryml.baml.BamlEncoder;
    import com.boundaryml.baml.BamlDecoder;
    import com.boundaryml.baml.BamlStream;
    import java.util.LinkedHashMap;
    import java.util.Map;
    import java.util.function.Function;
    
    /**
     * Generated BAML function wrappers. Use Globals.getRuntime() and call these methods.
     * Requires baml-runtime-java for BamlRuntime, encode/decode helpers.
     */
    public final class Functions {
        private final BamlRuntime runtime;
    
        public Functions(BamlRuntime runtime) {
            this.runtime = runtime;
        }
    
    
        public Types.Person PersonTest() {
            Map<String, Object> kwargs = new LinkedHashMap<>();
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("PersonTest", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.Person typed = (Types.Person) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialPerson, Types.Person> PersonTestStream() {
            Map<String, Object> kwargs = new LinkedHashMap<>();
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialPerson> partialDecoder = bytes -> (Types.PartialPerson) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.Person> finalDecoder = bytes -> (Types.Person) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("PersonTest", encoded, partialDecoder, finalDecoder);
        }
    
    
    }
    