// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML class types.
 */
public class Types {
    public static class Person {
        private String name;
        private long age;

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public long getAge() {
            return this.age;
        }

        public void setAge(long age) {
            this.age = age;
        }
    }

    public static class PartialPerson {
        private String name;
        private long age;

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public long getAge() {
            return this.age;
        }

        public void setAge(long age) {
            this.age = age;
        }
    }
}
