// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;
    
    import com.boundaryml.baml.BamlRuntime;
    import com.boundaryml.baml.BamlEncoder;
    import com.boundaryml.baml.BamlDecoder;
    import com.boundaryml.baml.BamlStream;
    import java.util.LinkedHashMap;
    import java.util.Map;
    import java.util.function.Function;
    
    /**
     * Generated BAML function wrappers. Use Globals.getRuntime() and call these methods.
     * Requires baml-runtime-java for BamlRuntime, encode/decode helpers.
     */
    public final class Functions {
        private final BamlRuntime runtime;
    
        public Functions(BamlRuntime runtime) {
            this.runtime = runtime;
        }
    
    
        public Types.CircularReference TestCircularReference(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestCircularReference", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.CircularReference typed = (Types.CircularReference) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialCircularReference, Types.CircularReference> TestCircularReferenceStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialCircularReference> partialDecoder = bytes -> (Types.PartialCircularReference) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.CircularReference> finalDecoder = bytes -> (Types.CircularReference) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestCircularReference", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.DeepRecursion TestDeepRecursion(long depth) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("depth", depth);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestDeepRecursion", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.DeepRecursion typed = (Types.DeepRecursion) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialDeepRecursion, Types.DeepRecursion> TestDeepRecursionStream(long depth) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("depth", depth);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialDeepRecursion> partialDecoder = bytes -> (Types.PartialDeepRecursion) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.DeepRecursion> finalDecoder = bytes -> (Types.DeepRecursion) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestDeepRecursion", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.EmptyCollections TestEmptyCollections(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestEmptyCollections", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.EmptyCollections typed = (Types.EmptyCollections) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialEmptyCollections, Types.EmptyCollections> TestEmptyCollectionsStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialEmptyCollections> partialDecoder = bytes -> (Types.PartialEmptyCollections) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.EmptyCollections> finalDecoder = bytes -> (Types.EmptyCollections) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestEmptyCollections", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.LargeStructure TestLargeStructure(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestLargeStructure", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.LargeStructure typed = (Types.LargeStructure) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialLargeStructure, Types.LargeStructure> TestLargeStructureStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialLargeStructure> partialDecoder = bytes -> (Types.PartialLargeStructure) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.LargeStructure> finalDecoder = bytes -> (Types.LargeStructure) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestLargeStructure", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.NumberEdgeCases TestNumberEdgeCases(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestNumberEdgeCases", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.NumberEdgeCases typed = (Types.NumberEdgeCases) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialNumberEdgeCases, Types.NumberEdgeCases> TestNumberEdgeCasesStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialNumberEdgeCases> partialDecoder = bytes -> (Types.PartialNumberEdgeCases) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.NumberEdgeCases> finalDecoder = bytes -> (Types.NumberEdgeCases) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestNumberEdgeCases", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.SpecialCharacters TestSpecialCharacters(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestSpecialCharacters", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.SpecialCharacters typed = (Types.SpecialCharacters) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialSpecialCharacters, Types.SpecialCharacters> TestSpecialCharactersStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialSpecialCharacters> partialDecoder = bytes -> (Types.PartialSpecialCharacters) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.SpecialCharacters> finalDecoder = bytes -> (Types.SpecialCharacters) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestSpecialCharacters", encoded, partialDecoder, finalDecoder);
        }
    
    
    }
    