// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

import com.boundaryml.baml.BamlRuntime;

/**
 * Globals and runtime. Requires baml-runtime-java on classpath.
 */
public final class Globals {
    private static BamlRuntime runtime;

    public static synchronized BamlRuntime getRuntime() {
        if (runtime == null) {
            String rootPath = "./baml_src";
            String srcFiles = BamlSourceMap.getSourceMap();
            String envVars = "{}";
            runtime = BamlRuntime.create(rootPath, srcFiles, envVars);
        }
        return runtime;
    }
}
