// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML union types.
 */
public class Unions {

    public static final class Union3BoolOrIntOrStringOptional {

        private final String value0;

        private final Long value1;

        private final Boolean value2;


        private Union3BoolOrIntOrStringOptional(String value0, Long value1, Boolean value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3BoolOrIntOrStringOptional ofVariant0(String value) {
            return new Union3BoolOrIntOrStringOptional(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union3BoolOrIntOrStringOptional ofVariant1(Long value) {
            return new Union3BoolOrIntOrStringOptional(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union3BoolOrIntOrStringOptional ofVariant2(Boolean value) {
            return new Union3BoolOrIntOrStringOptional(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Boolean getVariant2() {
            return this.value2;
        }

    }

}
