use askama::Template;

use crate::r#type::{SerializeType, TypeSwift};

pub struct FunctionSwift {
    pub(crate) documentation: Option<String>,
    pub(crate) name: String,
    pub(crate) args: Vec<(String, TypeSwift)>,
    pub(crate) return_type: TypeSwift,
    pub(crate) stream_return_type: TypeSwift,
}

#[derive(askama::Template)]
#[template(path = "function.swift.j2", escape = "none")]
struct FunctionTemplate<'a> {
    r#fn: &'a FunctionSwift,
}

#[derive(askama::Template)]
#[template(path = "function.stream.swift.j2", escape = "none")]
struct FunctionStreamTemplate<'a> {
    r#fn: &'a FunctionSwift,
}

fn render_function(function: &FunctionSwift) -> Result<String, askama::Error> {
    FunctionTemplate { r#fn: function }.render()
}

fn render_function_stream(function: &FunctionSwift) -> Result<String, askama::Error> {
    FunctionStreamTemplate { r#fn: function }.render()
}

/// The main functions file
///
/// ```askama
/// // Generated by BAML - do not edit
///
/// import Foundation
/// import BamlSwift
///
/// /// Returns the process environment with TEST_RUNNER_* variables normalized.
/// /// xcodebuild passes env vars with a TEST_RUNNER_ prefix when using build
/// /// settings; this strips it so BAML clients find OPENROUTER_API_KEY etc.
/// func processEnv() -> [String: String] {
///     var env = ProcessInfo.processInfo.environment
///     for (key, value) in env where key.hasPrefix("TEST_RUNNER_") {
///         let stripped = String(key.dropFirst("TEST_RUNNER_".count))
///         if env[stripped] == nil { env[stripped] = value }
///     }
///     return env
/// }
///
/// {% for function in functions %}
/// {{ crate::functions::render_function(function)? }}
/// {% endfor %}
/// ```
#[derive(askama::Template)]
#[template(in_doc = true, ext = "txt", escape = "none")]
struct FunctionsTemplate<'a> {
    functions: &'a [FunctionSwift],
}

pub fn render_functions(functions: &[FunctionSwift]) -> Result<String, askama::Error> {
    FunctionsTemplate { functions }.render()
}

/// The streaming functions file
///
/// ```askama
/// // Generated by BAML - do not edit
///
/// import Foundation
/// import BamlSwift
///
/// {% for function in functions %}
/// {{ crate::functions::render_function_stream(function)? }}
/// {% endfor %}
/// ```
#[derive(askama::Template)]
#[template(in_doc = true, ext = "txt", escape = "none")]
struct FunctionsStreamTemplate<'a> {
    functions: &'a [FunctionSwift],
}

pub fn render_functions_stream(
    functions: &[FunctionSwift],
) -> Result<String, askama::Error> {
    FunctionsStreamTemplate { functions }.render()
}

/// Source file map
///
/// ```askama
/// // Generated by BAML - do not edit
///
/// import Foundation
///
/// let bamlFileMap: [String: String] = [
/// {% for (path, contents) in file_map %}
///     {{ path }}: {{ contents }},
/// {%- endfor %}
/// ]
///
/// func getBamlFiles() -> [String: String] {
///     return bamlFileMap
/// }
/// ```
#[derive(askama::Template)]
#[template(in_doc = true, escape = "none", ext = "txt")]
struct SourceFiles<'a> {
    file_map: &'a [(String, String)],
}

pub fn render_source_files(file_map: Vec<(String, String)>) -> Result<String, askama::Error> {
    SourceFiles {
        file_map: &file_map,
    }
    .render()
}

/// Runtime initialization code
///
/// ```askama
/// // Generated by BAML - do not edit
///
/// import Foundation
/// import BamlSwift
///
/// /// Shared BAML runtime instance for all generated functions.
/// /// Initialized lazily on first access using the generated file map.
/// public let bamlClient: BamlRuntime = {
///     let files = getBamlFiles()
///     do {
///         return try BamlRuntime(
///             rootPath: ".",
///             srcFiles: files,
///             envVars: [:]
///         )
///     } catch {
///         fatalError("Failed to initialize BAML runtime: \(error)")
///     }
/// }()
/// ```
#[derive(askama::Template)]
#[template(in_doc = true, escape = "none", ext = "txt")]
struct RuntimeCode {}

pub fn render_runtime_code() -> Result<String, askama::Error> {
    RuntimeCode {}.render()
}
