use baml_types::{ir_type::TypeGeneric, LiteralValue, TypeIR, TypeValue};
use dir_writer::{FileCollector, GeneratorArgs, IntermediateRepr, LanguageFeatures};
use internal_baml_core::ir::repr::Function;

#[derive(Default)]
pub struct SwiftLanguageFeatures;

/// Convert a BAML TypeIR to a Swift type string.
///
/// Very basic: primitives get proper Swift types, everything else is `Any?`.
fn type_ir_to_swift(t: &TypeIR) -> String {
    match t {
        TypeGeneric::Primitive(TypeValue::String, _) => "String".to_string(),
        TypeGeneric::Primitive(TypeValue::Int, _) => "Int".to_string(),
        TypeGeneric::Primitive(TypeValue::Float, _) => "Double".to_string(),
        TypeGeneric::Primitive(TypeValue::Bool, _) => "Bool".to_string(),
        TypeGeneric::Primitive(TypeValue::Null, _) => "Any?".to_string(),
        TypeGeneric::Primitive(TypeValue::Media(_), _) => "Any".to_string(),
        TypeGeneric::Literal(lit, _) => match lit {
            LiteralValue::String(_) => "String".to_string(),
            LiteralValue::Int(_) => "Int".to_string(),
            LiteralValue::Bool(_) => "Bool".to_string(),
        },
        TypeGeneric::Enum { .. } => "String".to_string(),
        TypeGeneric::Class { .. } => "[String: Any?]".to_string(),
        TypeGeneric::List(inner, _) => format!("[{}]", type_ir_to_swift(inner)),
        TypeGeneric::Map(_, val, _) => format!("[String: {}]", type_ir_to_swift(val)),
        TypeGeneric::Union(union_types, _) => {
            use baml_types::ir_type::UnionTypeViewGeneric;
            match union_types.view() {
                UnionTypeViewGeneric::Null => "Any?".to_string(),
                UnionTypeViewGeneric::Optional(inner) => {
                    let inner_str = type_ir_to_swift(inner);
                    // avoid double-optional (Any?? looks weird)
                    if inner_str.ends_with('?') {
                        inner_str
                    } else {
                        format!("{}?", inner_str)
                    }
                }
                // Real union (multiple non-null types) — fall back to Any
                UnionTypeViewGeneric::OneOf(_) | UnionTypeViewGeneric::OneOfOptional(_) => {
                    "Any".to_string()
                }
            }
        }
        // Recursive type aliases, tuples, arrows — not supported in the basic generator
        _ => "Any".to_string(),
    }
}

/// Generate the Swift source for a single BAML function.
fn render_function(function: &Function) -> String {
    let fn_name = &function.name;
    let inputs = &function.inputs;

    // Build Swift parameter list: "name: SwiftType, ..."
    let args_str = inputs
        .iter()
        .map(|(name, t)| format!("{}: {}", name, type_ir_to_swift(t)))
        .collect::<Vec<_>>()
        .join(", ");

    // Return type: always Any? for the basic generator.
    // Callers can cast using `as? ConcreteType`.
    let ret_type = "Any?";

    let mut s = String::new();
    s.push_str(&format!(
        "    public func {fn_name}({args_str}) async throws -> {ret_type} {{\n"
    ));

    // Build the kwargs dictionary literal
    s.push_str("        let args = try encodeArgs(kwargs: [\n");
    for (name, _) in inputs.iter() {
        s.push_str(&format!("            \"{name}\": {name},\n"));
    }
    s.push_str("        ])\n");

    s.push_str(&format!(
        "        let holder = try await runtime.callFunction(name: \"{fn_name}\", args: args)\n"
    ));
    s.push_str("        return decode(holder)\n");
    s.push_str("    }\n");

    s
}

impl LanguageFeatures for SwiftLanguageFeatures {
    const CONTENT_PREFIX: &'static str = r#"
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, add BamlSwift to your
//  Swift Package dependencies and call loadBamlLibrary(path:) before use.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
"#;

    fn name() -> &'static str {
        "swift"
    }

    fn generate_sdk_files(
        &self,
        collector: &mut FileCollector<Self>,
        ir: std::sync::Arc<IntermediateRepr>,
        _args: &GeneratorArgs,
    ) -> Result<(), anyhow::Error> {
        let mut content = String::new();

        content.push_str("import BamlSwift\n\n");
        content.push_str("public class BamlClient {\n");
        content.push_str("    private let runtime: BamlRuntime\n\n");
        content.push_str("    public init(runtime: BamlRuntime) {\n");
        content.push_str("        self.runtime = runtime\n");
        content.push_str("    }\n");

        for function in ir.functions.iter() {
            content.push('\n');
            content.push_str(&render_function(&function.elem));
        }

        content.push_str("}\n");

        collector.add_file("BamlClient.swift", content)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_name() {
        use std::str::FromStr;

        use dir_writer::LanguageFeatures;

        let gen_type =
            baml_types::GeneratorOutputType::from_str(crate::SwiftLanguageFeatures::name())
                .expect("SwiftLanguageFeatures name should be a valid GeneratorOutputType");
        assert_eq!(gen_type, baml_types::GeneratorOutputType::Swift);
    }
}
