use baml_types::{ir_type::TypeGeneric, ToUnionName};
use dir_writer::{FileCollector, GeneratorArgs, IntermediateRepr, LanguageFeatures};
use internal_baml_core::ir::TypeValue;

mod functions;
mod generated_types;
mod ir_to_swift;
mod r#type;
mod utils;

#[cfg(test)]
mod test_macros;

#[derive(Default)]
pub struct SwiftLanguageFeatures;

impl LanguageFeatures for SwiftLanguageFeatures {
    const CONTENT_PREFIX: &'static str = r#"
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, add the BamlSwift package:
//
//  https://github.com/boundaryml/baml-swift
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
        "#;

    fn name() -> &'static str {
        "swift"
    }

    fn generate_sdk_files(
        &self,
        collector: &mut FileCollector<Self>,
        ir: std::sync::Arc<IntermediateRepr>,
        args: &GeneratorArgs,
    ) -> Result<(), anyhow::Error> {
        let lookup = ir.as_ref();

        // Source map file
        let file_map = args.file_map_as_json_string()?;
        collector.add_file(
            "BamlSourceMap.swift",
            functions::render_source_files(file_map)?,
        )?;

        // Runtime initialization
        collector.add_file("BamlRuntime.swift", functions::render_runtime_code()?)?;

        // Functions
        let functions = ir
            .functions
            .iter()
            .map(|f| ir_to_swift::functions::ir_function_to_swift(f, lookup))
            .collect::<Vec<_>>();

        collector.add_file(
            "BamlFunctions.swift",
            functions::render_functions(&functions)?,
        )?;

        collector.add_file(
            "BamlFunctionsStream.swift",
            functions::render_functions_stream(&functions)?,
        )?;

        // Classes
        let classes = ir
            .walk_classes()
            .map(|c| ir_to_swift::classes::ir_class_to_swift(c.item, lookup))
            .collect::<Vec<_>>();

        collector.add_file(
            "BamlTypes.swift",
            generated_types::render_swift_types(&classes)?,
        )?;

        // Enums
        let enums = ir
            .walk_enums()
            .map(|e| ir_to_swift::enums::ir_enum_to_swift(e.item))
            .collect::<Vec<_>>();

        collector.add_file(
            "BamlEnums.swift",
            generated_types::render_swift_types(&enums)?,
        )?;

        // Unions
        let unions = {
            let mut unions = ir
                .walk_all_non_streaming_unions()
                .flat_map(|t| ir_to_swift::unions::ir_union_to_swift(&t, lookup))
                .collect::<Vec<_>>();
            unions.sort_by_key(|u| u.name.clone());
            unions.dedup_by_key(|u| u.name.clone());
            unions
        };

        collector.add_file(
            "BamlUnions.swift",
            generated_types::render_swift_types(&unions)?,
        )?;

        // Type aliases
        let type_aliases = ir.walk_type_aliases().collect::<Vec<_>>();

        let invalid_cycles = ir
            .structural_recursive_alias_cycles()
            .iter()
            .filter(|&cycle| {
                cycle.iter().all(|(_, field_type)| {
                    field_type
                        .find_if(
                            &|t| match t {
                                TypeGeneric::Class { .. } => true,
                                TypeGeneric::Enum { .. } => true,
                                TypeGeneric::Literal(..) => true,
                                TypeGeneric::Primitive(TypeValue::Null, ..) => false,
                                TypeGeneric::Primitive(..) => true,
                                _ => false,
                            },
                            true,
                        )
                        .is_empty()
                })
            })
            .flat_map(|cycle| {
                let keys = cycle.keys().cloned().collect::<Vec<_>>();
                let first_key = keys[0].clone();
                keys.into_iter().map(move |k| (k, first_key.clone()))
            })
            .collect::<baml_types::BamlMap<_, _>>();

        let mut swift_type_aliases = type_aliases
            .iter()
            .map(|c| {
                ir_to_swift::type_aliases::ir_type_alias_to_swift(
                    c.item,
                    lookup,
                    invalid_cycles.get(&c.elem().name),
                )
            })
            .collect::<Vec<_>>();
        swift_type_aliases.sort_by(|a, b| a.name.cmp(&b.name));

        // Generate type alias file
        if !swift_type_aliases.is_empty() {
            let mut alias_content =
                String::from("// Generated by BAML - do not edit\n\nimport Foundation\n\n");
            for alias in &swift_type_aliases {
                if let Some(ref doc) = alias.docstring {
                    alias_content.push_str(&utils::prefix_lines(doc, "/// "));
                    alias_content.push('\n');
                }
                alias_content.push_str(&format!(
                    "public typealias {} = {}\n\n",
                    alias.name,
                    alias.swift_type()
                ));
            }
            collector.add_file("BamlTypeAliases.swift", alias_content)?;
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_name() {
        use std::str::FromStr;

        use dir_writer::LanguageFeatures;

        let gen_type =
            baml_types::GeneratorOutputType::from_str(crate::SwiftLanguageFeatures::name())
                .expect("SwiftLanguageFeatures name should be a valid GeneratorOutputType");
        assert_eq!(gen_type, baml_types::GeneratorOutputType::Swift);
    }
}
