// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * BAML source file map. Do not edit.
 */
public final class BamlSourceMap {
    public static String getSourceMap() {
        return "{\"baml_src/main.baml\":\"enum TestEnum {\\r\\n  Angry @alias(\\\"k1\\\") @description(#\\\"\\r\\n    User is angry\\r\\n  \\\"#)\\r\\n  Happy @alias(\\\"k2\\\") @description(#\\\"\\r\\n    User is happy\\r\\n  \\\"#)\\r\\n  // tests whether k1 doesnt incorrectly get matched with k11\\r\\n  Sad @alias(\\\"k3\\\") @description(#\\\"\\r\\n    User is sad\\r\\n  \\\"#)\\r\\n  Confused @description(\\r\\n    User is confused\\r\\n  )\\r\\n  Excited @alias(\\\"k5\\\") @description(\\r\\n    User is excited\\r\\n  )\\r\\n  Exclamation @alias(\\\"k6\\\") // only alias\\r\\n  \\r\\n  Bored @alias(\\\"k7\\\") @description(#\\\"\\r\\n    User is bored\\r\\n    With a long description\\r\\n  \\\"#)\\r\\n   \\r\\n  @@alias(\\\"Category\\\")\\r\\n}\\r\\n\\r\\nfunction FnTestAliasedEnumOutput(input: string) -> TestEnum {\\r\\n  client \\\"openai/gpt-4o-mini\\\"\\r\\n  prompt #\\\"\\r\\n    Classify the user input into the following category\\r\\n      \\r\\n    {{ ctx.output_format }}\\r\\n\\r\\n    {{ _.role('user') }}\\r\\n    {{input}}\\r\\n\\r\\n    {{ _.role('assistant') }}\\r\\n    Category ID:\\r\\n  \\\"#\\r\\n}\\r\\n\\r\\nfunction ConsumeTestEnum(input: TestEnum) -> TestEnum {\\r\\n  client \\\"openai/gpt-4o-mini\\\"\\r\\n  prompt #\\\"\\r\\n    Return back to me verbatim:\\r\\n    \\r\\n    {{ input }}\\r\\n  \\\"#\\r\\n}\\r\\n\\r\\ntest FnTestAliasedEnumOutput {\\r\\n  functions [FnTestAliasedEnumOutput]\\r\\n  args {\\r\\n    input \\\"mehhhhh\\\"\\r\\n  }\\r\\n}\"}";
    }
}
