// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML enum types.
 */
public class Enums {

    public enum TestEnum {
        
        Angry,
        
        Happy,
        
        Sad,
        
        Confused,
        
        Excited,
        
        Exclamation,
        
        Bored
        
    }

}
