// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;
    
    import com.boundaryml.baml.BamlRuntime;
    import com.boundaryml.baml.BamlEncoder;
    import com.boundaryml.baml.BamlDecoder;
    import com.boundaryml.baml.BamlStream;
    import java.util.LinkedHashMap;
    import java.util.Map;
    import java.util.function.Function;
    
    /**
     * Generated BAML function wrappers. Use Globals.getRuntime() and call these methods.
     * Requires baml-runtime-java for BamlRuntime, encode/decode helpers.
     */
    public final class Functions {
        private final BamlRuntime runtime;
    
        public Functions(BamlRuntime runtime) {
            this.runtime = runtime;
        }
    
    
        public Enums.TestEnum ConsumeTestEnum(Enums.TestEnum input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("ConsumeTestEnum", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Enums.TestEnum typed = (Enums.TestEnum) decoded;
            return typed;
        }
    
        public BamlStream<Enums.TestEnum, Enums.TestEnum> ConsumeTestEnumStream(Enums.TestEnum input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Enums.TestEnum> partialDecoder = bytes -> (Enums.TestEnum) BamlDecoder.decodeResult(bytes);
            Function<byte[], Enums.TestEnum> finalDecoder = bytes -> (Enums.TestEnum) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("ConsumeTestEnum", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Enums.TestEnum FnTestAliasedEnumOutput(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("FnTestAliasedEnumOutput", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Enums.TestEnum typed = (Enums.TestEnum) decoded;
            return typed;
        }
    
        public BamlStream<Enums.TestEnum, Enums.TestEnum> FnTestAliasedEnumOutputStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Enums.TestEnum> partialDecoder = bytes -> (Enums.TestEnum) BamlDecoder.decodeResult(bytes);
            Function<byte[], Enums.TestEnum> finalDecoder = bytes -> (Enums.TestEnum) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("FnTestAliasedEnumOutput", encoded, partialDecoder, finalDecoder);
        }
    
    
    }
    