// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "BamlSwift",
    platforms: [.macOS(.v13)],
    products: [
        .library(name: "BamlSwift", targets: ["BamlSwift"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.25.0"),
    ],
    targets: [
        // Thin C wrapper — mirrors Go's baml_cffi_wrapper.c.
        // Stores dlsym'd function pointers and provides typed wrappers.
        // Using C types here lets Swift import BamlBuffer as a C struct,
        // which is required for @convention(c) function types.
        .target(
            name: "BamlCFFI",
            path: "Sources/BamlCFFI"
        ),
        .target(
            name: "BamlSwift",
            dependencies: [
                "BamlCFFI",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ]
        ),
        // Generated by: baml-cli generate --from baml_src
        // Re-run after editing baml_src/main.baml
        .target(
            name: "BamlClient",
            dependencies: ["BamlSwift"],
            path: "Sources/BamlClient/baml_client"
        ),
        .testTarget(
            name: "BamlSwiftTests",
            dependencies: ["BamlSwift", "BamlClient"]
        ),
    ]
)
