// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, add BamlSwift to your
//  Swift Package dependencies and call loadBamlLibrary(path:) before use.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import BamlSwift

public class BamlClient {
    private let runtime: BamlRuntime

    public init(runtime: BamlRuntime) {
        self.runtime = runtime
    }

    public func Classify(text: String) async throws -> Any? {
        let args = try encodeArgs(kwargs: [
            "text": text,
        ])
        let holder = try await runtime.callFunction(name: "Classify", args: args)
        return decode(holder)
    }

    public func SayHello(name: String) async throws -> Any? {
        let args = try encodeArgs(kwargs: [
            "name": name,
        ])
        let holder = try await runtime.callFunction(name: "SayHello", args: args)
        return decode(holder)
    }
}
