// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;
    
    import com.boundaryml.baml.BamlRuntime;
    import com.boundaryml.baml.BamlEncoder;
    import com.boundaryml.baml.BamlDecoder;
    import com.boundaryml.baml.BamlStream;
    import java.util.LinkedHashMap;
    import java.util.Map;
    import java.util.function.Function;
    
    /**
     * Generated BAML function wrappers. Use Globals.getRuntime() and call these methods.
     * Requires baml-runtime-java for BamlRuntime, encode/decode helpers.
     */
    public final class Functions {
        private final BamlRuntime runtime;
    
        public Functions(BamlRuntime runtime) {
            this.runtime = runtime;
        }
    
    
        public Types.KitchenSink TestKitchenSink(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestKitchenSink", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.KitchenSink typed = (Types.KitchenSink) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialKitchenSink, Types.KitchenSink> TestKitchenSinkStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialKitchenSink> partialDecoder = bytes -> (Types.PartialKitchenSink) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.KitchenSink> finalDecoder = bytes -> (Types.KitchenSink) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestKitchenSink", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.Node TestRecursiveComplexity(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestRecursiveComplexity", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.Node typed = (Types.Node) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialNode, Types.Node> TestRecursiveComplexityStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialNode> partialDecoder = bytes -> (Types.PartialNode) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.Node> finalDecoder = bytes -> (Types.Node) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestRecursiveComplexity", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.UltraComplex TestUltraComplex(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestUltraComplex", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.UltraComplex typed = (Types.UltraComplex) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialUltraComplex, Types.UltraComplex> TestUltraComplexStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialUltraComplex> partialDecoder = bytes -> (Types.PartialUltraComplex) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.UltraComplex> finalDecoder = bytes -> (Types.UltraComplex) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestUltraComplex", encoded, partialDecoder, finalDecoder);
        }
    
    
    }
    