// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML class types.
 */
public class Types {
    public static class Action {
        private String type;
        private java.util.Map<String, Union3BoolOrIntOrString> parameters;
        private boolean async_;

        public String getType() {
            return this.type;
        }

        public void setType(String type) {
            this.type = type;
        }
        public java.util.Map<String, Union3BoolOrIntOrString> getParameters() {
            return this.parameters;
        }

        public void setParameters(java.util.Map<String, Union3BoolOrIntOrString> parameters) {
            this.parameters = parameters;
        }
        public boolean getAsync_() {
            return this.async_;
        }

        public void setAsync_(boolean async_) {
            this.async_ = async_;
        }
    }

    public static class PartialAction {
        private String type;
        private java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> parameters;
        private boolean async_;

        public String getType() {
            return this.type;
        }

        public void setType(String type) {
            this.type = type;
        }
        public java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> getParameters() {
            return this.parameters;
        }

        public void setParameters(java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> parameters) {
            this.parameters = parameters;
        }
        public boolean getAsync_() {
            return this.async_;
        }

        public void setAsync_(boolean async_) {
            this.async_ = async_;
        }
    }
    public static class Asset {
        private long id;
        private Union3StringOrStringOrString type;
        private AssetMetadata metadata;
        private java.util.List<String> tags;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public Union3StringOrStringOrString getType() {
            return this.type;
        }

        public void setType(Union3StringOrStringOrString type) {
            this.type = type;
        }
        public AssetMetadata getMetadata() {
            return this.metadata;
        }

        public void setMetadata(AssetMetadata metadata) {
            this.metadata = metadata;
        }
        public java.util.List<String> getTags() {
            return this.tags;
        }

        public void setTags(java.util.List<String> tags) {
            this.tags = tags;
        }
    }

    public static class PartialAsset {
        private long id;
        private java.util.Optional<Unions.Union3StringOrStringOrString> type;
        private java.util.Optional<Types.PartialAssetMetadata> metadata;
        private java.util.Optional<java.util.List<String>> tags;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public java.util.Optional<Unions.Union3StringOrStringOrString> getType() {
            return this.type;
        }

        public void setType(java.util.Optional<Unions.Union3StringOrStringOrString> type) {
            this.type = type;
        }
        public java.util.Optional<Types.PartialAssetMetadata> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Optional<Types.PartialAssetMetadata> metadata) {
            this.metadata = metadata;
        }
        public java.util.Optional<java.util.List<String>> getTags() {
            return this.tags;
        }

        public void setTags(java.util.Optional<java.util.List<String>> tags) {
            this.tags = tags;
        }
    }
    public static class AssetMetadata {
        private String filename;
        private long size;
        private String mimeType;
        private String uploaded;
        private String checksum;

        public String getFilename() {
            return this.filename;
        }

        public void setFilename(String filename) {
            this.filename = filename;
        }
        public long getSize() {
            return this.size;
        }

        public void setSize(long size) {
            this.size = size;
        }
        public String getMimeType() {
            return this.mimeType;
        }

        public void setMimeType(String mimeType) {
            this.mimeType = mimeType;
        }
        public String getUploaded() {
            return this.uploaded;
        }

        public void setUploaded(String uploaded) {
            this.uploaded = uploaded;
        }
        public String getChecksum() {
            return this.checksum;
        }

        public void setChecksum(String checksum) {
            this.checksum = checksum;
        }
    }

    public static class PartialAssetMetadata {
        private String filename;
        private long size;
        private String mimeType;
        private String uploaded;
        private String checksum;

        public String getFilename() {
            return this.filename;
        }

        public void setFilename(String filename) {
            this.filename = filename;
        }
        public long getSize() {
            return this.size;
        }

        public void setSize(long size) {
            this.size = size;
        }
        public String getMimeType() {
            return this.mimeType;
        }

        public void setMimeType(String mimeType) {
            this.mimeType = mimeType;
        }
        public String getUploaded() {
            return this.uploaded;
        }

        public void setUploaded(String uploaded) {
            this.uploaded = uploaded;
        }
        public String getChecksum() {
            return this.checksum;
        }

        public void setChecksum(String checksum) {
            this.checksum = checksum;
        }
    }
    public static class ButtonWidget {
        private String label;
        private String action;
        private java.util.Map<String, String> style;

        public String getLabel() {
            return this.label;
        }

        public void setLabel(String label) {
            this.label = label;
        }
        public String getAction() {
            return this.action;
        }

        public void setAction(String action) {
            this.action = action;
        }
        public java.util.Map<String, String> getStyle() {
            return this.style;
        }

        public void setStyle(java.util.Map<String, String> style) {
            this.style = style;
        }
    }

    public static class PartialButtonWidget {
        private String label;
        private String action;
        private java.util.Optional<java.util.Map<String, String>> style;

        public String getLabel() {
            return this.label;
        }

        public void setLabel(String label) {
            this.label = label;
        }
        public String getAction() {
            return this.action;
        }

        public void setAction(String action) {
            this.action = action;
        }
        public java.util.Optional<java.util.Map<String, String>> getStyle() {
            return this.style;
        }

        public void setStyle(java.util.Optional<java.util.Map<String, String>> style) {
            this.style = style;
        }
    }
    public static class ComplexData {
        private PrimaryData primary;
        private java.util.Optional<SecondaryData> secondary;
        private java.util.Optional<TertiaryData> tertiary;

        public PrimaryData getPrimary() {
            return this.primary;
        }

        public void setPrimary(PrimaryData primary) {
            this.primary = primary;
        }
        public java.util.Optional<SecondaryData> getSecondary() {
            return this.secondary;
        }

        public void setSecondary(java.util.Optional<SecondaryData> secondary) {
            this.secondary = secondary;
        }
        public java.util.Optional<TertiaryData> getTertiary() {
            return this.tertiary;
        }

        public void setTertiary(java.util.Optional<TertiaryData> tertiary) {
            this.tertiary = tertiary;
        }
    }

    public static class PartialComplexData {
        private java.util.Optional<Types.PartialPrimaryData> primary;
        private java.util.Optional<SecondaryData> secondary;
        private java.util.Optional<TertiaryData> tertiary;

        public java.util.Optional<Types.PartialPrimaryData> getPrimary() {
            return this.primary;
        }

        public void setPrimary(java.util.Optional<Types.PartialPrimaryData> primary) {
            this.primary = primary;
        }
        public java.util.Optional<SecondaryData> getSecondary() {
            return this.secondary;
        }

        public void setSecondary(java.util.Optional<SecondaryData> secondary) {
            this.secondary = secondary;
        }
        public java.util.Optional<TertiaryData> getTertiary() {
            return this.tertiary;
        }

        public void setTertiary(java.util.Optional<TertiaryData> tertiary) {
            this.tertiary = tertiary;
        }
    }
    public static class Condition {
        private Union3StringOrStringOrString type;
        private java.util.List<Union2ConditionOrSimpleCondition> conditions;

        public Union3StringOrStringOrString getType() {
            return this.type;
        }

        public void setType(Union3StringOrStringOrString type) {
            this.type = type;
        }
        public java.util.List<Union2ConditionOrSimpleCondition> getConditions() {
            return this.conditions;
        }

        public void setConditions(java.util.List<Union2ConditionOrSimpleCondition> conditions) {
            this.conditions = conditions;
        }
    }

    public static class PartialCondition {
        private java.util.Optional<Unions.Union3StringOrStringOrString> type;
        private java.util.Optional<java.util.List<Union2ConditionOrSimpleCondition>> conditions;

        public java.util.Optional<Unions.Union3StringOrStringOrString> getType() {
            return this.type;
        }

        public void setType(java.util.Optional<Unions.Union3StringOrStringOrString> type) {
            this.type = type;
        }
        public java.util.Optional<java.util.List<Union2ConditionOrSimpleCondition>> getConditions() {
            return this.conditions;
        }

        public void setConditions(java.util.Optional<java.util.List<Union2ConditionOrSimpleCondition>> conditions) {
            this.conditions = conditions;
        }
    }
    public static class Configuration {
        private String version;
        private java.util.List<Feature> features;
        private java.util.Map<String, Environment> environments;
        private java.util.List<Rule> rules;

        public String getVersion() {
            return this.version;
        }

        public void setVersion(String version) {
            this.version = version;
        }
        public java.util.List<Feature> getFeatures() {
            return this.features;
        }

        public void setFeatures(java.util.List<Feature> features) {
            this.features = features;
        }
        public java.util.Map<String, Environment> getEnvironments() {
            return this.environments;
        }

        public void setEnvironments(java.util.Map<String, Environment> environments) {
            this.environments = environments;
        }
        public java.util.List<Rule> getRules() {
            return this.rules;
        }

        public void setRules(java.util.List<Rule> rules) {
            this.rules = rules;
        }
    }

    public static class PartialConfiguration {
        private String version;
        private java.util.Optional<java.util.List<Feature>> features;
        private java.util.Optional<java.util.Map<String, Environment>> environments;
        private java.util.Optional<java.util.List<Rule>> rules;

        public String getVersion() {
            return this.version;
        }

        public void setVersion(String version) {
            this.version = version;
        }
        public java.util.Optional<java.util.List<Feature>> getFeatures() {
            return this.features;
        }

        public void setFeatures(java.util.Optional<java.util.List<Feature>> features) {
            this.features = features;
        }
        public java.util.Optional<java.util.Map<String, Environment>> getEnvironments() {
            return this.environments;
        }

        public void setEnvironments(java.util.Optional<java.util.Map<String, Environment>> environments) {
            this.environments = environments;
        }
        public java.util.Optional<java.util.List<Rule>> getRules() {
            return this.rules;
        }

        public void setRules(java.util.Optional<java.util.List<Rule>> rules) {
            this.rules = rules;
        }
    }
    public static class ContainerWidget {
        private Union3StringOrStringOrString layout;
        private java.util.List<Widget> children;
        private java.util.Map<String, String> style;

        public Union3StringOrStringOrString getLayout() {
            return this.layout;
        }

        public void setLayout(Union3StringOrStringOrString layout) {
            this.layout = layout;
        }
        public java.util.List<Widget> getChildren() {
            return this.children;
        }

        public void setChildren(java.util.List<Widget> children) {
            this.children = children;
        }
        public java.util.Map<String, String> getStyle() {
            return this.style;
        }

        public void setStyle(java.util.Map<String, String> style) {
            this.style = style;
        }
    }

    public static class PartialContainerWidget {
        private java.util.Optional<Unions.Union3StringOrStringOrString> layout;
        private java.util.Optional<java.util.List<Widget>> children;
        private java.util.Optional<java.util.Map<String, String>> style;

        public java.util.Optional<Unions.Union3StringOrStringOrString> getLayout() {
            return this.layout;
        }

        public void setLayout(java.util.Optional<Unions.Union3StringOrStringOrString> layout) {
            this.layout = layout;
        }
        public java.util.Optional<java.util.List<Widget>> getChildren() {
            return this.children;
        }

        public void setChildren(java.util.Optional<java.util.List<Widget>> children) {
            this.children = children;
        }
        public java.util.Optional<java.util.Map<String, String>> getStyle() {
            return this.style;
        }

        public void setStyle(java.util.Optional<java.util.Map<String, String>> style) {
            this.style = style;
        }
    }
    public static class DataObject {
        private String type;
        private java.util.Map<String, String> value;

        public String getType() {
            return this.type;
        }

        public void setType(String type) {
            this.type = type;
        }
        public java.util.Map<String, String> getValue() {
            return this.value;
        }

        public void setValue(java.util.Map<String, String> value) {
            this.value = value;
        }
    }

    public static class PartialDataObject {
        private String type;
        private java.util.Optional<java.util.Map<String, String>> value;

        public String getType() {
            return this.type;
        }

        public void setType(String type) {
            this.type = type;
        }
        public java.util.Optional<java.util.Map<String, String>> getValue() {
            return this.value;
        }

        public void setValue(java.util.Optional<java.util.Map<String, String>> value) {
            this.value = value;
        }
    }
    public static class Dimensions {
        private long width;
        private long height;

        public long getWidth() {
            return this.width;
        }

        public void setWidth(long width) {
            this.width = width;
        }
        public long getHeight() {
            return this.height;
        }

        public void setHeight(long height) {
            this.height = height;
        }
    }

    public static class PartialDimensions {
        private long width;
        private long height;

        public long getWidth() {
            return this.width;
        }

        public void setWidth(long width) {
            this.width = width;
        }
        public long getHeight() {
            return this.height;
        }

        public void setHeight(long height) {
            this.height = height;
        }
    }
    public static class Environment {
        private String name;
        private String url;
        private java.util.Map<String, String> variables;
        private java.util.Optional<java.util.Map<String, String>> secrets;

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getUrl() {
            return this.url;
        }

        public void setUrl(String url) {
            this.url = url;
        }
        public java.util.Map<String, String> getVariables() {
            return this.variables;
        }

        public void setVariables(java.util.Map<String, String> variables) {
            this.variables = variables;
        }
        public java.util.Optional<java.util.Map<String, String>> getSecrets() {
            return this.secrets;
        }

        public void setSecrets(java.util.Optional<java.util.Map<String, String>> secrets) {
            this.secrets = secrets;
        }
    }

    public static class PartialEnvironment {
        private String name;
        private String url;
        private java.util.Optional<java.util.Map<String, String>> variables;
        private java.util.Optional<java.util.Map<String, String>> secrets;

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getUrl() {
            return this.url;
        }

        public void setUrl(String url) {
            this.url = url;
        }
        public java.util.Optional<java.util.Map<String, String>> getVariables() {
            return this.variables;
        }

        public void setVariables(java.util.Optional<java.util.Map<String, String>> variables) {
            this.variables = variables;
        }
        public java.util.Optional<java.util.Map<String, String>> getSecrets() {
            return this.secrets;
        }

        public void setSecrets(java.util.Optional<java.util.Map<String, String>> secrets) {
            this.secrets = secrets;
        }
    }
    public static class Error {
        private String type;
        private String message;
        private long code;

        public String getType() {
            return this.type;
        }

        public void setType(String type) {
            this.type = type;
        }
        public String getMessage() {
            return this.message;
        }

        public void setMessage(String message) {
            this.message = message;
        }
        public long getCode() {
            return this.code;
        }

        public void setCode(long code) {
            this.code = code;
        }
    }

    public static class PartialError {
        private String type;
        private String message;
        private long code;

        public String getType() {
            return this.type;
        }

        public void setType(String type) {
            this.type = type;
        }
        public String getMessage() {
            return this.message;
        }

        public void setMessage(String message) {
            this.message = message;
        }
        public long getCode() {
            return this.code;
        }

        public void setCode(long code) {
            this.code = code;
        }
    }
    public static class ErrorDetail {
        private String code;
        private String message;
        private java.util.Optional<java.util.Map<String, String>> details;

        public String getCode() {
            return this.code;
        }

        public void setCode(String code) {
            this.code = code;
        }
        public String getMessage() {
            return this.message;
        }

        public void setMessage(String message) {
            this.message = message;
        }
        public java.util.Optional<java.util.Map<String, String>> getDetails() {
            return this.details;
        }

        public void setDetails(java.util.Optional<java.util.Map<String, String>> details) {
            this.details = details;
        }
    }

    public static class PartialErrorDetail {
        private String code;
        private String message;
        private java.util.Optional<java.util.Map<String, String>> details;

        public String getCode() {
            return this.code;
        }

        public void setCode(String code) {
            this.code = code;
        }
        public String getMessage() {
            return this.message;
        }

        public void setMessage(String message) {
            this.message = message;
        }
        public java.util.Optional<java.util.Map<String, String>> getDetails() {
            return this.details;
        }

        public void setDetails(java.util.Optional<java.util.Map<String, String>> details) {
            this.details = details;
        }
    }
    public static class Feature {
        private String name;
        private boolean enabled;
        private java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> config;
        private java.util.List<String> dependencies;

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public boolean getEnabled() {
            return this.enabled;
        }

        public void setEnabled(boolean enabled) {
            this.enabled = enabled;
        }
        public java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> getConfig() {
            return this.config;
        }

        public void setConfig(java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> config) {
            this.config = config;
        }
        public java.util.List<String> getDependencies() {
            return this.dependencies;
        }

        public void setDependencies(java.util.List<String> dependencies) {
            this.dependencies = dependencies;
        }
    }

    public static class PartialFeature {
        private String name;
        private boolean enabled;
        private java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> config;
        private java.util.Optional<java.util.List<String>> dependencies;

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public boolean getEnabled() {
            return this.enabled;
        }

        public void setEnabled(boolean enabled) {
            this.enabled = enabled;
        }
        public java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> getConfig() {
            return this.config;
        }

        public void setConfig(java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> config) {
            this.config = config;
        }
        public java.util.Optional<java.util.List<String>> getDependencies() {
            return this.dependencies;
        }

        public void setDependencies(java.util.Optional<java.util.List<String>> dependencies) {
            this.dependencies = dependencies;
        }
    }
    public static class ImageWidget {
        private String alt;
        private Dimensions dimensions;

        public String getAlt() {
            return this.alt;
        }

        public void setAlt(String alt) {
            this.alt = alt;
        }
        public Dimensions getDimensions() {
            return this.dimensions;
        }

        public void setDimensions(Dimensions dimensions) {
            this.dimensions = dimensions;
        }
    }

    public static class PartialImageWidget {
        private String alt;
        private java.util.Optional<Types.PartialDimensions> dimensions;

        public String getAlt() {
            return this.alt;
        }

        public void setAlt(String alt) {
            this.alt = alt;
        }
        public java.util.Optional<Types.PartialDimensions> getDimensions() {
            return this.dimensions;
        }

        public void setDimensions(java.util.Optional<Types.PartialDimensions> dimensions) {
            this.dimensions = dimensions;
        }
    }
    public static class Item {
        private long id;
        private String name;
        private java.util.List<Variant> variants;
        private java.util.Map<String, Union4BoolOrFloatOrIntOrString> attributes;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public java.util.List<Variant> getVariants() {
            return this.variants;
        }

        public void setVariants(java.util.List<Variant> variants) {
            this.variants = variants;
        }
        public java.util.Map<String, Union4BoolOrFloatOrIntOrString> getAttributes() {
            return this.attributes;
        }

        public void setAttributes(java.util.Map<String, Union4BoolOrFloatOrIntOrString> attributes) {
            this.attributes = attributes;
        }
    }

    public static class PartialItem {
        private long id;
        private String name;
        private java.util.Optional<java.util.List<Variant>> variants;
        private java.util.Optional<java.util.Map<String, Union4BoolOrFloatOrIntOrString>> attributes;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public java.util.Optional<java.util.List<Variant>> getVariants() {
            return this.variants;
        }

        public void setVariants(java.util.Optional<java.util.List<Variant>> variants) {
            this.variants = variants;
        }
        public java.util.Optional<java.util.Map<String, Union4BoolOrFloatOrIntOrString>> getAttributes() {
            return this.attributes;
        }

        public void setAttributes(java.util.Optional<java.util.Map<String, Union4BoolOrFloatOrIntOrString>> attributes) {
            this.attributes = attributes;
        }
    }
    public static class KitchenSink {
        private long id;
        private String name;
        private double score;
        private boolean active;
        private Void nothing;
        private Union3StringOrStringOrString status;
        private Union5IntOrIntOrIntOrIntOrInt priority;
        private java.util.List<String> tags;
        private java.util.List<long> numbers;
        private java.util.List<java.util.List<long>> matrix;
        private java.util.Map<String, String> metadata;
        private java.util.Map<String, double> scores;
        private java.util.Optional<String> description;
        private java.util.Optional<String> notes;
        private Union3DataObjectOrIntOrString data;
        private Union2ErrorOrSuccess result;
        private User user;
        private java.util.List<Item> items;
        private Configuration config;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public double getScore() {
            return this.score;
        }

        public void setScore(double score) {
            this.score = score;
        }
        public boolean getActive() {
            return this.active;
        }

        public void setActive(boolean active) {
            this.active = active;
        }
        public Void getNothing() {
            return this.nothing;
        }

        public void setNothing(Void nothing) {
            this.nothing = nothing;
        }
        public Union3StringOrStringOrString getStatus() {
            return this.status;
        }

        public void setStatus(Union3StringOrStringOrString status) {
            this.status = status;
        }
        public Union5IntOrIntOrIntOrIntOrInt getPriority() {
            return this.priority;
        }

        public void setPriority(Union5IntOrIntOrIntOrIntOrInt priority) {
            this.priority = priority;
        }
        public java.util.List<String> getTags() {
            return this.tags;
        }

        public void setTags(java.util.List<String> tags) {
            this.tags = tags;
        }
        public java.util.List<long> getNumbers() {
            return this.numbers;
        }

        public void setNumbers(java.util.List<long> numbers) {
            this.numbers = numbers;
        }
        public java.util.List<java.util.List<long>> getMatrix() {
            return this.matrix;
        }

        public void setMatrix(java.util.List<java.util.List<long>> matrix) {
            this.matrix = matrix;
        }
        public java.util.Map<String, String> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Map<String, String> metadata) {
            this.metadata = metadata;
        }
        public java.util.Map<String, double> getScores() {
            return this.scores;
        }

        public void setScores(java.util.Map<String, double> scores) {
            this.scores = scores;
        }
        public java.util.Optional<String> getDescription() {
            return this.description;
        }

        public void setDescription(java.util.Optional<String> description) {
            this.description = description;
        }
        public java.util.Optional<String> getNotes() {
            return this.notes;
        }

        public void setNotes(java.util.Optional<String> notes) {
            this.notes = notes;
        }
        public Union3DataObjectOrIntOrString getData() {
            return this.data;
        }

        public void setData(Union3DataObjectOrIntOrString data) {
            this.data = data;
        }
        public Union2ErrorOrSuccess getResult() {
            return this.result;
        }

        public void setResult(Union2ErrorOrSuccess result) {
            this.result = result;
        }
        public User getUser() {
            return this.user;
        }

        public void setUser(User user) {
            this.user = user;
        }
        public java.util.List<Item> getItems() {
            return this.items;
        }

        public void setItems(java.util.List<Item> items) {
            this.items = items;
        }
        public Configuration getConfig() {
            return this.config;
        }

        public void setConfig(Configuration config) {
            this.config = config;
        }
    }

    public static class PartialKitchenSink {
        private long id;
        private String name;
        private double score;
        private boolean active;
        private Void nothing;
        private java.util.Optional<Unions.Union3StringOrStringOrString> status;
        private java.util.Optional<Unions.Union5IntOrIntOrIntOrIntOrInt> priority;
        private java.util.Optional<java.util.List<String>> tags;
        private java.util.Optional<java.util.List<long>> numbers;
        private java.util.Optional<java.util.List<java.util.List<long>>> matrix;
        private java.util.Optional<java.util.Map<String, String>> metadata;
        private java.util.Optional<java.util.Map<String, double>> scores;
        private java.util.Optional<String> description;
        private java.util.Optional<String> notes;
        private java.util.Optional<Unions.Union3DataObjectOrIntOrString> data;
        private java.util.Optional<Unions.Union2ErrorOrSuccess> result;
        private java.util.Optional<Types.PartialUser> user;
        private java.util.Optional<java.util.List<Item>> items;
        private java.util.Optional<Types.PartialConfiguration> config;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public double getScore() {
            return this.score;
        }

        public void setScore(double score) {
            this.score = score;
        }
        public boolean getActive() {
            return this.active;
        }

        public void setActive(boolean active) {
            this.active = active;
        }
        public Void getNothing() {
            return this.nothing;
        }

        public void setNothing(Void nothing) {
            this.nothing = nothing;
        }
        public java.util.Optional<Unions.Union3StringOrStringOrString> getStatus() {
            return this.status;
        }

        public void setStatus(java.util.Optional<Unions.Union3StringOrStringOrString> status) {
            this.status = status;
        }
        public java.util.Optional<Unions.Union5IntOrIntOrIntOrIntOrInt> getPriority() {
            return this.priority;
        }

        public void setPriority(java.util.Optional<Unions.Union5IntOrIntOrIntOrIntOrInt> priority) {
            this.priority = priority;
        }
        public java.util.Optional<java.util.List<String>> getTags() {
            return this.tags;
        }

        public void setTags(java.util.Optional<java.util.List<String>> tags) {
            this.tags = tags;
        }
        public java.util.Optional<java.util.List<long>> getNumbers() {
            return this.numbers;
        }

        public void setNumbers(java.util.Optional<java.util.List<long>> numbers) {
            this.numbers = numbers;
        }
        public java.util.Optional<java.util.List<java.util.List<long>>> getMatrix() {
            return this.matrix;
        }

        public void setMatrix(java.util.Optional<java.util.List<java.util.List<long>>> matrix) {
            this.matrix = matrix;
        }
        public java.util.Optional<java.util.Map<String, String>> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Optional<java.util.Map<String, String>> metadata) {
            this.metadata = metadata;
        }
        public java.util.Optional<java.util.Map<String, double>> getScores() {
            return this.scores;
        }

        public void setScores(java.util.Optional<java.util.Map<String, double>> scores) {
            this.scores = scores;
        }
        public java.util.Optional<String> getDescription() {
            return this.description;
        }

        public void setDescription(java.util.Optional<String> description) {
            this.description = description;
        }
        public java.util.Optional<String> getNotes() {
            return this.notes;
        }

        public void setNotes(java.util.Optional<String> notes) {
            this.notes = notes;
        }
        public java.util.Optional<Unions.Union3DataObjectOrIntOrString> getData() {
            return this.data;
        }

        public void setData(java.util.Optional<Unions.Union3DataObjectOrIntOrString> data) {
            this.data = data;
        }
        public java.util.Optional<Unions.Union2ErrorOrSuccess> getResult() {
            return this.result;
        }

        public void setResult(java.util.Optional<Unions.Union2ErrorOrSuccess> result) {
            this.result = result;
        }
        public java.util.Optional<Types.PartialUser> getUser() {
            return this.user;
        }

        public void setUser(java.util.Optional<Types.PartialUser> user) {
            this.user = user;
        }
        public java.util.Optional<java.util.List<Item>> getItems() {
            return this.items;
        }

        public void setItems(java.util.Optional<java.util.List<Item>> items) {
            this.items = items;
        }
        public java.util.Optional<Types.PartialConfiguration> getConfig() {
            return this.config;
        }

        public void setConfig(java.util.Optional<Types.PartialConfiguration> config) {
            this.config = config;
        }
    }
    public static class Node {
        private long id;
        private Union2StringOrString type;
        private Union4IntOrListNodeOrMapStringNodeOrString value;
        private java.util.Optional<NodeMetadata> metadata;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public Union2StringOrString getType() {
            return this.type;
        }

        public void setType(Union2StringOrString type) {
            this.type = type;
        }
        public Union4IntOrListNodeOrMapStringNodeOrString getValue() {
            return this.value;
        }

        public void setValue(Union4IntOrListNodeOrMapStringNodeOrString value) {
            this.value = value;
        }
        public java.util.Optional<NodeMetadata> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Optional<NodeMetadata> metadata) {
            this.metadata = metadata;
        }
    }

    public static class PartialNode {
        private long id;
        private java.util.Optional<Unions.Union2StringOrString> type;
        private java.util.Optional<Unions.Union4IntOrListNodeOrMapStringNodeOrString> value;
        private java.util.Optional<NodeMetadata> metadata;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public java.util.Optional<Unions.Union2StringOrString> getType() {
            return this.type;
        }

        public void setType(java.util.Optional<Unions.Union2StringOrString> type) {
            this.type = type;
        }
        public java.util.Optional<Unions.Union4IntOrListNodeOrMapStringNodeOrString> getValue() {
            return this.value;
        }

        public void setValue(java.util.Optional<Unions.Union4IntOrListNodeOrMapStringNodeOrString> value) {
            this.value = value;
        }
        public java.util.Optional<NodeMetadata> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Optional<NodeMetadata> metadata) {
            this.metadata = metadata;
        }
    }
    public static class NodeMetadata {
        private String created;
        private String modified;
        private java.util.List<String> tags;
        private java.util.Map<String, Union3BoolOrIntOrStringOptional> attributes;

        public String getCreated() {
            return this.created;
        }

        public void setCreated(String created) {
            this.created = created;
        }
        public String getModified() {
            return this.modified;
        }

        public void setModified(String modified) {
            this.modified = modified;
        }
        public java.util.List<String> getTags() {
            return this.tags;
        }

        public void setTags(java.util.List<String> tags) {
            this.tags = tags;
        }
        public java.util.Map<String, Union3BoolOrIntOrStringOptional> getAttributes() {
            return this.attributes;
        }

        public void setAttributes(java.util.Map<String, Union3BoolOrIntOrStringOptional> attributes) {
            this.attributes = attributes;
        }
    }

    public static class PartialNodeMetadata {
        private String created;
        private String modified;
        private java.util.Optional<java.util.List<String>> tags;
        private java.util.Optional<java.util.Map<String, Union3BoolOrIntOrStringOptional>> attributes;

        public String getCreated() {
            return this.created;
        }

        public void setCreated(String created) {
            this.created = created;
        }
        public String getModified() {
            return this.modified;
        }

        public void setModified(String modified) {
            this.modified = modified;
        }
        public java.util.Optional<java.util.List<String>> getTags() {
            return this.tags;
        }

        public void setTags(java.util.Optional<java.util.List<String>> tags) {
            this.tags = tags;
        }
        public java.util.Optional<java.util.Map<String, Union3BoolOrIntOrStringOptional>> getAttributes() {
            return this.attributes;
        }

        public void setAttributes(java.util.Optional<java.util.Map<String, Union3BoolOrIntOrStringOptional>> attributes) {
            this.attributes = attributes;
        }
    }
    public static class PrimaryData {
        private java.util.List<Union3FloatOrIntOrString> values;
        private java.util.Map<String, java.util.Map<String, String>> mappings;
        private java.util.List<boolean> flags;

        public java.util.List<Union3FloatOrIntOrString> getValues() {
            return this.values;
        }

        public void setValues(java.util.List<Union3FloatOrIntOrString> values) {
            this.values = values;
        }
        public java.util.Map<String, java.util.Map<String, String>> getMappings() {
            return this.mappings;
        }

        public void setMappings(java.util.Map<String, java.util.Map<String, String>> mappings) {
            this.mappings = mappings;
        }
        public java.util.List<boolean> getFlags() {
            return this.flags;
        }

        public void setFlags(java.util.List<boolean> flags) {
            this.flags = flags;
        }
    }

    public static class PartialPrimaryData {
        private java.util.Optional<java.util.List<Union3FloatOrIntOrString>> values;
        private java.util.Optional<java.util.Map<String, java.util.Map<String, String>>> mappings;
        private java.util.Optional<java.util.List<boolean>> flags;

        public java.util.Optional<java.util.List<Union3FloatOrIntOrString>> getValues() {
            return this.values;
        }

        public void setValues(java.util.Optional<java.util.List<Union3FloatOrIntOrString>> values) {
            this.values = values;
        }
        public java.util.Optional<java.util.Map<String, java.util.Map<String, String>>> getMappings() {
            return this.mappings;
        }

        public void setMappings(java.util.Optional<java.util.Map<String, java.util.Map<String, String>>> mappings) {
            this.mappings = mappings;
        }
        public java.util.Optional<java.util.List<boolean>> getFlags() {
            return this.flags;
        }

        public void setFlags(java.util.Optional<java.util.List<boolean>> flags) {
            this.flags = flags;
        }
    }
    public static class Record {
        private long id;
        private java.util.Map<String, Union3BoolOrIntOrStringOptional> data;
        private java.util.Optional<java.util.List<Record>> related;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public java.util.Map<String, Union3BoolOrIntOrStringOptional> getData() {
            return this.data;
        }

        public void setData(java.util.Map<String, Union3BoolOrIntOrStringOptional> data) {
            this.data = data;
        }
        public java.util.Optional<java.util.List<Record>> getRelated() {
            return this.related;
        }

        public void setRelated(java.util.Optional<java.util.List<Record>> related) {
            this.related = related;
        }
    }

    public static class PartialRecord {
        private long id;
        private java.util.Optional<java.util.Map<String, Union3BoolOrIntOrStringOptional>> data;
        private java.util.Optional<java.util.List<Record>> related;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public java.util.Optional<java.util.Map<String, Union3BoolOrIntOrStringOptional>> getData() {
            return this.data;
        }

        public void setData(java.util.Optional<java.util.Map<String, Union3BoolOrIntOrStringOptional>> data) {
            this.data = data;
        }
        public java.util.Optional<java.util.List<Record>> getRelated() {
            return this.related;
        }

        public void setRelated(java.util.Optional<java.util.List<Record>> related) {
            this.related = related;
        }
    }
    public static class ResponseMetadata {
        private String timestamp;
        private String requestId;
        private long duration;
        private long retries;

        public String getTimestamp() {
            return this.timestamp;
        }

        public void setTimestamp(String timestamp) {
            this.timestamp = timestamp;
        }
        public String getRequestId() {
            return this.requestId;
        }

        public void setRequestId(String requestId) {
            this.requestId = requestId;
        }
        public long getDuration() {
            return this.duration;
        }

        public void setDuration(long duration) {
            this.duration = duration;
        }
        public long getRetries() {
            return this.retries;
        }

        public void setRetries(long retries) {
            this.retries = retries;
        }
    }

    public static class PartialResponseMetadata {
        private String timestamp;
        private String requestId;
        private long duration;
        private long retries;

        public String getTimestamp() {
            return this.timestamp;
        }

        public void setTimestamp(String timestamp) {
            this.timestamp = timestamp;
        }
        public String getRequestId() {
            return this.requestId;
        }

        public void setRequestId(String requestId) {
            this.requestId = requestId;
        }
        public long getDuration() {
            return this.duration;
        }

        public void setDuration(long duration) {
            this.duration = duration;
        }
        public long getRetries() {
            return this.retries;
        }

        public void setRetries(long retries) {
            this.retries = retries;
        }
    }
    public static class Rule {
        private long id;
        private String name;
        private Condition condition;
        private java.util.List<Action> actions;
        private long priority;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public Condition getCondition() {
            return this.condition;
        }

        public void setCondition(Condition condition) {
            this.condition = condition;
        }
        public java.util.List<Action> getActions() {
            return this.actions;
        }

        public void setActions(java.util.List<Action> actions) {
            this.actions = actions;
        }
        public long getPriority() {
            return this.priority;
        }

        public void setPriority(long priority) {
            this.priority = priority;
        }
    }

    public static class PartialRule {
        private long id;
        private String name;
        private java.util.Optional<Types.PartialCondition> condition;
        private java.util.Optional<java.util.List<Action>> actions;
        private long priority;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public java.util.Optional<Types.PartialCondition> getCondition() {
            return this.condition;
        }

        public void setCondition(java.util.Optional<Types.PartialCondition> condition) {
            this.condition = condition;
        }
        public java.util.Optional<java.util.List<Action>> getActions() {
            return this.actions;
        }

        public void setActions(java.util.Optional<java.util.List<Action>> actions) {
            this.actions = actions;
        }
        public long getPriority() {
            return this.priority;
        }

        public void setPriority(long priority) {
            this.priority = priority;
        }
    }
    public static class SecondaryData {
        private java.util.List<Record> records;
        private java.util.Map<String, Record> index;

        public java.util.List<Record> getRecords() {
            return this.records;
        }

        public void setRecords(java.util.List<Record> records) {
            this.records = records;
        }
        public java.util.Map<String, Record> getIndex() {
            return this.index;
        }

        public void setIndex(java.util.Map<String, Record> index) {
            this.index = index;
        }
    }

    public static class PartialSecondaryData {
        private java.util.Optional<java.util.List<Record>> records;
        private java.util.Optional<java.util.Map<String, Record>> index;

        public java.util.Optional<java.util.List<Record>> getRecords() {
            return this.records;
        }

        public void setRecords(java.util.Optional<java.util.List<Record>> records) {
            this.records = records;
        }
        public java.util.Optional<java.util.Map<String, Record>> getIndex() {
            return this.index;
        }

        public void setIndex(java.util.Optional<java.util.Map<String, Record>> index) {
            this.index = index;
        }
    }
    public static class Setting {
        private String key;
        private Union3BoolOrIntOrString value;
        private java.util.Optional<java.util.Map<String, String>> metadata;

        public String getKey() {
            return this.key;
        }

        public void setKey(String key) {
            this.key = key;
        }
        public Union3BoolOrIntOrString getValue() {
            return this.value;
        }

        public void setValue(Union3BoolOrIntOrString value) {
            this.value = value;
        }
        public java.util.Optional<java.util.Map<String, String>> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Optional<java.util.Map<String, String>> metadata) {
            this.metadata = metadata;
        }
    }

    public static class PartialSetting {
        private String key;
        private java.util.Optional<Unions.Union3BoolOrIntOrString> value;
        private java.util.Optional<java.util.Map<String, String>> metadata;

        public String getKey() {
            return this.key;
        }

        public void setKey(String key) {
            this.key = key;
        }
        public java.util.Optional<Unions.Union3BoolOrIntOrString> getValue() {
            return this.value;
        }

        public void setValue(java.util.Optional<Unions.Union3BoolOrIntOrString> value) {
            this.value = value;
        }
        public java.util.Optional<java.util.Map<String, String>> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Optional<java.util.Map<String, String>> metadata) {
            this.metadata = metadata;
        }
    }
    public static class SimpleCondition {
        private String field;
        private Union5StringOrStringOrStringOrStringOrString operator;
        private Union4BoolOrFloatOrIntOrString value;

        public String getField() {
            return this.field;
        }

        public void setField(String field) {
            this.field = field;
        }
        public Union5StringOrStringOrStringOrStringOrString getOperator() {
            return this.operator;
        }

        public void setOperator(Union5StringOrStringOrStringOrStringOrString operator) {
            this.operator = operator;
        }
        public Union4BoolOrFloatOrIntOrString getValue() {
            return this.value;
        }

        public void setValue(Union4BoolOrFloatOrIntOrString value) {
            this.value = value;
        }
    }

    public static class PartialSimpleCondition {
        private String field;
        private java.util.Optional<Unions.Union5StringOrStringOrStringOrStringOrString> operator;
        private java.util.Optional<Unions.Union4BoolOrFloatOrIntOrString> value;

        public String getField() {
            return this.field;
        }

        public void setField(String field) {
            this.field = field;
        }
        public java.util.Optional<Unions.Union5StringOrStringOrStringOrStringOrString> getOperator() {
            return this.operator;
        }

        public void setOperator(java.util.Optional<Unions.Union5StringOrStringOrStringOrStringOrString> operator) {
            this.operator = operator;
        }
        public java.util.Optional<Unions.Union4BoolOrFloatOrIntOrString> getValue() {
            return this.value;
        }

        public void setValue(java.util.Optional<Unions.Union4BoolOrFloatOrIntOrString> value) {
            this.value = value;
        }
    }
    public static class Success {
        private String type;
        private java.util.Map<String, String> data;

        public String getType() {
            return this.type;
        }

        public void setType(String type) {
            this.type = type;
        }
        public java.util.Map<String, String> getData() {
            return this.data;
        }

        public void setData(java.util.Map<String, String> data) {
            this.data = data;
        }
    }

    public static class PartialSuccess {
        private String type;
        private java.util.Optional<java.util.Map<String, String>> data;

        public String getType() {
            return this.type;
        }

        public void setType(String type) {
            this.type = type;
        }
        public java.util.Optional<java.util.Map<String, String>> getData() {
            return this.data;
        }

        public void setData(java.util.Optional<java.util.Map<String, String>> data) {
            this.data = data;
        }
    }
    public static class TertiaryData {
        private String raw;
        private java.util.Optional<java.util.Map<String, String>> parsed;
        private boolean valid;

        public String getRaw() {
            return this.raw;
        }

        public void setRaw(String raw) {
            this.raw = raw;
        }
        public java.util.Optional<java.util.Map<String, String>> getParsed() {
            return this.parsed;
        }

        public void setParsed(java.util.Optional<java.util.Map<String, String>> parsed) {
            this.parsed = parsed;
        }
        public boolean getValid() {
            return this.valid;
        }

        public void setValid(boolean valid) {
            this.valid = valid;
        }
    }

    public static class PartialTertiaryData {
        private String raw;
        private java.util.Optional<java.util.Map<String, String>> parsed;
        private boolean valid;

        public String getRaw() {
            return this.raw;
        }

        public void setRaw(String raw) {
            this.raw = raw;
        }
        public java.util.Optional<java.util.Map<String, String>> getParsed() {
            return this.parsed;
        }

        public void setParsed(java.util.Optional<java.util.Map<String, String>> parsed) {
            this.parsed = parsed;
        }
        public boolean getValid() {
            return this.valid;
        }

        public void setValid(boolean valid) {
            this.valid = valid;
        }
    }
    public static class TextWidget {
        private String content;
        private Union3StringOrStringOrString format;
        private java.util.Map<String, String> style;

        public String getContent() {
            return this.content;
        }

        public void setContent(String content) {
            this.content = content;
        }
        public Union3StringOrStringOrString getFormat() {
            return this.format;
        }

        public void setFormat(Union3StringOrStringOrString format) {
            this.format = format;
        }
        public java.util.Map<String, String> getStyle() {
            return this.style;
        }

        public void setStyle(java.util.Map<String, String> style) {
            this.style = style;
        }
    }

    public static class PartialTextWidget {
        private String content;
        private java.util.Optional<Unions.Union3StringOrStringOrString> format;
        private java.util.Optional<java.util.Map<String, String>> style;

        public String getContent() {
            return this.content;
        }

        public void setContent(String content) {
            this.content = content;
        }
        public java.util.Optional<Unions.Union3StringOrStringOrString> getFormat() {
            return this.format;
        }

        public void setFormat(java.util.Optional<Unions.Union3StringOrStringOrString> format) {
            this.format = format;
        }
        public java.util.Optional<java.util.Map<String, String>> getStyle() {
            return this.style;
        }

        public void setStyle(java.util.Optional<java.util.Map<String, String>> style) {
            this.style = style;
        }
    }
    public static class UltraComplex {
        private Node tree;
        private java.util.List<Widget> widgets;
        private java.util.Optional<ComplexData> data;
        private UserResponse response;
        private java.util.List<Asset> assets;

        public Node getTree() {
            return this.tree;
        }

        public void setTree(Node tree) {
            this.tree = tree;
        }
        public java.util.List<Widget> getWidgets() {
            return this.widgets;
        }

        public void setWidgets(java.util.List<Widget> widgets) {
            this.widgets = widgets;
        }
        public java.util.Optional<ComplexData> getData() {
            return this.data;
        }

        public void setData(java.util.Optional<ComplexData> data) {
            this.data = data;
        }
        public UserResponse getResponse() {
            return this.response;
        }

        public void setResponse(UserResponse response) {
            this.response = response;
        }
        public java.util.List<Asset> getAssets() {
            return this.assets;
        }

        public void setAssets(java.util.List<Asset> assets) {
            this.assets = assets;
        }
    }

    public static class PartialUltraComplex {
        private java.util.Optional<Types.PartialNode> tree;
        private java.util.Optional<java.util.List<Widget>> widgets;
        private java.util.Optional<ComplexData> data;
        private java.util.Optional<Types.PartialUserResponse> response;
        private java.util.Optional<java.util.List<Asset>> assets;

        public java.util.Optional<Types.PartialNode> getTree() {
            return this.tree;
        }

        public void setTree(java.util.Optional<Types.PartialNode> tree) {
            this.tree = tree;
        }
        public java.util.Optional<java.util.List<Widget>> getWidgets() {
            return this.widgets;
        }

        public void setWidgets(java.util.Optional<java.util.List<Widget>> widgets) {
            this.widgets = widgets;
        }
        public java.util.Optional<ComplexData> getData() {
            return this.data;
        }

        public void setData(java.util.Optional<ComplexData> data) {
            this.data = data;
        }
        public java.util.Optional<Types.PartialUserResponse> getResponse() {
            return this.response;
        }

        public void setResponse(java.util.Optional<Types.PartialUserResponse> response) {
            this.response = response;
        }
        public java.util.Optional<java.util.List<Asset>> getAssets() {
            return this.assets;
        }

        public void setAssets(java.util.Optional<java.util.List<Asset>> assets) {
            this.assets = assets;
        }
    }
    public static class User {
        private long id;
        private UserProfile profile;
        private java.util.Map<String, Setting> settings;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public UserProfile getProfile() {
            return this.profile;
        }

        public void setProfile(UserProfile profile) {
            this.profile = profile;
        }
        public java.util.Map<String, Setting> getSettings() {
            return this.settings;
        }

        public void setSettings(java.util.Map<String, Setting> settings) {
            this.settings = settings;
        }
    }

    public static class PartialUser {
        private long id;
        private java.util.Optional<Types.PartialUserProfile> profile;
        private java.util.Optional<java.util.Map<String, Setting>> settings;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public java.util.Optional<Types.PartialUserProfile> getProfile() {
            return this.profile;
        }

        public void setProfile(java.util.Optional<Types.PartialUserProfile> profile) {
            this.profile = profile;
        }
        public java.util.Optional<java.util.Map<String, Setting>> getSettings() {
            return this.settings;
        }

        public void setSettings(java.util.Optional<java.util.Map<String, Setting>> settings) {
            this.settings = settings;
        }
    }
    public static class UserProfile {
        private String name;
        private String email;
        private java.util.Optional<String> bio;
        private java.util.List<String> links;

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getEmail() {
            return this.email;
        }

        public void setEmail(String email) {
            this.email = email;
        }
        public java.util.Optional<String> getBio() {
            return this.bio;
        }

        public void setBio(java.util.Optional<String> bio) {
            this.bio = bio;
        }
        public java.util.List<String> getLinks() {
            return this.links;
        }

        public void setLinks(java.util.List<String> links) {
            this.links = links;
        }
    }

    public static class PartialUserProfile {
        private String name;
        private String email;
        private java.util.Optional<String> bio;
        private java.util.Optional<java.util.List<String>> links;

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getEmail() {
            return this.email;
        }

        public void setEmail(String email) {
            this.email = email;
        }
        public java.util.Optional<String> getBio() {
            return this.bio;
        }

        public void setBio(java.util.Optional<String> bio) {
            this.bio = bio;
        }
        public java.util.Optional<java.util.List<String>> getLinks() {
            return this.links;
        }

        public void setLinks(java.util.Optional<java.util.List<String>> links) {
            this.links = links;
        }
    }
    public static class UserResponse {
        private Union2StringOrString status;
        private java.util.Optional<User> data;
        private java.util.Optional<ErrorDetail> error;
        private ResponseMetadata metadata;

        public Union2StringOrString getStatus() {
            return this.status;
        }

        public void setStatus(Union2StringOrString status) {
            this.status = status;
        }
        public java.util.Optional<User> getData() {
            return this.data;
        }

        public void setData(java.util.Optional<User> data) {
            this.data = data;
        }
        public java.util.Optional<ErrorDetail> getError() {
            return this.error;
        }

        public void setError(java.util.Optional<ErrorDetail> error) {
            this.error = error;
        }
        public ResponseMetadata getMetadata() {
            return this.metadata;
        }

        public void setMetadata(ResponseMetadata metadata) {
            this.metadata = metadata;
        }
    }

    public static class PartialUserResponse {
        private java.util.Optional<Unions.Union2StringOrString> status;
        private java.util.Optional<User> data;
        private java.util.Optional<ErrorDetail> error;
        private java.util.Optional<Types.PartialResponseMetadata> metadata;

        public java.util.Optional<Unions.Union2StringOrString> getStatus() {
            return this.status;
        }

        public void setStatus(java.util.Optional<Unions.Union2StringOrString> status) {
            this.status = status;
        }
        public java.util.Optional<User> getData() {
            return this.data;
        }

        public void setData(java.util.Optional<User> data) {
            this.data = data;
        }
        public java.util.Optional<ErrorDetail> getError() {
            return this.error;
        }

        public void setError(java.util.Optional<ErrorDetail> error) {
            this.error = error;
        }
        public java.util.Optional<Types.PartialResponseMetadata> getMetadata() {
            return this.metadata;
        }

        public void setMetadata(java.util.Optional<Types.PartialResponseMetadata> metadata) {
            this.metadata = metadata;
        }
    }
    public static class Variant {
        private String sku;
        private double price;
        private long stock;
        private java.util.Map<String, String> options;

        public String getSku() {
            return this.sku;
        }

        public void setSku(String sku) {
            this.sku = sku;
        }
        public double getPrice() {
            return this.price;
        }

        public void setPrice(double price) {
            this.price = price;
        }
        public long getStock() {
            return this.stock;
        }

        public void setStock(long stock) {
            this.stock = stock;
        }
        public java.util.Map<String, String> getOptions() {
            return this.options;
        }

        public void setOptions(java.util.Map<String, String> options) {
            this.options = options;
        }
    }

    public static class PartialVariant {
        private String sku;
        private double price;
        private long stock;
        private java.util.Optional<java.util.Map<String, String>> options;

        public String getSku() {
            return this.sku;
        }

        public void setSku(String sku) {
            this.sku = sku;
        }
        public double getPrice() {
            return this.price;
        }

        public void setPrice(double price) {
            this.price = price;
        }
        public long getStock() {
            return this.stock;
        }

        public void setStock(long stock) {
            this.stock = stock;
        }
        public java.util.Optional<java.util.Map<String, String>> getOptions() {
            return this.options;
        }

        public void setOptions(java.util.Optional<java.util.Map<String, String>> options) {
            this.options = options;
        }
    }
    public static class Widget {
        private Union4StringOrStringOrStringOrString type;
        private java.util.Optional<ButtonWidget> button;
        private java.util.Optional<TextWidget> text;
        private java.util.Optional<ImageWidget> img;
        private java.util.Optional<ContainerWidget> container;

        public Union4StringOrStringOrStringOrString getType() {
            return this.type;
        }

        public void setType(Union4StringOrStringOrStringOrString type) {
            this.type = type;
        }
        public java.util.Optional<ButtonWidget> getButton() {
            return this.button;
        }

        public void setButton(java.util.Optional<ButtonWidget> button) {
            this.button = button;
        }
        public java.util.Optional<TextWidget> getText() {
            return this.text;
        }

        public void setText(java.util.Optional<TextWidget> text) {
            this.text = text;
        }
        public java.util.Optional<ImageWidget> getImg() {
            return this.img;
        }

        public void setImg(java.util.Optional<ImageWidget> img) {
            this.img = img;
        }
        public java.util.Optional<ContainerWidget> getContainer() {
            return this.container;
        }

        public void setContainer(java.util.Optional<ContainerWidget> container) {
            this.container = container;
        }
    }

    public static class PartialWidget {
        private java.util.Optional<Unions.Union4StringOrStringOrStringOrString> type;
        private java.util.Optional<ButtonWidget> button;
        private java.util.Optional<TextWidget> text;
        private java.util.Optional<ImageWidget> img;
        private java.util.Optional<ContainerWidget> container;

        public java.util.Optional<Unions.Union4StringOrStringOrStringOrString> getType() {
            return this.type;
        }

        public void setType(java.util.Optional<Unions.Union4StringOrStringOrStringOrString> type) {
            this.type = type;
        }
        public java.util.Optional<ButtonWidget> getButton() {
            return this.button;
        }

        public void setButton(java.util.Optional<ButtonWidget> button) {
            this.button = button;
        }
        public java.util.Optional<TextWidget> getText() {
            return this.text;
        }

        public void setText(java.util.Optional<TextWidget> text) {
            this.text = text;
        }
        public java.util.Optional<ImageWidget> getImg() {
            return this.img;
        }

        public void setImg(java.util.Optional<ImageWidget> img) {
            this.img = img;
        }
        public java.util.Optional<ContainerWidget> getContainer() {
            return this.container;
        }

        public void setContainer(java.util.Optional<ContainerWidget> container) {
            this.container = container;
        }
    }
}
