// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML union types.
 */
public class Unions {

    public static final class Union2ConditionOrSimpleCondition {

        private final Types.Condition value0;

        private final Types.SimpleCondition value1;


        private Union2ConditionOrSimpleCondition(Types.Condition value0, Types.SimpleCondition value1) {

            this.value0 = value0;

            this.value1 = value1;

        }


        public static Union2ConditionOrSimpleCondition ofVariant0(Types.Condition value) {
            return new Union2ConditionOrSimpleCondition(value, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public Types.Condition getVariant0() {
            return this.value0;
        }

        public static Union2ConditionOrSimpleCondition ofVariant1(Types.SimpleCondition value) {
            return new Union2ConditionOrSimpleCondition(null, value);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Types.SimpleCondition getVariant1() {
            return this.value1;
        }

    }

    public static final class Union2ErrorOrSuccess {

        private final Types.Success value0;

        private final Types.Error value1;


        private Union2ErrorOrSuccess(Types.Success value0, Types.Error value1) {

            this.value0 = value0;

            this.value1 = value1;

        }


        public static Union2ErrorOrSuccess ofVariant0(Types.Success value) {
            return new Union2ErrorOrSuccess(value, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public Types.Success getVariant0() {
            return this.value0;
        }

        public static Union2ErrorOrSuccess ofVariant1(Types.Error value) {
            return new Union2ErrorOrSuccess(null, value);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Types.Error getVariant1() {
            return this.value1;
        }

    }

    public static final class Union2StringOrString {

        private final String value0;

        private final String value1;


        private Union2StringOrString(String value0, String value1) {

            this.value0 = value0;

            this.value1 = value1;

        }


        public static Union2StringOrString ofVariant0(String value) {
            return new Union2StringOrString(value, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union2StringOrString ofVariant1(String value) {
            return new Union2StringOrString(null, value);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public String getVariant1() {
            return this.value1;
        }

    }

    public static final class Union3BoolOrIntOrString {

        private final String value0;

        private final Long value1;

        private final Boolean value2;


        private Union3BoolOrIntOrString(String value0, Long value1, Boolean value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3BoolOrIntOrString ofVariant0(String value) {
            return new Union3BoolOrIntOrString(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union3BoolOrIntOrString ofVariant1(Long value) {
            return new Union3BoolOrIntOrString(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union3BoolOrIntOrString ofVariant2(Boolean value) {
            return new Union3BoolOrIntOrString(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Boolean getVariant2() {
            return this.value2;
        }

    }

    public static final class Union3BoolOrIntOrStringOptional {

        private final String value0;

        private final Long value1;

        private final Boolean value2;


        private Union3BoolOrIntOrStringOptional(String value0, Long value1, Boolean value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3BoolOrIntOrStringOptional ofVariant0(String value) {
            return new Union3BoolOrIntOrStringOptional(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union3BoolOrIntOrStringOptional ofVariant1(Long value) {
            return new Union3BoolOrIntOrStringOptional(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union3BoolOrIntOrStringOptional ofVariant2(Boolean value) {
            return new Union3BoolOrIntOrStringOptional(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Boolean getVariant2() {
            return this.value2;
        }

    }

    public static final class Union3DataObjectOrIntOrString {

        private final String value0;

        private final Long value1;

        private final Types.DataObject value2;


        private Union3DataObjectOrIntOrString(String value0, Long value1, Types.DataObject value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3DataObjectOrIntOrString ofVariant0(String value) {
            return new Union3DataObjectOrIntOrString(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union3DataObjectOrIntOrString ofVariant1(Long value) {
            return new Union3DataObjectOrIntOrString(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union3DataObjectOrIntOrString ofVariant2(Types.DataObject value) {
            return new Union3DataObjectOrIntOrString(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Types.DataObject getVariant2() {
            return this.value2;
        }

    }

    public static final class Union3FloatOrIntOrString {

        private final String value0;

        private final Long value1;

        private final Double value2;


        private Union3FloatOrIntOrString(String value0, Long value1, Double value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3FloatOrIntOrString ofVariant0(String value) {
            return new Union3FloatOrIntOrString(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union3FloatOrIntOrString ofVariant1(Long value) {
            return new Union3FloatOrIntOrString(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union3FloatOrIntOrString ofVariant2(Double value) {
            return new Union3FloatOrIntOrString(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Double getVariant2() {
            return this.value2;
        }

    }

    public static final class Union3StringOrStringOrString {

        private final String value0;

        private final String value1;

        private final String value2;


        private Union3StringOrStringOrString(String value0, String value1, String value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3StringOrStringOrString ofVariant0(String value) {
            return new Union3StringOrStringOrString(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union3StringOrStringOrString ofVariant1(String value) {
            return new Union3StringOrStringOrString(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public String getVariant1() {
            return this.value1;
        }

        public static Union3StringOrStringOrString ofVariant2(String value) {
            return new Union3StringOrStringOrString(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public String getVariant2() {
            return this.value2;
        }

    }

    public static final class Union4BoolOrFloatOrIntOrString {

        private final String value0;

        private final Long value1;

        private final Double value2;

        private final Boolean value3;


        private Union4BoolOrFloatOrIntOrString(String value0, Long value1, Double value2, Boolean value3) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

        }


        public static Union4BoolOrFloatOrIntOrString ofVariant0(String value) {
            return new Union4BoolOrFloatOrIntOrString(value, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union4BoolOrFloatOrIntOrString ofVariant1(Long value) {
            return new Union4BoolOrFloatOrIntOrString(null, value, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union4BoolOrFloatOrIntOrString ofVariant2(Double value) {
            return new Union4BoolOrFloatOrIntOrString(null, null, value, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Double getVariant2() {
            return this.value2;
        }

        public static Union4BoolOrFloatOrIntOrString ofVariant3(Boolean value) {
            return new Union4BoolOrFloatOrIntOrString(null, null, null, value);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public Boolean getVariant3() {
            return this.value3;
        }

    }

    public static final class Union4IntOrListNodeOrMapStringNodeOrString {

        private final String value0;

        private final Long value1;

        private final java.util.List<Node> value2;

        private final java.util.Map<String, Node> value3;


        private Union4IntOrListNodeOrMapStringNodeOrString(String value0, Long value1, java.util.List<Node> value2, java.util.Map<String, Node> value3) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

        }


        public static Union4IntOrListNodeOrMapStringNodeOrString ofVariant0(String value) {
            return new Union4IntOrListNodeOrMapStringNodeOrString(value, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union4IntOrListNodeOrMapStringNodeOrString ofVariant1(Long value) {
            return new Union4IntOrListNodeOrMapStringNodeOrString(null, value, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union4IntOrListNodeOrMapStringNodeOrString ofVariant2(java.util.List<Node> value) {
            return new Union4IntOrListNodeOrMapStringNodeOrString(null, null, value, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public java.util.List<Node> getVariant2() {
            return this.value2;
        }

        public static Union4IntOrListNodeOrMapStringNodeOrString ofVariant3(java.util.Map<String, Node> value) {
            return new Union4IntOrListNodeOrMapStringNodeOrString(null, null, null, value);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public java.util.Map<String, Node> getVariant3() {
            return this.value3;
        }

    }

    public static final class Union4StringOrStringOrStringOrString {

        private final String value0;

        private final String value1;

        private final String value2;

        private final String value3;


        private Union4StringOrStringOrStringOrString(String value0, String value1, String value2, String value3) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

        }


        public static Union4StringOrStringOrStringOrString ofVariant0(String value) {
            return new Union4StringOrStringOrStringOrString(value, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union4StringOrStringOrStringOrString ofVariant1(String value) {
            return new Union4StringOrStringOrStringOrString(null, value, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public String getVariant1() {
            return this.value1;
        }

        public static Union4StringOrStringOrStringOrString ofVariant2(String value) {
            return new Union4StringOrStringOrStringOrString(null, null, value, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public String getVariant2() {
            return this.value2;
        }

        public static Union4StringOrStringOrStringOrString ofVariant3(String value) {
            return new Union4StringOrStringOrStringOrString(null, null, null, value);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public String getVariant3() {
            return this.value3;
        }

    }

    public static final class Union5IntOrIntOrIntOrIntOrInt {

        private final Long value0;

        private final Long value1;

        private final Long value2;

        private final Long value3;

        private final Long value4;


        private Union5IntOrIntOrIntOrIntOrInt(Long value0, Long value1, Long value2, Long value3, Long value4) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

            this.value4 = value4;

        }


        public static Union5IntOrIntOrIntOrIntOrInt ofVariant0(Long value) {
            return new Union5IntOrIntOrIntOrIntOrInt(value, null, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public Long getVariant0() {
            return this.value0;
        }

        public static Union5IntOrIntOrIntOrIntOrInt ofVariant1(Long value) {
            return new Union5IntOrIntOrIntOrIntOrInt(null, value, null, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union5IntOrIntOrIntOrIntOrInt ofVariant2(Long value) {
            return new Union5IntOrIntOrIntOrIntOrInt(null, null, value, null, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Long getVariant2() {
            return this.value2;
        }

        public static Union5IntOrIntOrIntOrIntOrInt ofVariant3(Long value) {
            return new Union5IntOrIntOrIntOrIntOrInt(null, null, null, value, null);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public Long getVariant3() {
            return this.value3;
        }

        public static Union5IntOrIntOrIntOrIntOrInt ofVariant4(Long value) {
            return new Union5IntOrIntOrIntOrIntOrInt(null, null, null, null, value);
        }

        public boolean isVariant4() {
            return this.value4 != null;
        }

        public Long getVariant4() {
            return this.value4;
        }

    }

    public static final class Union5StringOrStringOrStringOrStringOrString {

        private final String value0;

        private final String value1;

        private final String value2;

        private final String value3;

        private final String value4;


        private Union5StringOrStringOrStringOrStringOrString(String value0, String value1, String value2, String value3, String value4) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

            this.value4 = value4;

        }


        public static Union5StringOrStringOrStringOrStringOrString ofVariant0(String value) {
            return new Union5StringOrStringOrStringOrStringOrString(value, null, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union5StringOrStringOrStringOrStringOrString ofVariant1(String value) {
            return new Union5StringOrStringOrStringOrStringOrString(null, value, null, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public String getVariant1() {
            return this.value1;
        }

        public static Union5StringOrStringOrStringOrStringOrString ofVariant2(String value) {
            return new Union5StringOrStringOrStringOrStringOrString(null, null, value, null, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public String getVariant2() {
            return this.value2;
        }

        public static Union5StringOrStringOrStringOrStringOrString ofVariant3(String value) {
            return new Union5StringOrStringOrStringOrStringOrString(null, null, null, value, null);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public String getVariant3() {
            return this.value3;
        }

        public static Union5StringOrStringOrStringOrStringOrString ofVariant4(String value) {
            return new Union5StringOrStringOrStringOrStringOrString(null, null, null, null, value);
        }

        public boolean isVariant4() {
            return this.value4 != null;
        }

        public String getVariant4() {
            return this.value4;
        }

    }

}
