// Generated by BAML - do not edit

import Foundation
import BamlSwift

/// Returns the process environment with TEST_RUNNER_* variables normalized.
/// xcodebuild passes env vars with a TEST_RUNNER_ prefix; this strips it so
/// BAML clients can find OPENROUTER_API_KEY regardless of which form is set.
internal func processEnv() -> [String: String] {
    var env = ProcessInfo.processInfo.environment
    for (key, value) in env where key.hasPrefix("TEST_RUNNER_") {
        let stripped = String(key.dropFirst("TEST_RUNNER_".count))
        if env[stripped] == nil { env[stripped] = value }
    }
    return env
}

public func AnalyzeText(text: String) async throws -> TextAnalysis {
    var kwargs: [String: Any] = [:]
    kwargs["text"] = text
    let argsData = try BamlEncoder.encodeFunctionArgs(
        kwargs: kwargs,
        envVars: processEnv()
    )
    let resultData = try await bamlClient.callFunction(name: "AnalyzeText", args: argsData)
    return try BamlDecoder.decodeResult(resultData)
}
