// Generated by BAML - do not edit

import Foundation
import BamlSwift

public func AnalyzeTextStream(text: String) throws -> AsyncThrowingStream<TextAnalysis, Error> {
    var kwargs: [String: Any] = [:]
    kwargs["text"] = text
    let argsData = try BamlEncoder.encodeFunctionArgs(
        kwargs: kwargs,
        envVars: processEnv()
    )
    let dataStream = bamlClient.callFunctionStream(name: "AnalyzeText", args: argsData)
    return AsyncThrowingStream { continuation in
        Task {
            do {
                for try await chunk in dataStream {
                    if let value = try? BamlDecoder.decodeResult(chunk) as TextAnalysis {
                        continuation.yield(value)
                    }
                }
                continuation.finish()
            } catch {
                continuation.finish(throwing: error)
            }
        }
    }
}
