// Generated by BAML - do not edit

/// Sentiment classification result.
public enum Sentiment: String, Codable, Sendable, CaseIterable {
    case Positive = "Positive"
    case Negative = "Negative"
    case Neutral  = "Neutral"
    case Mixed    = "Mixed"
}
