// Generated by BAML - do not edit

/// Structured analysis of a piece of text.
public struct TextAnalysis: Codable, Sendable {
    public var title: String
    public var summary: String
    public var themes: [String]
    public var sentiment: Sentiment
    public var key_points: [String]

    public init(
        title: String,
        summary: String,
        themes: [String],
        sentiment: Sentiment,
        key_points: [String]
    ) {
        self.title = title
        self.summary = summary
        self.themes = themes
        self.sentiment = sentiment
        self.key_points = key_points
    }
}
