// Generated by BAML - do not edit

import Foundation
import BamlSwift

// MARK: - BAML source file map

private let bamlFileMap: [String: String] = [
    "clients.baml": #"""
retry_policy Retry {
  max_retries 3
  strategy {
    type exponential_backoff
  }
}

client<llm> OpenRouterClient {
  provider openrouter
  retry_policy Retry
  options {
    model "stepfun/step-3.5-flash:free"
    api_key env.OPENROUTER_API_KEY
    temperature 0
    max_tokens 8192
  }
}
"""#,
    "functions.baml": ##"""
enum Sentiment {
  Positive
  Negative
  Neutral
  Mixed
}

class TextAnalysis {
  title      string    @description("short title, max 10 words")
  summary    string    @description("2-3 sentence summary")
  themes     string[]  @description("3-5 topic tags")
  sentiment  Sentiment
  key_points string[]  @description("3-5 short bullet takeaways")
}

function AnalyzeText(text: string) -> TextAnalysis {
  client OpenRouterClient
  prompt #"
    Analyze the following text and extract key information.

    Text: {{ text }}

    {{ ctx.output_format }}
  "#
}
"""##,
]

func getBamlFiles() -> [String: String] {
    return bamlFileMap
}

// MARK: - Shared runtime instance

/// Shared BAML runtime instance for all generated functions.
/// Initialized lazily on first access using the generated file map.
public let bamlClient: BamlRuntime = {
    let files = getBamlFiles()
    do {
        return try BamlRuntime(
            rootPath: ".",
            srcFiles: files,
            envVars: [:]
        )
    } catch {
        fatalError("Failed to initialize BAML runtime: \(error)")
    }
}()
