// Generated by BAML - do not edit

import Foundation
import BamlSwift

/// Returns the process environment with TEST_RUNNER_* variables normalized.
/// xcodebuild passes env vars with a TEST_RUNNER_ prefix; this strips it so
/// BAML clients can find OPENROUTER_API_KEY regardless of which form is set.
internal func processEnv() -> [String: String] {
    var env = ProcessInfo.processInfo.environment
    for (key, value) in env where key.hasPrefix("TEST_RUNNER_") {
        let stripped = String(key.dropFirst("TEST_RUNNER_".count))
        if env[stripped] == nil { env[stripped] = value }
    }
    return env
}

public func AnalyzeText(text: String) async throws -> TextAnalysis {
    let preview = String(text.prefix(80)).replacingOccurrences(of: "\n", with: " ")
    print("[BAML] AnalyzeText called")
    print("[BAML] Model  : stepfun/step-3.5-flash:free via OpenRouter")
    print("[BAML] Input  : \"\(preview)\(text.count > 80 ? "…" : "")\"")

    var kwargs: [String: Any] = [:]
    kwargs["text"] = text
    let argsData = try BamlEncoder.encodeFunctionArgs(
        kwargs: kwargs,
        envVars: processEnv()
    )

    let start = Date()
    let resultData = try await bamlClient.callFunction(name: "AnalyzeText", args: argsData)
    let elapsed = Date().timeIntervalSince(start)

    let result: TextAnalysis = try BamlDecoder.decodeResult(resultData)

    print("[BAML] Elapsed : \(String(format: "%.2f", elapsed))s")
    print("[BAML] Title   : \(result.title)")
    print("[BAML] Sentiment: \(result.sentiment.rawValue)")
    print("[BAML] Themes  : \(result.themes.joined(separator: ", "))")
    print("[BAML] Points  : \(result.key_points.count) key points")

    return result
}
