// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML class types.
 */
public class Types {
    public static class ComplexMaps {
        private java.util.Map<String, User> userMap;
        private java.util.Map<String, Product> productMap;
        private java.util.Map<String, java.util.Map<String, String>> nestedMap;
        private java.util.Map<String, java.util.List<long>> arrayMap;
        private java.util.List<java.util.Map<String, String>> mapArray;

        public java.util.Map<String, User> getUserMap() {
            return this.userMap;
        }

        public void setUserMap(java.util.Map<String, User> userMap) {
            this.userMap = userMap;
        }
        public java.util.Map<String, Product> getProductMap() {
            return this.productMap;
        }

        public void setProductMap(java.util.Map<String, Product> productMap) {
            this.productMap = productMap;
        }
        public java.util.Map<String, java.util.Map<String, String>> getNestedMap() {
            return this.nestedMap;
        }

        public void setNestedMap(java.util.Map<String, java.util.Map<String, String>> nestedMap) {
            this.nestedMap = nestedMap;
        }
        public java.util.Map<String, java.util.List<long>> getArrayMap() {
            return this.arrayMap;
        }

        public void setArrayMap(java.util.Map<String, java.util.List<long>> arrayMap) {
            this.arrayMap = arrayMap;
        }
        public java.util.List<java.util.Map<String, String>> getMapArray() {
            return this.mapArray;
        }

        public void setMapArray(java.util.List<java.util.Map<String, String>> mapArray) {
            this.mapArray = mapArray;
        }
    }

    public static class PartialComplexMaps {
        private java.util.Optional<java.util.Map<String, User>> userMap;
        private java.util.Optional<java.util.Map<String, Product>> productMap;
        private java.util.Optional<java.util.Map<String, java.util.Map<String, String>>> nestedMap;
        private java.util.Optional<java.util.Map<String, java.util.List<long>>> arrayMap;
        private java.util.Optional<java.util.List<java.util.Map<String, String>>> mapArray;

        public java.util.Optional<java.util.Map<String, User>> getUserMap() {
            return this.userMap;
        }

        public void setUserMap(java.util.Optional<java.util.Map<String, User>> userMap) {
            this.userMap = userMap;
        }
        public java.util.Optional<java.util.Map<String, Product>> getProductMap() {
            return this.productMap;
        }

        public void setProductMap(java.util.Optional<java.util.Map<String, Product>> productMap) {
            this.productMap = productMap;
        }
        public java.util.Optional<java.util.Map<String, java.util.Map<String, String>>> getNestedMap() {
            return this.nestedMap;
        }

        public void setNestedMap(java.util.Optional<java.util.Map<String, java.util.Map<String, String>>> nestedMap) {
            this.nestedMap = nestedMap;
        }
        public java.util.Optional<java.util.Map<String, java.util.List<long>>> getArrayMap() {
            return this.arrayMap;
        }

        public void setArrayMap(java.util.Optional<java.util.Map<String, java.util.List<long>>> arrayMap) {
            this.arrayMap = arrayMap;
        }
        public java.util.Optional<java.util.List<java.util.Map<String, String>>> getMapArray() {
            return this.mapArray;
        }

        public void setMapArray(java.util.Optional<java.util.List<java.util.Map<String, String>>> mapArray) {
            this.mapArray = mapArray;
        }
    }
    public static class Config {
        private String url;
        private long port;
        private boolean debug;

        public String getUrl() {
            return this.url;
        }

        public void setUrl(String url) {
            this.url = url;
        }
        public long getPort() {
            return this.port;
        }

        public void setPort(long port) {
            this.port = port;
        }
        public boolean getDebug() {
            return this.debug;
        }

        public void setDebug(boolean debug) {
            this.debug = debug;
        }
    }

    public static class PartialConfig {
        private String url;
        private long port;
        private boolean debug;

        public String getUrl() {
            return this.url;
        }

        public void setUrl(String url) {
            this.url = url;
        }
        public long getPort() {
            return this.port;
        }

        public void setPort(long port) {
            this.port = port;
        }
        public boolean getDebug() {
            return this.debug;
        }

        public void setDebug(boolean debug) {
            this.debug = debug;
        }
    }
    public static class EdgeCaseMaps {
        private java.util.Map<String, String> emptyMap;
        private java.util.Map<String, java.util.Optional<String>> nullableValues;
        private java.util.Map<String, java.util.Optional<String>> optionalValues;
        private java.util.Map<String, Union3BoolOrIntOrString> unionValues;

        public java.util.Map<String, String> getEmptyMap() {
            return this.emptyMap;
        }

        public void setEmptyMap(java.util.Map<String, String> emptyMap) {
            this.emptyMap = emptyMap;
        }
        public java.util.Map<String, java.util.Optional<String>> getNullableValues() {
            return this.nullableValues;
        }

        public void setNullableValues(java.util.Map<String, java.util.Optional<String>> nullableValues) {
            this.nullableValues = nullableValues;
        }
        public java.util.Map<String, java.util.Optional<String>> getOptionalValues() {
            return this.optionalValues;
        }

        public void setOptionalValues(java.util.Map<String, java.util.Optional<String>> optionalValues) {
            this.optionalValues = optionalValues;
        }
        public java.util.Map<String, Union3BoolOrIntOrString> getUnionValues() {
            return this.unionValues;
        }

        public void setUnionValues(java.util.Map<String, Union3BoolOrIntOrString> unionValues) {
            this.unionValues = unionValues;
        }
    }

    public static class PartialEdgeCaseMaps {
        private java.util.Optional<java.util.Map<String, String>> emptyMap;
        private java.util.Optional<java.util.Map<String, java.util.Optional<String>>> nullableValues;
        private java.util.Optional<java.util.Map<String, java.util.Optional<String>>> optionalValues;
        private java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> unionValues;

        public java.util.Optional<java.util.Map<String, String>> getEmptyMap() {
            return this.emptyMap;
        }

        public void setEmptyMap(java.util.Optional<java.util.Map<String, String>> emptyMap) {
            this.emptyMap = emptyMap;
        }
        public java.util.Optional<java.util.Map<String, java.util.Optional<String>>> getNullableValues() {
            return this.nullableValues;
        }

        public void setNullableValues(java.util.Optional<java.util.Map<String, java.util.Optional<String>>> nullableValues) {
            this.nullableValues = nullableValues;
        }
        public java.util.Optional<java.util.Map<String, java.util.Optional<String>>> getOptionalValues() {
            return this.optionalValues;
        }

        public void setOptionalValues(java.util.Optional<java.util.Map<String, java.util.Optional<String>>> optionalValues) {
            this.optionalValues = optionalValues;
        }
        public java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> getUnionValues() {
            return this.unionValues;
        }

        public void setUnionValues(java.util.Optional<java.util.Map<String, Union3BoolOrIntOrString>> unionValues) {
            this.unionValues = unionValues;
        }
    }
    public static class MixedKeyMaps {
        private java.util.Map<String, long> stringIntMap;
        private java.util.Map<String, String> intStringMap;
        private java.util.Map<String, String> enumMap;
        private java.util.Map<String, Config> literalMap;

        public java.util.Map<String, long> getStringIntMap() {
            return this.stringIntMap;
        }

        public void setStringIntMap(java.util.Map<String, long> stringIntMap) {
            this.stringIntMap = stringIntMap;
        }
        public java.util.Map<String, String> getIntStringMap() {
            return this.intStringMap;
        }

        public void setIntStringMap(java.util.Map<String, String> intStringMap) {
            this.intStringMap = intStringMap;
        }
        public java.util.Map<String, String> getEnumMap() {
            return this.enumMap;
        }

        public void setEnumMap(java.util.Map<String, String> enumMap) {
            this.enumMap = enumMap;
        }
        public java.util.Map<String, Config> getLiteralMap() {
            return this.literalMap;
        }

        public void setLiteralMap(java.util.Map<String, Config> literalMap) {
            this.literalMap = literalMap;
        }
    }

    public static class PartialMixedKeyMaps {
        private java.util.Optional<java.util.Map<String, long>> stringIntMap;
        private java.util.Optional<java.util.Map<String, String>> intStringMap;
        private java.util.Optional<java.util.Map<String, String>> enumMap;
        private java.util.Optional<java.util.Map<String, Config>> literalMap;

        public java.util.Optional<java.util.Map<String, long>> getStringIntMap() {
            return this.stringIntMap;
        }

        public void setStringIntMap(java.util.Optional<java.util.Map<String, long>> stringIntMap) {
            this.stringIntMap = stringIntMap;
        }
        public java.util.Optional<java.util.Map<String, String>> getIntStringMap() {
            return this.intStringMap;
        }

        public void setIntStringMap(java.util.Optional<java.util.Map<String, String>> intStringMap) {
            this.intStringMap = intStringMap;
        }
        public java.util.Optional<java.util.Map<String, String>> getEnumMap() {
            return this.enumMap;
        }

        public void setEnumMap(java.util.Optional<java.util.Map<String, String>> enumMap) {
            this.enumMap = enumMap;
        }
        public java.util.Optional<java.util.Map<String, Config>> getLiteralMap() {
            return this.literalMap;
        }

        public void setLiteralMap(java.util.Optional<java.util.Map<String, Config>> literalMap) {
            this.literalMap = literalMap;
        }
    }
    public static class NestedMaps {
        private java.util.Map<String, String> simple;
        private java.util.Map<String, java.util.Map<String, long>> oneLevelNested;
        private java.util.Map<String, java.util.Map<String, java.util.Map<String, boolean>>> twoLevelNested;
        private java.util.Map<String, java.util.List<String>> mapOfArrays;
        private java.util.Map<String, java.util.Map<String, double>> mapOfMaps;

        public java.util.Map<String, String> getSimple() {
            return this.simple;
        }

        public void setSimple(java.util.Map<String, String> simple) {
            this.simple = simple;
        }
        public java.util.Map<String, java.util.Map<String, long>> getOneLevelNested() {
            return this.oneLevelNested;
        }

        public void setOneLevelNested(java.util.Map<String, java.util.Map<String, long>> oneLevelNested) {
            this.oneLevelNested = oneLevelNested;
        }
        public java.util.Map<String, java.util.Map<String, java.util.Map<String, boolean>>> getTwoLevelNested() {
            return this.twoLevelNested;
        }

        public void setTwoLevelNested(java.util.Map<String, java.util.Map<String, java.util.Map<String, boolean>>> twoLevelNested) {
            this.twoLevelNested = twoLevelNested;
        }
        public java.util.Map<String, java.util.List<String>> getMapOfArrays() {
            return this.mapOfArrays;
        }

        public void setMapOfArrays(java.util.Map<String, java.util.List<String>> mapOfArrays) {
            this.mapOfArrays = mapOfArrays;
        }
        public java.util.Map<String, java.util.Map<String, double>> getMapOfMaps() {
            return this.mapOfMaps;
        }

        public void setMapOfMaps(java.util.Map<String, java.util.Map<String, double>> mapOfMaps) {
            this.mapOfMaps = mapOfMaps;
        }
    }

    public static class PartialNestedMaps {
        private java.util.Optional<java.util.Map<String, String>> simple;
        private java.util.Optional<java.util.Map<String, java.util.Map<String, long>>> oneLevelNested;
        private java.util.Optional<java.util.Map<String, java.util.Map<String, java.util.Map<String, boolean>>>> twoLevelNested;
        private java.util.Optional<java.util.Map<String, java.util.List<String>>> mapOfArrays;
        private java.util.Optional<java.util.Map<String, java.util.Map<String, double>>> mapOfMaps;

        public java.util.Optional<java.util.Map<String, String>> getSimple() {
            return this.simple;
        }

        public void setSimple(java.util.Optional<java.util.Map<String, String>> simple) {
            this.simple = simple;
        }
        public java.util.Optional<java.util.Map<String, java.util.Map<String, long>>> getOneLevelNested() {
            return this.oneLevelNested;
        }

        public void setOneLevelNested(java.util.Optional<java.util.Map<String, java.util.Map<String, long>>> oneLevelNested) {
            this.oneLevelNested = oneLevelNested;
        }
        public java.util.Optional<java.util.Map<String, java.util.Map<String, java.util.Map<String, boolean>>>> getTwoLevelNested() {
            return this.twoLevelNested;
        }

        public void setTwoLevelNested(java.util.Optional<java.util.Map<String, java.util.Map<String, java.util.Map<String, boolean>>>> twoLevelNested) {
            this.twoLevelNested = twoLevelNested;
        }
        public java.util.Optional<java.util.Map<String, java.util.List<String>>> getMapOfArrays() {
            return this.mapOfArrays;
        }

        public void setMapOfArrays(java.util.Optional<java.util.Map<String, java.util.List<String>>> mapOfArrays) {
            this.mapOfArrays = mapOfArrays;
        }
        public java.util.Optional<java.util.Map<String, java.util.Map<String, double>>> getMapOfMaps() {
            return this.mapOfMaps;
        }

        public void setMapOfMaps(java.util.Optional<java.util.Map<String, java.util.Map<String, double>>> mapOfMaps) {
            this.mapOfMaps = mapOfMaps;
        }
    }
    public static class Product {
        private long id;
        private String name;
        private double price;
        private java.util.List<String> tags;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public double getPrice() {
            return this.price;
        }

        public void setPrice(double price) {
            this.price = price;
        }
        public java.util.List<String> getTags() {
            return this.tags;
        }

        public void setTags(java.util.List<String> tags) {
            this.tags = tags;
        }
    }

    public static class PartialProduct {
        private long id;
        private String name;
        private double price;
        private java.util.Optional<java.util.List<String>> tags;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public double getPrice() {
            return this.price;
        }

        public void setPrice(double price) {
            this.price = price;
        }
        public java.util.Optional<java.util.List<String>> getTags() {
            return this.tags;
        }

        public void setTags(java.util.Optional<java.util.List<String>> tags) {
            this.tags = tags;
        }
    }
    public static class SimpleMaps {
        private java.util.Map<String, String> stringToString;
        private java.util.Map<String, long> stringToInt;
        private java.util.Map<String, double> stringToFloat;
        private java.util.Map<String, boolean> stringToBool;
        private java.util.Map<String, String> intToString;

        public java.util.Map<String, String> getStringToString() {
            return this.stringToString;
        }

        public void setStringToString(java.util.Map<String, String> stringToString) {
            this.stringToString = stringToString;
        }
        public java.util.Map<String, long> getStringToInt() {
            return this.stringToInt;
        }

        public void setStringToInt(java.util.Map<String, long> stringToInt) {
            this.stringToInt = stringToInt;
        }
        public java.util.Map<String, double> getStringToFloat() {
            return this.stringToFloat;
        }

        public void setStringToFloat(java.util.Map<String, double> stringToFloat) {
            this.stringToFloat = stringToFloat;
        }
        public java.util.Map<String, boolean> getStringToBool() {
            return this.stringToBool;
        }

        public void setStringToBool(java.util.Map<String, boolean> stringToBool) {
            this.stringToBool = stringToBool;
        }
        public java.util.Map<String, String> getIntToString() {
            return this.intToString;
        }

        public void setIntToString(java.util.Map<String, String> intToString) {
            this.intToString = intToString;
        }
    }

    public static class PartialSimpleMaps {
        private java.util.Optional<java.util.Map<String, String>> stringToString;
        private java.util.Optional<java.util.Map<String, long>> stringToInt;
        private java.util.Optional<java.util.Map<String, double>> stringToFloat;
        private java.util.Optional<java.util.Map<String, boolean>> stringToBool;
        private java.util.Optional<java.util.Map<String, String>> intToString;

        public java.util.Optional<java.util.Map<String, String>> getStringToString() {
            return this.stringToString;
        }

        public void setStringToString(java.util.Optional<java.util.Map<String, String>> stringToString) {
            this.stringToString = stringToString;
        }
        public java.util.Optional<java.util.Map<String, long>> getStringToInt() {
            return this.stringToInt;
        }

        public void setStringToInt(java.util.Optional<java.util.Map<String, long>> stringToInt) {
            this.stringToInt = stringToInt;
        }
        public java.util.Optional<java.util.Map<String, double>> getStringToFloat() {
            return this.stringToFloat;
        }

        public void setStringToFloat(java.util.Optional<java.util.Map<String, double>> stringToFloat) {
            this.stringToFloat = stringToFloat;
        }
        public java.util.Optional<java.util.Map<String, boolean>> getStringToBool() {
            return this.stringToBool;
        }

        public void setStringToBool(java.util.Optional<java.util.Map<String, boolean>> stringToBool) {
            this.stringToBool = stringToBool;
        }
        public java.util.Optional<java.util.Map<String, String>> getIntToString() {
            return this.intToString;
        }

        public void setIntToString(java.util.Optional<java.util.Map<String, String>> intToString) {
            this.intToString = intToString;
        }
    }
    public static class User {
        private long id;
        private String name;
        private String email;
        private boolean active;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getEmail() {
            return this.email;
        }

        public void setEmail(String email) {
            this.email = email;
        }
        public boolean getActive() {
            return this.active;
        }

        public void setActive(boolean active) {
            this.active = active;
        }
    }

    public static class PartialUser {
        private long id;
        private String name;
        private String email;
        private boolean active;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getEmail() {
            return this.email;
        }

        public void setEmail(String email) {
            this.email = email;
        }
        public boolean getActive() {
            return this.active;
        }

        public void setActive(boolean active) {
            this.active = active;
        }
    }
}
