// Generated by BAML - do not edit

import Foundation
import BamlSwift

public func SayHelloStream(name: String) throws -> AsyncThrowingStream<String, Error> {
    var kwargs: [String: Any] = [:]
    kwargs["name"] = name
    let argsData = try BamlEncoder.encodeFunctionArgs(
        kwargs: kwargs,
        envVars: processEnv()
    )
    let dataStream = bamlClient.callFunctionStream(name: "SayHello", args: argsData)
    return AsyncThrowingStream { continuation in
        Task {
            do {
                for try await chunk in dataStream {
                    if let value = try? BamlDecoder.decodeResult(chunk) as String {
                        continuation.yield(value)
                    }
                }
                continuation.finish()
            } catch {
                continuation.finish(throwing: error)
            }
        }
    }
}

public func ClassifySentimentStream(text: String) throws -> AsyncThrowingStream<Sentiment, Error> {
    var kwargs: [String: Any] = [:]
    kwargs["text"] = text
    let argsData = try BamlEncoder.encodeFunctionArgs(
        kwargs: kwargs,
        envVars: processEnv()
    )
    let dataStream = bamlClient.callFunctionStream(name: "ClassifySentiment", args: argsData)
    return AsyncThrowingStream { continuation in
        Task {
            do {
                for try await chunk in dataStream {
                    if let value = try? BamlDecoder.decodeResult(chunk) as Sentiment {
                        continuation.yield(value)
                    }
                }
                continuation.finish()
            } catch {
                continuation.finish(throwing: error)
            }
        }
    }
}

public func ExtractGreetingStream(text: String) throws -> AsyncThrowingStream<NamedGreeting, Error> {
    var kwargs: [String: Any] = [:]
    kwargs["text"] = text
    let argsData = try BamlEncoder.encodeFunctionArgs(
        kwargs: kwargs,
        envVars: processEnv()
    )
    let dataStream = bamlClient.callFunctionStream(name: "ExtractGreeting", args: argsData)
    return AsyncThrowingStream { continuation in
        Task {
            do {
                for try await chunk in dataStream {
                    if let value = try? BamlDecoder.decodeResult(chunk) as NamedGreeting {
                        continuation.yield(value)
                    }
                }
                continuation.finish()
            } catch {
                continuation.finish(throwing: error)
            }
        }
    }
}

public func ExtractResumeStream(text: String) throws -> AsyncThrowingStream<Resume, Error> {
    var kwargs: [String: Any] = [:]
    kwargs["text"] = text
    let argsData = try BamlEncoder.encodeFunctionArgs(
        kwargs: kwargs,
        envVars: processEnv()
    )
    let dataStream = bamlClient.callFunctionStream(name: "ExtractResume", args: argsData)
    return AsyncThrowingStream { continuation in
        Task {
            do {
                for try await chunk in dataStream {
                    if let value = try? BamlDecoder.decodeResult(chunk) as Resume {
                        continuation.yield(value)
                    }
                }
                continuation.finish()
            } catch {
                continuation.finish(throwing: error)
            }
        }
    }
}
