// Generated by BAML - do not edit

/// Structured resume information.
public struct Resume: Codable, Sendable {
    public var name: String
    public var skills: [String]
    public var years_experience: Int64

    public init(name: String, skills: [String], years_experience: Int64) {
        self.name = name
        self.skills = skills
        self.years_experience = years_experience
    }
}

/// A greeting paired with the name being greeted.
public struct NamedGreeting: Codable, Sendable {
    public var greeting: String
    public var name: String

    public init(greeting: String, name: String) {
        self.greeting = greeting
        self.name = name
    }
}
