// Generated by BAML - do not edit

import Foundation
import BamlSwift

// MARK: - BAML source file map

private let bamlFileMap: [String: String] = [
    "clients.baml": #"""
retry_policy Retry {
  max_retries 3
  strategy {
    type exponential_backoff
  }
}

client<llm> OpenRouterClient {
  provider openrouter
  retry_policy Retry
  options {
    model "stepfun/step-3.5-flash:free"
    api_key env.OPENROUTER_API_KEY
    temperature 0
    max_tokens 8192
  }
}
"""#,
    "functions.baml": ##"""
enum Sentiment {
  Positive
  Negative
  Neutral
}

class Resume {
  name string
  skills string[]
  years_experience int
}

class NamedGreeting {
  greeting string
  name string
}

function SayHello(name: string) -> string {
  client OpenRouterClient
  prompt #"
    Say "Hello, {{ name }}!" and nothing else.
  "#
}

function ClassifySentiment(text: string) -> Sentiment {
  client OpenRouterClient
  prompt #"
    Classify the sentiment of the following text as Positive, Negative, or Neutral.

    Text: {{ text }}

    {{ ctx.output_format }}
  "#
}

function ExtractGreeting(text: string) -> NamedGreeting {
  client OpenRouterClient
  prompt #"
    Extract the greeting and name from this text.

    Text: {{ text }}

    {{ ctx.output_format }}
  "#
}

function ExtractResume(text: string) -> Resume {
  client OpenRouterClient
  prompt #"
    Extract structured resume information from this text.

    Text: {{ text }}

    {{ ctx.output_format }}
  "#
}
"""##,
]

func getBamlFiles() -> [String: String] {
    return bamlFileMap
}

// MARK: - Shared runtime instance

/// Shared BAML runtime instance for all generated functions.
/// Initialized lazily on first access using the generated file map.
public let bamlClient: BamlRuntime = {
    let files = getBamlFiles()
    do {
        return try BamlRuntime(
            rootPath: ".",
            srcFiles: files,
            envVars: [:]
        )
    } catch {
        fatalError("Failed to initialize BAML runtime: \(error)")
    }
}()
