// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML class types.
 */
public class Types {
    public static class ArrayWithConstraints {
        private java.util.List<String> nonEmptyStrings;
        private java.util.List<long> limitedInts;
        private java.util.List<double> positiveFloats;

        public java.util.List<String> getNonEmptyStrings() {
            return this.nonEmptyStrings;
        }

        public void setNonEmptyStrings(java.util.List<String> nonEmptyStrings) {
            this.nonEmptyStrings = nonEmptyStrings;
        }
        public java.util.List<long> getLimitedInts() {
            return this.limitedInts;
        }

        public void setLimitedInts(java.util.List<long> limitedInts) {
            this.limitedInts = limitedInts;
        }
        public java.util.List<double> getPositiveFloats() {
            return this.positiveFloats;
        }

        public void setPositiveFloats(java.util.List<double> positiveFloats) {
            this.positiveFloats = positiveFloats;
        }
    }

    public static class PartialArrayWithConstraints {
        private java.util.Optional<java.util.List<String>> nonEmptyStrings;
        private java.util.Optional<java.util.List<long>> limitedInts;
        private java.util.Optional<java.util.List<double>> positiveFloats;

        public java.util.Optional<java.util.List<String>> getNonEmptyStrings() {
            return this.nonEmptyStrings;
        }

        public void setNonEmptyStrings(java.util.Optional<java.util.List<String>> nonEmptyStrings) {
            this.nonEmptyStrings = nonEmptyStrings;
        }
        public java.util.Optional<java.util.List<long>> getLimitedInts() {
            return this.limitedInts;
        }

        public void setLimitedInts(java.util.Optional<java.util.List<long>> limitedInts) {
            this.limitedInts = limitedInts;
        }
        public java.util.Optional<java.util.List<double>> getPositiveFloats() {
            return this.positiveFloats;
        }

        public void setPositiveFloats(java.util.Optional<java.util.List<double>> positiveFloats) {
            this.positiveFloats = positiveFloats;
        }
    }
    public static class MixedArrays {
        private java.util.List<Union4BoolOrFloatOrIntOrString> primitiveArray;
        private java.util.List<java.util.Optional<String>> nullableArray;
        private java.util.List<java.util.Optional<String>> optionalItems;
        private java.util.List<java.util.List<String>> arrayOfArrays;
        private java.util.List<Union3ProductOrTagOrUser> complexMixed;

        public java.util.List<Union4BoolOrFloatOrIntOrString> getPrimitiveArray() {
            return this.primitiveArray;
        }

        public void setPrimitiveArray(java.util.List<Union4BoolOrFloatOrIntOrString> primitiveArray) {
            this.primitiveArray = primitiveArray;
        }
        public java.util.List<java.util.Optional<String>> getNullableArray() {
            return this.nullableArray;
        }

        public void setNullableArray(java.util.List<java.util.Optional<String>> nullableArray) {
            this.nullableArray = nullableArray;
        }
        public java.util.List<java.util.Optional<String>> getOptionalItems() {
            return this.optionalItems;
        }

        public void setOptionalItems(java.util.List<java.util.Optional<String>> optionalItems) {
            this.optionalItems = optionalItems;
        }
        public java.util.List<java.util.List<String>> getArrayOfArrays() {
            return this.arrayOfArrays;
        }

        public void setArrayOfArrays(java.util.List<java.util.List<String>> arrayOfArrays) {
            this.arrayOfArrays = arrayOfArrays;
        }
        public java.util.List<Union3ProductOrTagOrUser> getComplexMixed() {
            return this.complexMixed;
        }

        public void setComplexMixed(java.util.List<Union3ProductOrTagOrUser> complexMixed) {
            this.complexMixed = complexMixed;
        }
    }

    public static class PartialMixedArrays {
        private java.util.Optional<java.util.List<Union4BoolOrFloatOrIntOrString>> primitiveArray;
        private java.util.Optional<java.util.List<java.util.Optional<String>>> nullableArray;
        private java.util.Optional<java.util.List<java.util.Optional<String>>> optionalItems;
        private java.util.Optional<java.util.List<java.util.List<String>>> arrayOfArrays;
        private java.util.Optional<java.util.List<Union3ProductOrTagOrUser>> complexMixed;

        public java.util.Optional<java.util.List<Union4BoolOrFloatOrIntOrString>> getPrimitiveArray() {
            return this.primitiveArray;
        }

        public void setPrimitiveArray(java.util.Optional<java.util.List<Union4BoolOrFloatOrIntOrString>> primitiveArray) {
            this.primitiveArray = primitiveArray;
        }
        public java.util.Optional<java.util.List<java.util.Optional<String>>> getNullableArray() {
            return this.nullableArray;
        }

        public void setNullableArray(java.util.Optional<java.util.List<java.util.Optional<String>>> nullableArray) {
            this.nullableArray = nullableArray;
        }
        public java.util.Optional<java.util.List<java.util.Optional<String>>> getOptionalItems() {
            return this.optionalItems;
        }

        public void setOptionalItems(java.util.Optional<java.util.List<java.util.Optional<String>>> optionalItems) {
            this.optionalItems = optionalItems;
        }
        public java.util.Optional<java.util.List<java.util.List<String>>> getArrayOfArrays() {
            return this.arrayOfArrays;
        }

        public void setArrayOfArrays(java.util.Optional<java.util.List<java.util.List<String>>> arrayOfArrays) {
            this.arrayOfArrays = arrayOfArrays;
        }
        public java.util.Optional<java.util.List<Union3ProductOrTagOrUser>> getComplexMixed() {
            return this.complexMixed;
        }

        public void setComplexMixed(java.util.Optional<java.util.List<Union3ProductOrTagOrUser>> complexMixed) {
            this.complexMixed = complexMixed;
        }
    }
    public static class NestedArrays {
        private java.util.List<java.util.List<long>> matrix;
        private java.util.List<java.util.List<String>> stringMatrix;
        private java.util.List<java.util.List<java.util.List<double>>> threeDimensional;

        public java.util.List<java.util.List<long>> getMatrix() {
            return this.matrix;
        }

        public void setMatrix(java.util.List<java.util.List<long>> matrix) {
            this.matrix = matrix;
        }
        public java.util.List<java.util.List<String>> getStringMatrix() {
            return this.stringMatrix;
        }

        public void setStringMatrix(java.util.List<java.util.List<String>> stringMatrix) {
            this.stringMatrix = stringMatrix;
        }
        public java.util.List<java.util.List<java.util.List<double>>> getThreeDimensional() {
            return this.threeDimensional;
        }

        public void setThreeDimensional(java.util.List<java.util.List<java.util.List<double>>> threeDimensional) {
            this.threeDimensional = threeDimensional;
        }
    }

    public static class PartialNestedArrays {
        private java.util.Optional<java.util.List<java.util.List<long>>> matrix;
        private java.util.Optional<java.util.List<java.util.List<String>>> stringMatrix;
        private java.util.Optional<java.util.List<java.util.List<java.util.List<double>>>> threeDimensional;

        public java.util.Optional<java.util.List<java.util.List<long>>> getMatrix() {
            return this.matrix;
        }

        public void setMatrix(java.util.Optional<java.util.List<java.util.List<long>>> matrix) {
            this.matrix = matrix;
        }
        public java.util.Optional<java.util.List<java.util.List<String>>> getStringMatrix() {
            return this.stringMatrix;
        }

        public void setStringMatrix(java.util.Optional<java.util.List<java.util.List<String>>> stringMatrix) {
            this.stringMatrix = stringMatrix;
        }
        public java.util.Optional<java.util.List<java.util.List<java.util.List<double>>>> getThreeDimensional() {
            return this.threeDimensional;
        }

        public void setThreeDimensional(java.util.Optional<java.util.List<java.util.List<java.util.List<double>>>> threeDimensional) {
            this.threeDimensional = threeDimensional;
        }
    }
    public static class ObjectArrays {
        private java.util.List<User> users;
        private java.util.List<Product> products;
        private java.util.List<Tag> tags;

        public java.util.List<User> getUsers() {
            return this.users;
        }

        public void setUsers(java.util.List<User> users) {
            this.users = users;
        }
        public java.util.List<Product> getProducts() {
            return this.products;
        }

        public void setProducts(java.util.List<Product> products) {
            this.products = products;
        }
        public java.util.List<Tag> getTags() {
            return this.tags;
        }

        public void setTags(java.util.List<Tag> tags) {
            this.tags = tags;
        }
    }

    public static class PartialObjectArrays {
        private java.util.Optional<java.util.List<User>> users;
        private java.util.Optional<java.util.List<Product>> products;
        private java.util.Optional<java.util.List<Tag>> tags;

        public java.util.Optional<java.util.List<User>> getUsers() {
            return this.users;
        }

        public void setUsers(java.util.Optional<java.util.List<User>> users) {
            this.users = users;
        }
        public java.util.Optional<java.util.List<Product>> getProducts() {
            return this.products;
        }

        public void setProducts(java.util.Optional<java.util.List<Product>> products) {
            this.products = products;
        }
        public java.util.Optional<java.util.List<Tag>> getTags() {
            return this.tags;
        }

        public void setTags(java.util.Optional<java.util.List<Tag>> tags) {
            this.tags = tags;
        }
    }
    public static class Product {
        private long id;
        private String name;
        private double price;
        private java.util.List<String> tags;
        private boolean inStock;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public double getPrice() {
            return this.price;
        }

        public void setPrice(double price) {
            this.price = price;
        }
        public java.util.List<String> getTags() {
            return this.tags;
        }

        public void setTags(java.util.List<String> tags) {
            this.tags = tags;
        }
        public boolean getInStock() {
            return this.inStock;
        }

        public void setInStock(boolean inStock) {
            this.inStock = inStock;
        }
    }

    public static class PartialProduct {
        private long id;
        private String name;
        private double price;
        private java.util.Optional<java.util.List<String>> tags;
        private boolean inStock;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public double getPrice() {
            return this.price;
        }

        public void setPrice(double price) {
            this.price = price;
        }
        public java.util.Optional<java.util.List<String>> getTags() {
            return this.tags;
        }

        public void setTags(java.util.Optional<java.util.List<String>> tags) {
            this.tags = tags;
        }
        public boolean getInStock() {
            return this.inStock;
        }

        public void setInStock(boolean inStock) {
            this.inStock = inStock;
        }
    }
    public static class SimpleArrays {
        private java.util.List<String> strings;
        private java.util.List<long> integers;
        private java.util.List<double> floats;
        private java.util.List<boolean> booleans;

        public java.util.List<String> getStrings() {
            return this.strings;
        }

        public void setStrings(java.util.List<String> strings) {
            this.strings = strings;
        }
        public java.util.List<long> getIntegers() {
            return this.integers;
        }

        public void setIntegers(java.util.List<long> integers) {
            this.integers = integers;
        }
        public java.util.List<double> getFloats() {
            return this.floats;
        }

        public void setFloats(java.util.List<double> floats) {
            this.floats = floats;
        }
        public java.util.List<boolean> getBooleans() {
            return this.booleans;
        }

        public void setBooleans(java.util.List<boolean> booleans) {
            this.booleans = booleans;
        }
    }

    public static class PartialSimpleArrays {
        private java.util.Optional<java.util.List<String>> strings;
        private java.util.Optional<java.util.List<long>> integers;
        private java.util.Optional<java.util.List<double>> floats;
        private java.util.Optional<java.util.List<boolean>> booleans;

        public java.util.Optional<java.util.List<String>> getStrings() {
            return this.strings;
        }

        public void setStrings(java.util.Optional<java.util.List<String>> strings) {
            this.strings = strings;
        }
        public java.util.Optional<java.util.List<long>> getIntegers() {
            return this.integers;
        }

        public void setIntegers(java.util.Optional<java.util.List<long>> integers) {
            this.integers = integers;
        }
        public java.util.Optional<java.util.List<double>> getFloats() {
            return this.floats;
        }

        public void setFloats(java.util.Optional<java.util.List<double>> floats) {
            this.floats = floats;
        }
        public java.util.Optional<java.util.List<boolean>> getBooleans() {
            return this.booleans;
        }

        public void setBooleans(java.util.Optional<java.util.List<boolean>> booleans) {
            this.booleans = booleans;
        }
    }
    public static class Tag {
        private long id;
        private String name;
        private String color;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getColor() {
            return this.color;
        }

        public void setColor(String color) {
            this.color = color;
        }
    }

    public static class PartialTag {
        private long id;
        private String name;
        private String color;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getColor() {
            return this.color;
        }

        public void setColor(String color) {
            this.color = color;
        }
    }
    public static class User {
        private long id;
        private String name;
        private String email;
        private boolean isActive;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getEmail() {
            return this.email;
        }

        public void setEmail(String email) {
            this.email = email;
        }
        public boolean getIsActive() {
            return this.isActive;
        }

        public void setIsActive(boolean isActive) {
            this.isActive = isActive;
        }
    }

    public static class PartialUser {
        private long id;
        private String name;
        private String email;
        private boolean isActive;

        public long getId() {
            return this.id;
        }

        public void setId(long id) {
            this.id = id;
        }
        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
        public String getEmail() {
            return this.email;
        }

        public void setEmail(String email) {
            this.email = email;
        }
        public boolean getIsActive() {
            return this.isActive;
        }

        public void setIsActive(boolean isActive) {
            this.isActive = isActive;
        }
    }
}
