// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML union types.
 */
public class Unions {

    public static final class Union3BoolOrIntOrString {

        private final String value0;

        private final Long value1;

        private final Boolean value2;


        private Union3BoolOrIntOrString(String value0, Long value1, Boolean value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3BoolOrIntOrString ofVariant0(String value) {
            return new Union3BoolOrIntOrString(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union3BoolOrIntOrString ofVariant1(Long value) {
            return new Union3BoolOrIntOrString(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union3BoolOrIntOrString ofVariant2(Boolean value) {
            return new Union3BoolOrIntOrString(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Boolean getVariant2() {
            return this.value2;
        }

    }

    public static final class Union3ProductOrTagOrUser {

        private final Types.User value0;

        private final Types.Product value1;

        private final Types.Tag value2;


        private Union3ProductOrTagOrUser(Types.User value0, Types.Product value1, Types.Tag value2) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

        }


        public static Union3ProductOrTagOrUser ofVariant0(Types.User value) {
            return new Union3ProductOrTagOrUser(value, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public Types.User getVariant0() {
            return this.value0;
        }

        public static Union3ProductOrTagOrUser ofVariant1(Types.Product value) {
            return new Union3ProductOrTagOrUser(null, value, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Types.Product getVariant1() {
            return this.value1;
        }

        public static Union3ProductOrTagOrUser ofVariant2(Types.Tag value) {
            return new Union3ProductOrTagOrUser(null, null, value);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Types.Tag getVariant2() {
            return this.value2;
        }

    }

    public static final class Union4BoolOrFloatOrIntOrString {

        private final String value0;

        private final Long value1;

        private final Double value2;

        private final Boolean value3;


        private Union4BoolOrFloatOrIntOrString(String value0, Long value1, Double value2, Boolean value3) {

            this.value0 = value0;

            this.value1 = value1;

            this.value2 = value2;

            this.value3 = value3;

        }


        public static Union4BoolOrFloatOrIntOrString ofVariant0(String value) {
            return new Union4BoolOrFloatOrIntOrString(value, null, null, null);
        }

        public boolean isVariant0() {
            return this.value0 != null;
        }

        public String getVariant0() {
            return this.value0;
        }

        public static Union4BoolOrFloatOrIntOrString ofVariant1(Long value) {
            return new Union4BoolOrFloatOrIntOrString(null, value, null, null);
        }

        public boolean isVariant1() {
            return this.value1 != null;
        }

        public Long getVariant1() {
            return this.value1;
        }

        public static Union4BoolOrFloatOrIntOrString ofVariant2(Double value) {
            return new Union4BoolOrFloatOrIntOrString(null, null, value, null);
        }

        public boolean isVariant2() {
            return this.value2 != null;
        }

        public Double getVariant2() {
            return this.value2;
        }

        public static Union4BoolOrFloatOrIntOrString ofVariant3(Boolean value) {
            return new Union4BoolOrFloatOrIntOrString(null, null, null, value);
        }

        public boolean isVariant3() {
            return this.value3 != null;
        }

        public Boolean getVariant3() {
            return this.value3;
        }

    }

}
