use std::collections::BTreeMap;

use dir_writer::{FileCollector, GeneratorArgs, IntermediateRepr, LanguageFeatures};

use crate::{
    functions::{
        render_classes, render_enums, render_functions, render_runtime_code, render_source_files,
        render_unions, UnionJava, UnionJavaVariant,
    },
    ir_to_java::{
        classes::ir_class_to_java, enums::ir_enum_to_java, functions::ir_function_to_java, TypeJava,
    },
    package::CurrentRenderPackage,
};

mod functions;
mod ir_to_java;
mod package;

#[derive(Default)]
pub struct JavaLanguageFeatures;

impl LanguageFeatures for JavaLanguageFeatures {
    const CONTENT_PREFIX: &'static str = r#"
// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
        "#;

    fn name() -> &'static str {
        "java"
    }

    fn generate_sdk_files(
        &self,
        collector: &mut FileCollector<Self>,
        ir: std::sync::Arc<IntermediateRepr>,
        args: &GeneratorArgs,
    ) -> Result<(), anyhow::Error> {
        let package_name = args.client_package_name.as_deref().unwrap_or("baml_client");
        let pkg = CurrentRenderPackage::new(package_name, ir.clone());
        let file_map = args.file_map_as_json_string()?;

        let prefix = "baml_client/";
        collector.add_file(
            format!("{}BamlSourceMap.java", prefix),
            render_source_files(&file_map)?,
        )?;
        collector.add_file(
            format!("{}Globals.java", prefix),
            render_runtime_code(&pkg)?,
        )?;

        let functions = ir
            .functions
            .iter()
            .map(|f| ir_function_to_java(f, &pkg))
            .collect::<Vec<_>>();
        collector.add_file(
            format!("{}Functions.java", prefix),
            render_functions(&functions, &pkg)?,
        )?;

        let classes = ir
            .walk_classes()
            .map(|c| ir_class_to_java(c.item, &pkg))
            .collect::<Vec<_>>();
        if !classes.is_empty() {
            collector.add_file(
                format!("{}Types.java", prefix),
                render_classes(&classes, &pkg)?,
            )?;
        }

        let enums = ir
            .walk_enums()
            .map(|e| ir_enum_to_java(e.item, &pkg))
            .collect::<Vec<_>>();
        if !enums.is_empty() {
            collector.add_file(format!("{}Enums.java", prefix), render_enums(&enums, &pkg)?)?;
        }

        // Collect all union types referenced by functions/classes and generate helpers.
        fn collect_unions_from_type<'a>(
            ty: &TypeJava,
            unions: &mut BTreeMap<String, UnionJava<'a>>,
            pkg: &'a CurrentRenderPackage,
        ) {
            match ty {
                TypeJava::List(inner) | TypeJava::Optional(inner) => {
                    collect_unions_from_type(inner, unions, pkg)
                }
                TypeJava::Map(k, v) => {
                    collect_unions_from_type(k, unions, pkg);
                    collect_unions_from_type(v, unions, pkg);
                }
                TypeJava::Union { name, options } => {
                    if !unions.contains_key(name) {
                        let variants = options
                            .iter()
                            .enumerate()
                            .map(|(index, t)| UnionJavaVariant {
                                index,
                                type_java: t.clone(),
                            })
                            .collect();
                        unions.insert(
                            name.clone(),
                            UnionJava {
                                name: name.clone(),
                                variants,
                                _pkg: pkg,
                            },
                        );
                    }
                    for opt in options {
                        collect_unions_from_type(opt, unions, pkg);
                    }
                }
                _ => {}
            }
        }

        let mut unions: BTreeMap<String, UnionJava<'_>> = BTreeMap::new();

        for func in &functions {
            for (_, arg_ty) in &func.args {
                collect_unions_from_type(arg_ty, &mut unions, &pkg);
            }
            collect_unions_from_type(&func.return_type, &mut unions, &pkg);
        }

        for class in &classes {
            for field in &class.fields {
                collect_unions_from_type(&field.r#type, &mut unions, &pkg);
            }
        }

        if !unions.is_empty() {
            let unions_vec: Vec<_> = unions.into_values().collect();
            collector.add_file(
                format!("{}Unions.java", prefix),
                render_unions(&unions_vec, &pkg)?,
            )?;
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use std::str::FromStr;

    use dir_writer::LanguageFeatures;

    #[test]
    fn test_name() {
        let gen_type =
            baml_types::GeneratorOutputType::from_str(crate::JavaLanguageFeatures::name())
                .expect("JavaLanguageFeatures name should be a valid GeneratorOutputType");
        assert_eq!(gen_type, baml_types::GeneratorOutputType::Java);
    }
}

#[cfg(test)]
mod java_codegen_tests {
    use test_harness::{create_code_gen_test_suites, TestLanguageFeatures};

    impl TestLanguageFeatures for crate::JavaLanguageFeatures {
        fn test_name() -> &'static str {
            "java"
        }
    }

    create_code_gen_test_suites!(crate::JavaLanguageFeatures);
}
