// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * BAML source file map. Do not edit.
 */
public final class BamlSourceMap {
    public static String getSourceMap() {
        return "{\"baml_src/main.baml\":\"class SimpleClass {\\r\\n    digits int\\r\\n    words string  @stream.with_state\\r\\n}\\r\\n\\r\\nfunction MakeSimpleClass() -> SimpleClass {\\r\\n    client \\\"openai/gpt-4o-mini\\\"\\r\\n    prompt #\\\"\\r\\n        {{ ctx.output_format }}\\r\\n    \\\"#\\r\\n}\\r\\n\\r\\nfunction ConsumeSimpleClass(item: SimpleClass) -> SimpleClass {\\r\\n    client \\\"openai/gpt-4o-mini\\\"\\r\\n    prompt #\\\"\\r\\n        Return back to me verbatim:\\r\\n\\r\\n        {{ item }}\\r\\n    \\\"#\\r\\n}\\r\\n\\r\\ntest MakeSimpleClassTest {\\r\\n    functions [MakeSimpleClass]\\r\\n    args {}\\r\\n}\\r\\n\"}";
    }
}
