// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;
    
    import com.boundaryml.baml.BamlRuntime;
    import com.boundaryml.baml.BamlEncoder;
    import com.boundaryml.baml.BamlDecoder;
    import com.boundaryml.baml.BamlStream;
    import java.util.LinkedHashMap;
    import java.util.Map;
    import java.util.function.Function;
    
    /**
     * Generated BAML function wrappers. Use Globals.getRuntime() and call these methods.
     * Requires baml-runtime-java for BamlRuntime, encode/decode helpers.
     */
    public final class Functions {
        private final BamlRuntime runtime;
    
        public Functions(BamlRuntime runtime) {
            this.runtime = runtime;
        }
    
    
        public Types.SimpleClass ConsumeSimpleClass(Types.SimpleClass item) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("item", item);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("ConsumeSimpleClass", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.SimpleClass typed = (Types.SimpleClass) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialSimpleClass, Types.SimpleClass> ConsumeSimpleClassStream(Types.SimpleClass item) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("item", item);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialSimpleClass> partialDecoder = bytes -> (Types.PartialSimpleClass) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.SimpleClass> finalDecoder = bytes -> (Types.SimpleClass) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("ConsumeSimpleClass", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.SimpleClass MakeSimpleClass() {
            Map<String, Object> kwargs = new LinkedHashMap<>();
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("MakeSimpleClass", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.SimpleClass typed = (Types.SimpleClass) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialSimpleClass, Types.SimpleClass> MakeSimpleClassStream() {
            Map<String, Object> kwargs = new LinkedHashMap<>();
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialSimpleClass> partialDecoder = bytes -> (Types.PartialSimpleClass) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.SimpleClass> finalDecoder = bytes -> (Types.SimpleClass) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("MakeSimpleClass", encoded, partialDecoder, finalDecoder);
        }
    
    
    }
    