// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;

/**
 * Generated BAML class types.
 */
public class Types {
    public static class SimpleClass {
        private long digits;
        private String words;

        public long getDigits() {
            return this.digits;
        }

        public void setDigits(long digits) {
            this.digits = digits;
        }
        public String getWords() {
            return this.words;
        }

        public void setWords(String words) {
            this.words = words;
        }
    }

    public static class PartialSimpleClass {
        private long digits;
        private String words;

        public long getDigits() {
            return this.digits;
        }

        public void setDigits(long digits) {
            this.digits = digits;
        }
        public String getWords() {
            return this.words;
        }

        public void setWords(String words) {
            this.words = words;
        }
    }
}
