// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;
    
    import com.boundaryml.baml.BamlRuntime;
    import com.boundaryml.baml.BamlEncoder;
    import com.boundaryml.baml.BamlDecoder;
    import com.boundaryml.baml.BamlStream;
    import java.util.LinkedHashMap;
    import java.util.Map;
    import java.util.function.Function;
    
    /**
     * Generated BAML function wrappers. Use Globals.getRuntime() and call these methods.
     * Requires baml-runtime-java for BamlRuntime, encode/decode helpers.
     */
    public final class Functions {
        private final BamlRuntime runtime;
    
        public Functions(BamlRuntime runtime) {
            this.runtime = runtime;
        }
    
    
        public Types.NullableTypes TestAllNull(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestAllNull", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.NullableTypes typed = (Types.NullableTypes) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialNullableTypes, Types.NullableTypes> TestAllNullStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialNullableTypes> partialDecoder = bytes -> (Types.PartialNullableTypes) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.NullableTypes> finalDecoder = bytes -> (Types.NullableTypes) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestAllNull", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.OptionalFields TestAllOptionalOmitted(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestAllOptionalOmitted", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.OptionalFields typed = (Types.OptionalFields) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialOptionalFields, Types.OptionalFields> TestAllOptionalOmittedStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialOptionalFields> partialDecoder = bytes -> (Types.PartialOptionalFields) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.OptionalFields> finalDecoder = bytes -> (Types.OptionalFields) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestAllOptionalOmitted", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.MixedOptionalNullable TestMixedOptionalNullable(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestMixedOptionalNullable", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.MixedOptionalNullable typed = (Types.MixedOptionalNullable) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialMixedOptionalNullable, Types.MixedOptionalNullable> TestMixedOptionalNullableStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialMixedOptionalNullable> partialDecoder = bytes -> (Types.PartialMixedOptionalNullable) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.MixedOptionalNullable> finalDecoder = bytes -> (Types.MixedOptionalNullable) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestMixedOptionalNullable", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.NullableTypes TestNullableTypes(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestNullableTypes", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.NullableTypes typed = (Types.NullableTypes) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialNullableTypes, Types.NullableTypes> TestNullableTypesStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialNullableTypes> partialDecoder = bytes -> (Types.PartialNullableTypes) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.NullableTypes> finalDecoder = bytes -> (Types.NullableTypes) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestNullableTypes", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.OptionalFields TestOptionalFields(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("TestOptionalFields", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.OptionalFields typed = (Types.OptionalFields) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialOptionalFields, Types.OptionalFields> TestOptionalFieldsStream(String input) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("input", input);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialOptionalFields> partialDecoder = bytes -> (Types.PartialOptionalFields) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.OptionalFields> finalDecoder = bytes -> (Types.OptionalFields) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("TestOptionalFields", encoded, partialDecoder, finalDecoder);
        }
    
    
    }
    