// ----------------------------------------------------------------------------
//
//  Welcome to BAML! This Java client was generated by BAML.
//  Add the baml-runtime-java dependency to your project to use it.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client;
    
    import com.boundaryml.baml.BamlRuntime;
    import com.boundaryml.baml.BamlEncoder;
    import com.boundaryml.baml.BamlDecoder;
    import com.boundaryml.baml.BamlStream;
    import java.util.LinkedHashMap;
    import java.util.Map;
    import java.util.function.Function;
    
    /**
     * Generated BAML function wrappers. Use Globals.getRuntime() and call these methods.
     * Requires baml-runtime-java for BamlRuntime, encode/decode helpers.
     */
    public final class Functions {
        private final BamlRuntime runtime;
    
        public Functions(BamlRuntime runtime) {
            this.runtime = runtime;
        }
    
    
        public Enums.Category ClassifyArticle(String text) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("text", text);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("ClassifyArticle", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Enums.Category typed = (Enums.Category) decoded;
            return typed;
        }
    
        public BamlStream<Enums.Category, Enums.Category> ClassifyArticleStream(String text) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("text", text);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Enums.Category> partialDecoder = bytes -> (Enums.Category) BamlDecoder.decodeResult(bytes);
            Function<byte[], Enums.Category> finalDecoder = bytes -> (Enums.Category) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("ClassifyArticle", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.Article CreateArticle(String topic) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("topic", topic);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("CreateArticle", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.Article typed = (Types.Article) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialArticle, Types.Article> CreateArticleStream(String topic) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("topic", topic);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialArticle> partialDecoder = bytes -> (Types.PartialArticle) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.Article> finalDecoder = bytes -> (Types.Article) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("CreateArticle", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.PureDynamic GetDynamicResponse(String prompt) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("prompt", prompt);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("GetDynamicResponse", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.PureDynamic typed = (Types.PureDynamic) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialPureDynamic, Types.PureDynamic> GetDynamicResponseStream(String prompt) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("prompt", prompt);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialPureDynamic> partialDecoder = bytes -> (Types.PartialPureDynamic) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.PureDynamic> finalDecoder = bytes -> (Types.PureDynamic) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("GetDynamicResponse", encoded, partialDecoder, finalDecoder);
        }
    
    
        public Types.Person GetPerson(String description) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("description", description);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            byte[] response = runtime.callFunctionParse("GetPerson", encoded);
            Object decoded = BamlDecoder.decodeResult(response);
            @SuppressWarnings("unchecked")
            Types.Person typed = (Types.Person) decoded;
            return typed;
        }
    
        public BamlStream<Types.PartialPerson, Types.Person> GetPersonStream(String description) {
            Map<String, Object> kwargs = new LinkedHashMap<>();
            kwargs.put("description", description);
    
            byte[] encoded = BamlEncoder.encodeArgs(kwargs);
            Function<byte[], Types.PartialPerson> partialDecoder = bytes -> (Types.PartialPerson) BamlDecoder.decodeResult(bytes);
            Function<byte[], Types.Person> finalDecoder = bytes -> (Types.Person) BamlDecoder.decodeResult(bytes);
            return runtime.callFunctionStream("GetPerson", encoded, partialDecoder, finalDecoder);
        }
    
    
    }
    