// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: baml/cffi/v1/baml_object.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Enum for all possible object types
public enum Baml_Cffi_V1_BamlObjectType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case objectUnspecified // = 0
  case objectCollector // = 1
  case objectFunctionLog // = 2
  case objectUsage // = 3
  case objectTiming // = 4
  case objectStreamTiming // = 5
  case objectLlmCall // = 6
  case objectLlmStreamCall // = 7
  case objectHTTPRequest // = 8
  case objectHTTPResponse // = 9
  case objectHTTPBody // = 10
  case objectSseResponse // = 11
  case objectMediaImage // = 12
  case objectMediaAudio // = 13
  case objectMediaPdf // = 14
  case objectMediaVideo // = 15
  case objectTypeBuilder // = 16
  case objectType // = 17
  case objectEnumBuilder // = 18
  case objectEnumValueBuilder // = 19
  case objectClassBuilder // = 20
  case objectClassPropertyBuilder // = 21
  case UNRECOGNIZED(Int)

  public init() {
    self = .objectUnspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .objectUnspecified
    case 1: self = .objectCollector
    case 2: self = .objectFunctionLog
    case 3: self = .objectUsage
    case 4: self = .objectTiming
    case 5: self = .objectStreamTiming
    case 6: self = .objectLlmCall
    case 7: self = .objectLlmStreamCall
    case 8: self = .objectHTTPRequest
    case 9: self = .objectHTTPResponse
    case 10: self = .objectHTTPBody
    case 11: self = .objectSseResponse
    case 12: self = .objectMediaImage
    case 13: self = .objectMediaAudio
    case 14: self = .objectMediaPdf
    case 15: self = .objectMediaVideo
    case 16: self = .objectTypeBuilder
    case 17: self = .objectType
    case 18: self = .objectEnumBuilder
    case 19: self = .objectEnumValueBuilder
    case 20: self = .objectClassBuilder
    case 21: self = .objectClassPropertyBuilder
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .objectUnspecified: return 0
    case .objectCollector: return 1
    case .objectFunctionLog: return 2
    case .objectUsage: return 3
    case .objectTiming: return 4
    case .objectStreamTiming: return 5
    case .objectLlmCall: return 6
    case .objectLlmStreamCall: return 7
    case .objectHTTPRequest: return 8
    case .objectHTTPResponse: return 9
    case .objectHTTPBody: return 10
    case .objectSseResponse: return 11
    case .objectMediaImage: return 12
    case .objectMediaAudio: return 13
    case .objectMediaPdf: return 14
    case .objectMediaVideo: return 15
    case .objectTypeBuilder: return 16
    case .objectType: return 17
    case .objectEnumBuilder: return 18
    case .objectEnumValueBuilder: return 19
    case .objectClassBuilder: return 20
    case .objectClassPropertyBuilder: return 21
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Baml_Cffi_V1_BamlObjectType] = [
    .objectUnspecified,
    .objectCollector,
    .objectFunctionLog,
    .objectUsage,
    .objectTiming,
    .objectStreamTiming,
    .objectLlmCall,
    .objectLlmStreamCall,
    .objectHTTPRequest,
    .objectHTTPResponse,
    .objectHTTPBody,
    .objectSseResponse,
    .objectMediaImage,
    .objectMediaAudio,
    .objectMediaPdf,
    .objectMediaVideo,
    .objectTypeBuilder,
    .objectType,
    .objectEnumBuilder,
    .objectEnumValueBuilder,
    .objectClassBuilder,
    .objectClassPropertyBuilder,
  ]

}

/// Raw pointer type
public struct Baml_Cffi_V1_BamlPointerType: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var pointer: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Raw object with type information
public struct Baml_Cffi_V1_BamlObjectHandle: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var object: Baml_Cffi_V1_BamlObjectHandle.OneOf_Object? = nil

  public var collector: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .collector(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .collector(newValue)}
  }

  public var functionLog: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .functionLog(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .functionLog(newValue)}
  }

  public var usage: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .usage(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .usage(newValue)}
  }

  public var timing: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .timing(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .timing(newValue)}
  }

  public var streamTiming: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .streamTiming(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .streamTiming(newValue)}
  }

  public var llmCall: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .llmCall(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .llmCall(newValue)}
  }

  public var llmStreamCall: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .llmStreamCall(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .llmStreamCall(newValue)}
  }

  public var httpRequest: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .httpRequest(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .httpRequest(newValue)}
  }

  public var httpResponse: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .httpResponse(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .httpResponse(newValue)}
  }

  public var httpBody: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .httpBody(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .httpBody(newValue)}
  }

  public var sseResponse: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .sseResponse(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .sseResponse(newValue)}
  }

  public var mediaImage: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .mediaImage(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .mediaImage(newValue)}
  }

  public var mediaAudio: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .mediaAudio(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .mediaAudio(newValue)}
  }

  public var mediaPdf: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .mediaPdf(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .mediaPdf(newValue)}
  }

  public var mediaVideo: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .mediaVideo(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .mediaVideo(newValue)}
  }

  public var typeBuilder: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .typeBuilder(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .typeBuilder(newValue)}
  }

  public var type: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .type(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .type(newValue)}
  }

  public var enumBuilder: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .enumBuilder(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .enumBuilder(newValue)}
  }

  public var enumValueBuilder: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .enumValueBuilder(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .enumValueBuilder(newValue)}
  }

  public var classBuilder: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .classBuilder(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .classBuilder(newValue)}
  }

  public var classPropertyBuilder: Baml_Cffi_V1_BamlPointerType {
    get {
      if case .classPropertyBuilder(let v)? = object {return v}
      return Baml_Cffi_V1_BamlPointerType()
    }
    set {object = .classPropertyBuilder(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Object: Equatable, Sendable {
    case collector(Baml_Cffi_V1_BamlPointerType)
    case functionLog(Baml_Cffi_V1_BamlPointerType)
    case usage(Baml_Cffi_V1_BamlPointerType)
    case timing(Baml_Cffi_V1_BamlPointerType)
    case streamTiming(Baml_Cffi_V1_BamlPointerType)
    case llmCall(Baml_Cffi_V1_BamlPointerType)
    case llmStreamCall(Baml_Cffi_V1_BamlPointerType)
    case httpRequest(Baml_Cffi_V1_BamlPointerType)
    case httpResponse(Baml_Cffi_V1_BamlPointerType)
    case httpBody(Baml_Cffi_V1_BamlPointerType)
    case sseResponse(Baml_Cffi_V1_BamlPointerType)
    case mediaImage(Baml_Cffi_V1_BamlPointerType)
    case mediaAudio(Baml_Cffi_V1_BamlPointerType)
    case mediaPdf(Baml_Cffi_V1_BamlPointerType)
    case mediaVideo(Baml_Cffi_V1_BamlPointerType)
    case typeBuilder(Baml_Cffi_V1_BamlPointerType)
    case type(Baml_Cffi_V1_BamlPointerType)
    case enumBuilder(Baml_Cffi_V1_BamlPointerType)
    case enumValueBuilder(Baml_Cffi_V1_BamlPointerType)
    case classBuilder(Baml_Cffi_V1_BamlPointerType)
    case classPropertyBuilder(Baml_Cffi_V1_BamlPointerType)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "baml.cffi.v1"

extension Baml_Cffi_V1_BamlObjectType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0OBJECT_UNSPECIFIED\0\u{1}OBJECT_COLLECTOR\0\u{1}OBJECT_FUNCTION_LOG\0\u{1}OBJECT_USAGE\0\u{1}OBJECT_TIMING\0\u{1}OBJECT_STREAM_TIMING\0\u{1}OBJECT_LLM_CALL\0\u{1}OBJECT_LLM_STREAM_CALL\0\u{1}OBJECT_HTTP_REQUEST\0\u{1}OBJECT_HTTP_RESPONSE\0\u{1}OBJECT_HTTP_BODY\0\u{1}OBJECT_SSE_RESPONSE\0\u{1}OBJECT_MEDIA_IMAGE\0\u{1}OBJECT_MEDIA_AUDIO\0\u{1}OBJECT_MEDIA_PDF\0\u{1}OBJECT_MEDIA_VIDEO\0\u{1}OBJECT_TYPE_BUILDER\0\u{1}OBJECT_TYPE\0\u{1}OBJECT_ENUM_BUILDER\0\u{1}OBJECT_ENUM_VALUE_BUILDER\0\u{1}OBJECT_CLASS_BUILDER\0\u{1}OBJECT_CLASS_PROPERTY_BUILDER\0")
}

extension Baml_Cffi_V1_BamlPointerType: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BamlPointerType"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}pointer\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.pointer) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pointer != 0 {
      try visitor.visitSingularInt64Field(value: self.pointer, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Baml_Cffi_V1_BamlPointerType, rhs: Baml_Cffi_V1_BamlPointerType) -> Bool {
    if lhs.pointer != rhs.pointer {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_BamlObjectHandle: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BamlObjectHandle"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}collector\0\u{3}function_log\0\u{1}usage\0\u{1}timing\0\u{3}stream_timing\0\u{3}llm_call\0\u{3}llm_stream_call\0\u{3}http_request\0\u{3}http_response\0\u{3}http_body\0\u{3}sse_response\0\u{3}media_image\0\u{3}media_audio\0\u{3}media_pdf\0\u{3}media_video\0\u{3}type_builder\0\u{1}type\0\u{3}enum_builder\0\u{3}enum_value_builder\0\u{3}class_builder\0\u{3}class_property_builder\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .collector(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .collector(v)
        }
      }()
      case 2: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .functionLog(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .functionLog(v)
        }
      }()
      case 3: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .usage(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .usage(v)
        }
      }()
      case 4: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .timing(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .timing(v)
        }
      }()
      case 5: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .streamTiming(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .streamTiming(v)
        }
      }()
      case 6: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .llmCall(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .llmCall(v)
        }
      }()
      case 7: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .llmStreamCall(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .llmStreamCall(v)
        }
      }()
      case 8: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .httpRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .httpRequest(v)
        }
      }()
      case 9: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .httpResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .httpResponse(v)
        }
      }()
      case 10: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .httpBody(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .httpBody(v)
        }
      }()
      case 11: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .sseResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .sseResponse(v)
        }
      }()
      case 12: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .mediaImage(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .mediaImage(v)
        }
      }()
      case 13: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .mediaAudio(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .mediaAudio(v)
        }
      }()
      case 14: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .mediaPdf(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .mediaPdf(v)
        }
      }()
      case 15: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .mediaVideo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .mediaVideo(v)
        }
      }()
      case 16: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .typeBuilder(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .typeBuilder(v)
        }
      }()
      case 17: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .type(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .type(v)
        }
      }()
      case 18: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .enumBuilder(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .enumBuilder(v)
        }
      }()
      case 19: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .enumValueBuilder(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .enumValueBuilder(v)
        }
      }()
      case 20: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .classBuilder(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .classBuilder(v)
        }
      }()
      case 21: try {
        var v: Baml_Cffi_V1_BamlPointerType?
        var hadOneofValue = false
        if let current = self.object {
          hadOneofValue = true
          if case .classPropertyBuilder(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.object = .classPropertyBuilder(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.object {
    case .collector?: try {
      guard case .collector(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .functionLog?: try {
      guard case .functionLog(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .usage?: try {
      guard case .usage(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .timing?: try {
      guard case .timing(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .streamTiming?: try {
      guard case .streamTiming(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .llmCall?: try {
      guard case .llmCall(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .llmStreamCall?: try {
      guard case .llmStreamCall(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .httpRequest?: try {
      guard case .httpRequest(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .httpResponse?: try {
      guard case .httpResponse(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .httpBody?: try {
      guard case .httpBody(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .sseResponse?: try {
      guard case .sseResponse(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .mediaImage?: try {
      guard case .mediaImage(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .mediaAudio?: try {
      guard case .mediaAudio(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case .mediaPdf?: try {
      guard case .mediaPdf(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
    }()
    case .mediaVideo?: try {
      guard case .mediaVideo(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
    }()
    case .typeBuilder?: try {
      guard case .typeBuilder(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
    }()
    case .type?: try {
      guard case .type(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 17)
    }()
    case .enumBuilder?: try {
      guard case .enumBuilder(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
    }()
    case .enumValueBuilder?: try {
      guard case .enumValueBuilder(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 19)
    }()
    case .classBuilder?: try {
      guard case .classBuilder(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
    }()
    case .classPropertyBuilder?: try {
      guard case .classPropertyBuilder(let v)? = self.object else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Baml_Cffi_V1_BamlObjectHandle, rhs: Baml_Cffi_V1_BamlObjectHandle) -> Bool {
    if lhs.object != rhs.object {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
