// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: baml/cffi/v1/baml_object_methods.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Baml_Cffi_V1_BamlObjectMethodInvocation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var object: Baml_Cffi_V1_BamlObjectHandle {
    get {_object ?? Baml_Cffi_V1_BamlObjectHandle()}
    set {_object = newValue}
  }
  /// Returns true if `object` has been explicitly set.
  var hasObject: Bool {self._object != nil}
  /// Clears the value of `object`. Subsequent reads from it will return its default value.
  mutating func clearObject() {self._object = nil}

  var methodName: String = String()

  var kwargs: [Baml_Cffi_V1_HostMapEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _object: Baml_Cffi_V1_BamlObjectHandle? = nil
}

struct Baml_Cffi_V1_BamlObjectConstructorInvocation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Baml_Cffi_V1_BamlObjectType = .objectUnspecified

  var kwargs: [Baml_Cffi_V1_HostMapEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// only one of these will be set
/// proto doesn't allow oneofs with repeated fields
struct Baml_Cffi_V1_InvocationResponseSuccess: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var result: Baml_Cffi_V1_InvocationResponseSuccess.OneOf_Result? = nil

  var object: Baml_Cffi_V1_BamlObjectHandle {
    get {
      if case .object(let v)? = result {return v}
      return Baml_Cffi_V1_BamlObjectHandle()
    }
    set {result = .object(newValue)}
  }

  var objects: Baml_Cffi_V1_RepeatedBamlObjectHandle {
    get {
      if case .objects(let v)? = result {return v}
      return Baml_Cffi_V1_RepeatedBamlObjectHandle()
    }
    set {result = .objects(newValue)}
  }

  var value: Baml_Cffi_V1_CFFIValueHolder {
    get {
      if case .value(let v)? = result {return v}
      return Baml_Cffi_V1_CFFIValueHolder()
    }
    set {result = .value(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Result: Equatable, Sendable {
    case object(Baml_Cffi_V1_BamlObjectHandle)
    case objects(Baml_Cffi_V1_RepeatedBamlObjectHandle)
    case value(Baml_Cffi_V1_CFFIValueHolder)

  }

  init() {}
}

struct Baml_Cffi_V1_RepeatedBamlObjectHandle: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var objects: [Baml_Cffi_V1_BamlObjectHandle] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// from either:
/// BamlObjectConstructorInvocation
/// BamlObjectMethodInvocation
struct Baml_Cffi_V1_InvocationResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var response: Baml_Cffi_V1_InvocationResponse.OneOf_Response? = nil

  var success: Baml_Cffi_V1_InvocationResponseSuccess {
    get {
      if case .success(let v)? = response {return v}
      return Baml_Cffi_V1_InvocationResponseSuccess()
    }
    set {response = .success(newValue)}
  }

  var error: String {
    get {
      if case .error(let v)? = response {return v}
      return String()
    }
    set {response = .error(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Response: Equatable, Sendable {
    case success(Baml_Cffi_V1_InvocationResponseSuccess)
    case error(String)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "baml.cffi.v1"

extension Baml_Cffi_V1_BamlObjectMethodInvocation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BamlObjectMethodInvocation"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}object\0\u{3}method_name\0\u{1}kwargs\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._object) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.methodName) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.kwargs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._object {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.methodName.isEmpty {
      try visitor.visitSingularStringField(value: self.methodName, fieldNumber: 2)
    }
    if !self.kwargs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.kwargs, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_BamlObjectMethodInvocation, rhs: Baml_Cffi_V1_BamlObjectMethodInvocation) -> Bool {
    if lhs._object != rhs._object {return false}
    if lhs.methodName != rhs.methodName {return false}
    if lhs.kwargs != rhs.kwargs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_BamlObjectConstructorInvocation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BamlObjectConstructorInvocation"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}kwargs\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.kwargs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != .objectUnspecified {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 1)
    }
    if !self.kwargs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.kwargs, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_BamlObjectConstructorInvocation, rhs: Baml_Cffi_V1_BamlObjectConstructorInvocation) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.kwargs != rhs.kwargs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_InvocationResponseSuccess: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InvocationResponseSuccess"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}object\0\u{1}objects\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Baml_Cffi_V1_BamlObjectHandle?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .object(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .object(v)
        }
      }()
      case 2: try {
        var v: Baml_Cffi_V1_RepeatedBamlObjectHandle?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .objects(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .objects(v)
        }
      }()
      case 3: try {
        var v: Baml_Cffi_V1_CFFIValueHolder?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .value(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .value(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .object?: try {
      guard case .object(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .objects?: try {
      guard case .objects(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .value?: try {
      guard case .value(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_InvocationResponseSuccess, rhs: Baml_Cffi_V1_InvocationResponseSuccess) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_RepeatedBamlObjectHandle: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RepeatedBamlObjectHandle"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}objects\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.objects) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.objects.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.objects, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_RepeatedBamlObjectHandle, rhs: Baml_Cffi_V1_RepeatedBamlObjectHandle) -> Bool {
    if lhs.objects != rhs.objects {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_InvocationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InvocationResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Baml_Cffi_V1_InvocationResponseSuccess?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .success(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .success(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.response != nil {try decoder.handleConflictingOneOf()}
          self.response = .error(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.response {
    case .success?: try {
      guard case .success(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_InvocationResponse, rhs: Baml_Cffi_V1_InvocationResponse) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
