// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: baml/cffi/v1/baml_inbound.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Core value type
///
/// Things we have chosen to not track:
/// - the type of the value
/// - if the value is optional
/// - if the value is a union variant
///
/// Reasoning: not every language has these concepts
/// (e.g. python has no way to represent a union variant)
///
/// Later we can add optional containers with type information for the languages that do
/// support them as that will improve speed of decoding.
struct Baml_Cffi_V1_HostValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Do not use an explict null value.
  /// An HostValue can have value be missing entirely to signify a null value.
  /// HostNullValue null_value = 1;
  var value: Baml_Cffi_V1_HostValue.OneOf_Value? = nil

  var stringValue: String {
    get {
      if case .stringValue(let v)? = value {return v}
      return String()
    }
    set {value = .stringValue(newValue)}
  }

  var intValue: Int64 {
    get {
      if case .intValue(let v)? = value {return v}
      return 0
    }
    set {value = .intValue(newValue)}
  }

  var floatValue: Double {
    get {
      if case .floatValue(let v)? = value {return v}
      return 0
    }
    set {value = .floatValue(newValue)}
  }

  var boolValue: Bool {
    get {
      if case .boolValue(let v)? = value {return v}
      return false
    }
    set {value = .boolValue(newValue)}
  }

  var listValue: Baml_Cffi_V1_HostListValue {
    get {
      if case .listValue(let v)? = value {return v}
      return Baml_Cffi_V1_HostListValue()
    }
    set {value = .listValue(newValue)}
  }

  var mapValue: Baml_Cffi_V1_HostMapValue {
    get {
      if case .mapValue(let v)? = value {return v}
      return Baml_Cffi_V1_HostMapValue()
    }
    set {value = .mapValue(newValue)}
  }

  var classValue: Baml_Cffi_V1_HostClassValue {
    get {
      if case .classValue(let v)? = value {return v}
      return Baml_Cffi_V1_HostClassValue()
    }
    set {value = .classValue(newValue)}
  }

  var enumValue: Baml_Cffi_V1_HostEnumValue {
    get {
      if case .enumValue(let v)? = value {return v}
      return Baml_Cffi_V1_HostEnumValue()
    }
    set {value = .enumValue(newValue)}
  }

  var handle: Baml_Cffi_V1_BamlObjectHandle {
    get {
      if case .handle(let v)? = value {return v}
      return Baml_Cffi_V1_BamlObjectHandle()
    }
    set {value = .handle(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Do not use an explict null value.
  /// An HostValue can have value be missing entirely to signify a null value.
  /// HostNullValue null_value = 1;
  enum OneOf_Value: Equatable, Sendable {
    case stringValue(String)
    case intValue(Int64)
    case floatValue(Double)
    case boolValue(Bool)
    case listValue(Baml_Cffi_V1_HostListValue)
    case mapValue(Baml_Cffi_V1_HostMapValue)
    case classValue(Baml_Cffi_V1_HostClassValue)
    case enumValue(Baml_Cffi_V1_HostEnumValue)
    case handle(Baml_Cffi_V1_BamlObjectHandle)

  }

  init() {}
}

struct Baml_Cffi_V1_HostListValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var values: [Baml_Cffi_V1_HostValue] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Baml_Cffi_V1_HostMapValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var entries: [Baml_Cffi_V1_HostMapEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Baml_Cffi_V1_HostMapEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var key: Baml_Cffi_V1_HostMapEntry.OneOf_Key? = nil

  var stringKey: String {
    get {
      if case .stringKey(let v)? = key {return v}
      return String()
    }
    set {key = .stringKey(newValue)}
  }

  var intKey: Int64 {
    get {
      if case .intKey(let v)? = key {return v}
      return 0
    }
    set {key = .intKey(newValue)}
  }

  var boolKey: Bool {
    get {
      if case .boolKey(let v)? = key {return v}
      return false
    }
    set {key = .boolKey(newValue)}
  }

  var enumKey: Baml_Cffi_V1_HostEnumValue {
    get {
      if case .enumKey(let v)? = key {return v}
      return Baml_Cffi_V1_HostEnumValue()
    }
    set {key = .enumKey(newValue)}
  }

  var value: Baml_Cffi_V1_HostValue {
    get {_value ?? Baml_Cffi_V1_HostValue()}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  mutating func clearValue() {self._value = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Key: Equatable, Sendable {
    case stringKey(String)
    case intKey(Int64)
    case boolKey(Bool)
    case enumKey(Baml_Cffi_V1_HostEnumValue)

  }

  init() {}

  fileprivate var _value: Baml_Cffi_V1_HostValue? = nil
}

struct Baml_Cffi_V1_HostClassValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  /// fields with implict/default values can be omitted
  /// this includes null values
  var fields: [Baml_Cffi_V1_HostMapEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Baml_Cffi_V1_HostEnumValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var value: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Baml_Cffi_V1_HostFunctionArguments: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// named function arguments
  var kwargs: [Baml_Cffi_V1_HostMapEntry] = []

  var clientRegistry: Baml_Cffi_V1_HostClientRegistry {
    get {_clientRegistry ?? Baml_Cffi_V1_HostClientRegistry()}
    set {_clientRegistry = newValue}
  }
  /// Returns true if `clientRegistry` has been explicitly set.
  var hasClientRegistry: Bool {self._clientRegistry != nil}
  /// Clears the value of `clientRegistry`. Subsequent reads from it will return its default value.
  mutating func clearClientRegistry() {self._clientRegistry = nil}

  var env: [Baml_Cffi_V1_HostEnvVar] = []

  /// collectors only
  var collectors: [Baml_Cffi_V1_BamlObjectHandle] = []

  /// type builder only
  var typeBuilder: Baml_Cffi_V1_BamlObjectHandle {
    get {_typeBuilder ?? Baml_Cffi_V1_BamlObjectHandle()}
    set {_typeBuilder = newValue}
  }
  /// Returns true if `typeBuilder` has been explicitly set.
  var hasTypeBuilder: Bool {self._typeBuilder != nil}
  /// Clears the value of `typeBuilder`. Subsequent reads from it will return its default value.
  mutating func clearTypeBuilder() {self._typeBuilder = nil}

  /// tags
  var tags: [Baml_Cffi_V1_HostMapEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _clientRegistry: Baml_Cffi_V1_HostClientRegistry? = nil
  fileprivate var _typeBuilder: Baml_Cffi_V1_BamlObjectHandle? = nil
}

struct Baml_Cffi_V1_HostClientRegistry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var primary: String {
    get {_primary ?? String()}
    set {_primary = newValue}
  }
  /// Returns true if `primary` has been explicitly set.
  var hasPrimary: Bool {self._primary != nil}
  /// Clears the value of `primary`. Subsequent reads from it will return its default value.
  mutating func clearPrimary() {self._primary = nil}

  var clients: [Baml_Cffi_V1_HostClientProperty] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _primary: String? = nil
}

struct Baml_Cffi_V1_HostClientProperty: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var provider: String = String()

  var retryPolicy: String {
    get {_retryPolicy ?? String()}
    set {_retryPolicy = newValue}
  }
  /// Returns true if `retryPolicy` has been explicitly set.
  var hasRetryPolicy: Bool {self._retryPolicy != nil}
  /// Clears the value of `retryPolicy`. Subsequent reads from it will return its default value.
  mutating func clearRetryPolicy() {self._retryPolicy = nil}

  var options: [Baml_Cffi_V1_HostMapEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _retryPolicy: String? = nil
}

struct Baml_Cffi_V1_HostEnvVar: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var key: String = String()

  var value: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "baml.cffi.v1"

extension Baml_Cffi_V1_HostValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}string_value\0\u{3}int_value\0\u{3}float_value\0\u{3}bool_value\0\u{3}list_value\0\u{3}map_value\0\u{3}class_value\0\u{3}enum_value\0\u{1}handle\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .stringValue(v)
        }
      }()
      case 3: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .intValue(v)
        }
      }()
      case 4: try {
        var v: Double?
        try decoder.decodeSingularDoubleField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .floatValue(v)
        }
      }()
      case 5: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .boolValue(v)
        }
      }()
      case 6: try {
        var v: Baml_Cffi_V1_HostListValue?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .listValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .listValue(v)
        }
      }()
      case 7: try {
        var v: Baml_Cffi_V1_HostMapValue?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .mapValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .mapValue(v)
        }
      }()
      case 8: try {
        var v: Baml_Cffi_V1_HostClassValue?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .classValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .classValue(v)
        }
      }()
      case 9: try {
        var v: Baml_Cffi_V1_HostEnumValue?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .enumValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .enumValue(v)
        }
      }()
      case 10: try {
        var v: Baml_Cffi_V1_BamlObjectHandle?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .handle(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .handle(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .stringValue?: try {
      guard case .stringValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case .intValue?: try {
      guard case .intValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    }()
    case .floatValue?: try {
      guard case .floatValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    }()
    case .boolValue?: try {
      guard case .boolValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    }()
    case .listValue?: try {
      guard case .listValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .mapValue?: try {
      guard case .mapValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .classValue?: try {
      guard case .classValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .enumValue?: try {
      guard case .enumValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .handle?: try {
      guard case .handle(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_HostValue, rhs: Baml_Cffi_V1_HostValue) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_HostListValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostListValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}values\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.values) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.values.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.values, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_HostListValue, rhs: Baml_Cffi_V1_HostListValue) -> Bool {
    if lhs.values != rhs.values {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_HostMapValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostMapValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}entries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_HostMapValue, rhs: Baml_Cffi_V1_HostMapValue) -> Bool {
    if lhs.entries != rhs.entries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_HostMapEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostMapEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}string_key\0\u{3}int_key\0\u{3}bool_key\0\u{4}\u{2}enum_key\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.key != nil {try decoder.handleConflictingOneOf()}
          self.key = .stringKey(v)
        }
      }()
      case 2: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.key != nil {try decoder.handleConflictingOneOf()}
          self.key = .intKey(v)
        }
      }()
      case 3: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.key != nil {try decoder.handleConflictingOneOf()}
          self.key = .boolKey(v)
        }
      }()
      case 5: try {
        var v: Baml_Cffi_V1_HostEnumValue?
        var hadOneofValue = false
        if let current = self.key {
          hadOneofValue = true
          if case .enumKey(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.key = .enumKey(v)
        }
      }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.key {
    case .stringKey?: try {
      guard case .stringKey(let v)? = self.key else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .intKey?: try {
      guard case .intKey(let v)? = self.key else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 2)
    }()
    case .boolKey?: try {
      guard case .boolKey(let v)? = self.key else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    }()
    case .enumKey?: try {
      guard case .enumKey(let v)? = self.key else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try { if let v = self._value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_HostMapEntry, rhs: Baml_Cffi_V1_HostMapEntry) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs._value != rhs._value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_HostClassValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostClassValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}fields\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.fields) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.fields.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fields, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_HostClassValue, rhs: Baml_Cffi_V1_HostClassValue) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.fields != rhs.fields {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_HostEnumValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostEnumValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_HostEnumValue, rhs: Baml_Cffi_V1_HostEnumValue) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_HostFunctionArguments: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostFunctionArguments"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}kwargs\0\u{3}client_registry\0\u{1}env\0\u{1}collectors\0\u{3}type_builder\0\u{1}tags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.kwargs) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._clientRegistry) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.env) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.collectors) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._typeBuilder) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.tags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.kwargs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.kwargs, fieldNumber: 1)
    }
    try { if let v = self._clientRegistry {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.env.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.env, fieldNumber: 3)
    }
    if !self.collectors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.collectors, fieldNumber: 4)
    }
    try { if let v = self._typeBuilder {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.tags.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tags, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_HostFunctionArguments, rhs: Baml_Cffi_V1_HostFunctionArguments) -> Bool {
    if lhs.kwargs != rhs.kwargs {return false}
    if lhs._clientRegistry != rhs._clientRegistry {return false}
    if lhs.env != rhs.env {return false}
    if lhs.collectors != rhs.collectors {return false}
    if lhs._typeBuilder != rhs._typeBuilder {return false}
    if lhs.tags != rhs.tags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_HostClientRegistry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostClientRegistry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}primary\0\u{1}clients\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._primary) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.clients) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._primary {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    if !self.clients.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.clients, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_HostClientRegistry, rhs: Baml_Cffi_V1_HostClientRegistry) -> Bool {
    if lhs._primary != rhs._primary {return false}
    if lhs.clients != rhs.clients {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_HostClientProperty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostClientProperty"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}provider\0\u{3}retry_policy\0\u{1}options\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.provider) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._retryPolicy) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.options) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.provider.isEmpty {
      try visitor.visitSingularStringField(value: self.provider, fieldNumber: 2)
    }
    try { if let v = self._retryPolicy {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    if !self.options.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.options, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_HostClientProperty, rhs: Baml_Cffi_V1_HostClientProperty) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.provider != rhs.provider {return false}
    if lhs._retryPolicy != rhs._retryPolicy {return false}
    if lhs.options != rhs.options {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Baml_Cffi_V1_HostEnvVar: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostEnvVar"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Baml_Cffi_V1_HostEnvVar, rhs: Baml_Cffi_V1_HostEnvVar) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
